# TODO: Translation updated at 2026-08-02 23:21

translate chinese strings:

    old "Self-voicing disabled."
    new "自述语音已禁用。"
    old "Clipboard voicing enabled. "
    new "剪贴板语音已启用。"
    old "Self-voicing enabled. "
    new "自述语音已启用。"
    old "bar"
    new "进度条"
    old "selected"
    new "已选择"
    old "viewport"
    new "视口"
    old "horizontal scroll"
    new "横向滚动"
    old "vertical scroll"
    new "垂直滚动"
    old "activate"
    new "激活"
    old "deactivate"
    new "停用"
    old "increase"
    new "增加"
    old "decrease"
    new "减少"
    old "Font Override"
    new "字体覆盖"
    old "Default"
    new "默认"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "OpenDyslexic"
    old "Text Size Scaling"
    new "文字大小缩放"
    old "Reset"
    new "重置"
    old "Line Spacing Scaling"
    new "行距缩放"
    old "High Contrast Text"
    new "高对比度文本"
    old "Enable"
    new "启用"
    old "Disable"
    new "禁用"
    old "Self-Voicing"
    new "自述语音"
    old "Text-to-speech"
    new "语音朗读"
    old "Clipboard"
    new "剪贴板"
    old "Debug"
    new "调试"
    old "Self-Voicing Volume Drop"
    new "自述语音音量降低"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "本菜单中的选项旨在改善无障碍体验。它们可能并非适用于所有游戏，某些选项组合甚至可能令游戏无法正常游玩。这并非游戏或引擎的问题。更换字体时，为获得最佳效果，请尽量保持文字大小与原来一致。"
    old "{#weekday}Monday"
    new "{#weekday}星期一"
    old "{#weekday}Tuesday"
    new "{#weekday}星期二"
    old "{#weekday}Wednesday"
    new "{#weekday}星期三"
    old "{#weekday}Thursday"
    new "{#weekday}星期四"
    old "{#weekday}Friday"
    new "{#weekday}星期五"
    old "{#weekday}Saturday"
    new "{#weekday}星期六"
    old "{#weekday}Sunday"
    new "{#weekday}星期日"
    old "{#weekday_short}Mon"
    new "{#weekday_short}周一"
    old "{#weekday_short}Tue"
    new "{#weekday_short}周二"
    old "{#weekday_short}Wed"
    new "{#weekday_short}周三"
    old "{#weekday_short}Thu"
    new "{#weekday_short}周四"
    old "{#weekday_short}Fri"
    new "{#weekday_short}周五"
    old "{#weekday_short}Sat"
    new "{#weekday_short}周六"
    old "{#weekday_short}Sun"
    new "{#weekday_short}周日"
    old "{#month}January"
    new "{#month}一月"
    old "{#month}February"
    new "{#month}二月"
    old "{#month}March"
    new "{#month}三月"
    old "{#month}April"
    new "{#month}四月"
    old "{#month}May"
    new "{#month}五月"
    old "{#month}June"
    new "{#month}六月"
    old "{#month}July"
    new "{#month}七月"
    old "{#month}August"
    new "{#month}八月"
    old "{#month}September"
    new "{#month}九月"
    old "{#month}October"
    new "{#month}十月"
    old "{#month}November"
    new "{#month}十一月"
    old "{#month}December"
    new "{#month}十二月"
    old "{#month_short}Jan"
    new "{#month_short}1月"
    old "{#month_short}Feb"
    new "{#month_short}2月"
    old "{#month_short}Mar"
    new "{#month_short}3月"
    old "{#month_short}Apr"
    new "{#month_short}4月"
    old "{#month_short}May"
    new "{#month_short}5月"
    old "{#month_short}Jun"
    new "{#month_short}6月"
    old "{#month_short}Jul"
    new "{#month_short}7月"
    old "{#month_short}Aug"
    new "{#month_short}8月"
    old "{#month_short}Sep"
    new "{#month_short}9月"
    old "{#month_short}Oct"
    new "{#month_short}10月"
    old "{#month_short}Nov"
    new "{#month_short}11月"
    old "{#month_short}Dec"
    new "{#month_short}12月"
    old "%b %d, %H:%M"
    new "%b %d日 %H:%M"
    old "Save slot %s: [text]"
    new "存档槽 %s：[text]"
    old "Load slot %s: [text]"
    new "读取存档槽 %s：[text]"
    old "Delete slot [text]"
    new "删除存档槽 [text]"
    old "File page auto"
    new "自动存档页"
    old "File page quick"
    new "快速存档页"
    old "File page [text]"
    new "存档页 [text]"
    old "Quick saves"
    new "快速存档"
    old "Next file page."
    new "下一存档页。"
    old "Previous file page."
    new "上一存档页。"
    old "Quick save complete."
    new "快速存档完成。"
    old "Quick save."
    new "快速存档。"
    old "Quick load."
    new "快速读取。"
    old "Language [text]"
    new "语言 [text]"
    old "The interactive director is not enabled here."
    new "此处未启用互动导演模式。"
    old "⬆"
    new "⬆"
    old "⬇"
    new "⬇"
    old "Done"
    new "完成"
    old "(statement)"
    new "（语句）"
    old "(tag)"
    new "（标签）"
    old "(attributes)"
    new "（属性）"
    old "(transform)"
    new "（变换）"
    old "(transition)"
    new "（过渡）"
    old "(channel)"
    new "（频道）"
    old "(filename)"
    new "（文件名）"
    old "Change"
    new "更改"
    old "Add"
    new "添加"
    old "Cancel"
    new "取消"
    old "Remove"
    new "移除"
    old "Statement:"
    new "语句："
    old "Tag:"
    new "标签："
    old "Attributes:"
    new "属性："
    old "Transforms:"
    new "变换："
    old "Behind:"
    new "后方："
    old "Transition:"
    new "过渡："
    old "Channel:"
    new "频道："
    old "Audio Filename:"
    new "音频文件名："
    old "Are you sure?"
    new "确定吗？"
    old "Are you sure you want to delete this save?"
    new "确定要删除这个存档吗？"
    old "Are you sure you want to overwrite your save?"
    new "确定要覆盖当前存档吗？"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "加载将丢失未保存的进度。\n确定要这么做吗？"
    old "Are you sure you want to quit?"
    new "确定要退出吗？"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "确定要返回主菜单吗？\n未保存的进度将全部丢失。"
    old "Are you sure you want to end the replay?"
    new "确定要结束回放吗？"
    old "Are you sure you want to begin skipping?"
    new "确定要开始跳过吗？"
    old "Are you sure you want to skip to the next choice?"
    new "确定要跳到下一个选项吗？"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "确定要跳过未读对话，直接跳到下一个选项吗？"
    old "Failed to save screenshot as %s."
    new "无法将截图保存为 %s。"
    old "Saved screenshot as %s."
    new "截图已保存为 %s。"
    old "Skip Mode"
    new "跳过模式"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "本程序包含依据多种许可证发布的自由软件，其中包括 MIT 许可证和 GNU 宽通用公共许可证。完整的软件清单（含全部源码链接）可参见{a=https://www.renpy.org/l/license}这里{/a}。"
    old "display"
    new "显示"
    old "transitions"
    new "过渡"
    old "skip transitions"
    new "跳过过渡"
    old "video sprites"
    new "视频精灵"
    old "show empty window"
    new "显示空窗口"
    old "text speed"
    new "文字速度"
    old "joystick"
    new "手柄"
    old "joystick..."
    new "手柄..."
    old "skip"
    new "跳过"
    old "skip unseen [text]"
    new "跳过未读[text]"
    old "skip unseen text"
    new "跳过未读文本"
    old "begin skipping"
    new "开始跳过"
    old "after choices"
    new "选项后"
    old "skip after choices"
    new "选项后跳过"
    old "auto-forward time"
    new "自动前进间隔"
    old "auto-forward"
    new "自动前进"
    old "Auto forward"
    new "自动前进"
    old "auto-forward after click"
    new "点击后自动前进"
    old "automatic move"
    new "自动移动"
    old "wait for voice"
    new "等待语音"
    old "voice sustain"
    new "语音延续"
    old "self voicing"
    new "自述语音"
    old "self voicing volume drop"
    new "自述语音音量降低"
    old "clipboard voicing"
    new "剪贴板语音"
    old "debug voicing"
    new "调试语音"
    old "emphasize audio"
    new "强调音效"
    old "rollback side"
    new "回滚侧"
    old "gl powersave"
    new "GL 节能"
    old "gl framerate"
    new "GL 帧率"
    old "gl tearing"
    new "GL 撕裂"
    old "font transform"
    new "字体变换"
    old "font size"
    new "字体大小"
    old "font line spacing"
    new "字体行距"
    old "system cursor"
    new "系统光标"
    old "renderer menu"
    new "渲染器菜单"
    old "accessibility menu"
    new "无障碍菜单"
    old "high contrast text"
    new "高对比度文本"
    old "music volume"
    new "音乐音量"
    old "sound volume"
    new "音效音量"
    old "voice volume"
    new "语音音量"
    old "mute music"
    new "音乐静音"
    old "mute sound"
    new "音效静音"
    old "mute voice"
    new "语音静音"
    old "mute all"
    new "全部静音"
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new "剪贴板语音已启用。按“Shift+C”可关闭。"
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new "自述语音将朗读“[renpy.display.tts.last]”。按“Alt+Shift+V”可关闭。"
    old "Self-voicing enabled. Press 'v' to disable."
    new "自述语音已启用。按“V”键关闭。"
    old "Developer Menu"
    new "开发者菜单"
    old "Interactive Director (D)"
    new "互动导演（D）"
    old "Reload Game (Shift+R)"
    new "重新加载游戏（Shift+R）"
    old "Console (Shift+O)"
    new "控制台（Shift+O）"
    old "Variable Viewer"
    new "变量查看器"
    old "Image Location Picker"
    new "图像位置选择器"
    old "Filename List"
    new "文件名列表"
    old "Show Image Load Log (F4)"
    new "显示图像加载日志（F4）"
    old "Hide Image Load Log (F4)"
    new "隐藏图像加载日志（F4）"
    old "Image Attributes"
    new "图像属性"
    old "[name] [attributes] (hidden)"
    new "[name] [attributes]（隐藏）"
    old "[name] [attributes]"
    new "[name] [attributes]"
    old "Nothing to inspect."
    new "没有可检查的内容。"
    old "Hide deleted"
    new "隐藏已删除"
    old "Show deleted"
    new "显示已删除"
    old "Return to the developer menu"
    new "返回开发者菜单"
    old "Rectangle: %r"
    new "矩形：%r"
    old "Mouse position: %r"
    new "鼠标位置：%r"
    old "Right-click or escape to quit."
    new "右键点击或按 Esc 退出。"
    old "Rectangle copied to clipboard."
    new "矩形已复制到剪贴板。"
    old "Position copied to clipboard."
    new "位置已复制到剪贴板。"
    old "Type to filter: "
    new "输入以筛选："
    old "Textures: [tex_count] ([tex_size_mb:.1f] MB)"
    new "纹理数：[tex_count]（[tex_size_mb:.1f] MB）"
    old "Image cache: [cache_pct:.1f]% ([cache_size_mb:.1f] MB)"
    new "图像缓存：[cache_pct:.1f]%（[cache_size_mb:.1f] MB）"
    old "✔ "
    new "✔"
    old "✘ "
    new "✘"
    old "\n{color=#cfc}✔ predicted image (good){/color}\n{color=#fcc}✘ unpredicted image (bad){/color}\n{color=#fff}Drag to move.{/color}"
    new "\n{color=#cfc}✔ 已预测图像（好）{/color}\n{color=#fcc}✘ 未预测图像（差）{/color}\n{color=#fff}拖动以移动。{/color}"
    old "Displayable Inspector"
    new "显示对象检查器"
    old "Size"
    new "大小"
    old "Style"
    new "样式"
    old "Location"
    new "位置"
    old "Inspecting Styles of [displayable_name!q]"
    new "正在检查 [displayable_name!q] 的样式"
    old "displayable:"
    new "显示对象："
    old "        (no properties affect the displayable)"
    new "（没有任何属性会影响该显示对象）"
    old "        (default properties omitted)"
    new "（已省略默认属性）"
    old "<repr() failed>"
    new "<repr() 失败>"
    old "Joystick Mapping"
    new "手柄映射"
    old "Empty Slot."
    new "空存档位。"
    old "a"
    new "一个"
    old "q"
    new "q"
    old "Contacting App Store\nPlease Wait..."
    new "正在连接应用商店\n请稍候……"
    old "The Ren'Py Updater is not supported on mobile devices."
    new "Ren'Py 更新器不支持移动设备。"
    old "An error is being simulated."
    new "正在模拟一个错误。"
    old "Either this project does not support updating, or the update status file was deleted."
    new "可能是此项目不支持更新，也可能是更新状态文件已被删除。"
    old "This account does not have permission to perform an update."
    new "该账户没有执行更新的权限。"
    old "This account does not have permission to write the update log."
    new "该账户没有写入更新日志的权限。"
    old "Could not verify update signature."
    new "无法验证更新签名。"
    old "The update file was not downloaded."
    new "更新文件未能下载。"
    old "The update file does not have the correct digest - it may have been corrupted."
    new "更新文件的摘要不正确——文件可能已损坏。"
    old "While unpacking {}, unknown type {}."
    new "解包 {} 时遇到未知类型 {}。"
    old "Updater"
    new "更新器"
    old "An error has occured:"
    new "发生错误："
    old "Checking for updates."
    new "正在检查更新。"
    old "This program is up to date."
    new "该程序已是最新版本。"
    old "[u.version] is available. Do you want to install it?"
    new "有新版本 [u.version] 可用。是否安装？"
    old "Preparing to download the updates."
    new "正在准备下载更新。"
    old "Downloading the updates."
    new "正在下载更新。"
    old "Unpacking the updates."
    new "正在解压更新。"
    old "Finishing up."
    new "即将完成。"
    old "The updates have been installed. The program will restart."
    new "更新已安装，程序将重新启动。"
    old "The updates have been installed."
    new "更新已安装。"
    old "The updates were cancelled."
    new "更新已取消。"
    old "Image [index] of [count] locked."
    new "图片 [index] / [count] 已锁定。"
    old "prev"
    new "上一个"
    old "next"
    new "下一个"
    old "slideshow"
    new "幻灯片"
    old "return"
    new "返回"
    old "Renderer"
    new "渲染器"
    old "Automatically Choose"
    new "自动选择"
    old "Force GL Renderer"
    new "强制使用 GL 渲染器"
    old "Force ANGLE Renderer"
    new "强制使用 ANGLE 渲染器"
    old "Force GLES Renderer"
    new "强制使用 GLES 渲染器"
    old "Force GL2 Renderer"
    new "强制使用 GL2 渲染器"
    old "Force ANGLE2 Renderer"
    new "强制使用 ANGLE2 渲染器"
    old "Force GLES2 Renderer"
    new "强制使用 GLES2 渲染器"
    old "Enable (No Blocklist)"
    new "启用（无黑名单）"
    old "Powersave"
    new "省电模式"
    old "Framerate"
    new "帧率"
    old "Screen"
    new "屏幕"
    old "60"
    new "60"
    old "30"
    new "30"
    old "Tearing"
    new "撕裂"
    old "Changes will take effect the next time this program is run."
    new "更改将在下次运行程序时生效。"
    old "Performance Warning"
    new "性能警告"
    old "This computer is using software rendering."
    new "此电脑正在使用软件渲染。"
    old "This game requires use of GL2 that can't be initialised."
    new "本游戏需要使用 GL2，但无法初始化。"
    old "This computer has a problem displaying graphics: [problem]."
    new "这台电脑显示图形时出现问题：[problem]。"
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "显卡驱动可能过时或运行异常，可能导致画面卡顿或显示错误。"
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new "{a=edit:1:log.txt}log.txt{/a} 文件可能包含有助于判断电脑问题所在的信息。"
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new "有关如何解决此问题的更多详情，请参见 {a=[url]}文档{/a}。"
    old "Continue, Show this warning again"
    new "继续，并再次显示此警告"
    old "Continue, Don't show warning again"
    new "继续，且不再显示此警告"
    old "Change render options"
    new "更改渲染选项"
    old "Select Gamepad to Calibrate"
    new "选择要校准的手柄"
    old "No Gamepads Available"
    new "没有可用的手柄"
    old "Calibrating [name] ([i]/[total])"
    new "正在校准 [name]（[i]/[total]）"
    old "Press or move the '[control!s]' [kind]."
    new "按下或拨动“[control!s]”[kind]。"
    old "Skip (A)"
    new "跳过（A）"
    old "Back (B)"
    new "返回（B）"
    old "Open"
    new "打开"
    old "Opens the traceback.txt file in a text editor."
    new "用文本编辑器打开 traceback.txt 文件。"
    old "Copy BBCode"
    new "复制 BBCode"
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new "将 traceback.txt 文件以 BBCode 格式复制到剪贴板，用于 https://lemmasoft.renai.us/ 等论坛。"
    old "Copy Markdown"
    new "复制 Markdown"
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new "将 traceback.txt 文件以 Markdown 格式复制到剪贴板，用于 Discord。"
    old "An exception has occurred."
    new "发生了一个异常。"
    old "Rollback"
    new "回滚"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "尝试回滚到先前的时间点，以便你保存进度或做出不同的选择。"
    old "Ignore"
    new "忽略"
    old "Ignores the exception, allowing you to continue."
    new "忽略该异常并继续。"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "忽略该异常并继续，但这通常会导致更多错误。"
    old "Reload"
    new "重新加载"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "从磁盘重新加载游戏，并尽可能保存和恢复游戏状态。"
    old "Console"
    new "控制台"
    old "Opens a console to allow debugging the problem."
    new "打开控制台以调试该问题。"
    old "Quits the game."
    new "退出游戏。"
    old "Parsing the script failed."
    new "脚本解析失败。"
