# TODO: Translation updated at 2026-08-02 23:21

translate chinese strings:

    old "Восстановить контроль над Виндзором, чтобы не допустить осады Лондона или подготовить город к обороне, чтобы отразить предстоящую атаку Кентербери."
    new "夺回温莎的控制权，以防伦敦被围困；或加强城防，以抵御坎特伯雷即将发动的进攻。"
    old "Подготовиться к наступлению на Оксфорд.{vspace=5}Численность ваших войск должна быть выше, чем у графа Кентербери.{vspace=5}Вы должны удерживать не менее 5 провинций.{vspace=5}Власть должна быть не меньше 50."
    new "准备进攻牛津。{vspace=5}你的军队规模必须超过坎特伯雷伯爵。{vspace=5}你必须至少控制 5 个省份。{vspace=5}权力必须不低于 50。"
    old "Cобрать армию, превосходящую войска Нортхэмптона по численности.{vspace=5}Удерживать не меньше 4 провинций из списка: Гринвич, Дартфорд, Чиппенхэм, Бристоль, Виндзор."
    new "集结一支兵力超过北安普顿军队的部队。{vspace=5}至少从下列省份中控制 4 个：格林威治、达特福德、奇彭纳姆、布里斯托尔、温莎。"
    old "Cобрать армию, превосходящую войска Нортхэмптона по численности.{vspace=5}Удерживать не меньше 4 провинций из списка: Гринвич, Дартфорд, Чиппенхэм, Бристоль, Виндзор.{vspace=5}Не допустить проникновения шотландских войск в центральные регионы королевства."
    new "集结一支兵力超过北安普顿军队的部队。{vspace=5}至少从下列省份中控制 4 个：格林威治、达特福德、奇彭纳姆、布里斯托尔、温莎。{vspace=5}不得让苏格兰军队渗透进王国中部地区。"
    old "Обеспечить безопасность и процветание своего королевства, а также убедиться, что трон прочно закреплен за вашими наследниками."
    new "确保王国的安全与繁荣，并让王位牢牢掌控在你的继承人手中。"
    old "Захватить Мейдстоун и Кембридж.{vspace=5}Не допустить захвата шотландскими войсками Виндзора."
    new "占领梅德斯通和剑桥。{vspace=5}不得让苏格兰军队夺取温莎。"
    old "Восстановить контроль над Виндзором и собрать боеспособную армию для защиты королевства."
    new "夺回温莎的控制权，并组建一支有战斗力的军队保卫王国。"
    old "Local Drunkard"
    new "本地醉汉"
    old "Armed Citizen"
    new "持械平民"
    old "Giuseppe's supporter"
    new "朱塞佩的支持者"
    old "Drunk Thug"
    new "醉汉打手"
    old "Sailor"
    new "水手"
    old "Antonio"
    new "安东尼奥"
    old "Robber Crossbowman"
    new "强盗弩手"
    old "Robber"
    new "强盗"
    old "City Guard"
    new "城卫"
    old "Venetian Crossbowman"
    new "威尼斯弩手"
    old "Venetian Man-at-arms"
    new "威尼斯甲士"
    old "Venetian Sergeant-at-arms"
    new "威尼斯武装军士"
    old "Venetian Bandit"
    new "威尼斯强盗"
    old "Venetian Brigand"
    new "威尼斯劫匪"
    old "Genoese Man-at-arms"
    new "热那亚甲士"
    old "Genoese Sergeant-at-arms"
    new "热那亚武装军士"
    old "Notorious Bandit"
    new "臭名昭著的强盗"
    old "Bloodthirsty Bandit"
    new "嗜血强盗"
    old "Venetian Cutthroat"
    new "威尼斯割喉手"
    old "Bandit Sharpshooter"
    new "强盗神射手"
    old "Abductor"
    new "绑架者"
    old "Hawkwood's scout"
    new "霍克伍德的斥候"
    old "Hawkwood's mercenary"
    new "霍克伍德的雇佣兵"
    old "Napolitano's Goon"
    new "纳波利塔诺的打手"
    old "Napolitano's Bodyguard"
    new "纳波利塔诺的护卫"
    old "Napolitano's Capo"
    new "纳波利塔诺的头目"
    old "Bandit Underboss"
    new "强盗副头目"
    old "The Sparrow"
    new "麻雀"
    old "Scottish Swordsman"
    new "苏格兰剑士"
    old "Undead Swordsman"
    new "亡灵剑士"
    old "Jean Bouland"
    new "让·布兰"
    old "Enrico Selvo"
    new "恩里科·塞尔沃"
    old "Italian Man-at-arms"
    new "意大利甲士"
    old "Italian Noble"
    new "意大利贵族"
    old "Venetian Knight"
    new "威尼斯骑士"
    old "Barnabo's Knight"
    new "巴尔纳博的骑士"
    old "Genoese Knight"
    new "热那亚骑士"
    old "Lorenzo"
    new "洛伦佐"
    old "Gabriele"
    new "加布里埃莱"
    old "Carlo Imperiali"
    new "卡洛·因佩里亚利"
    old "Cavalli family bodyguard"
    new "卡瓦利家族护卫"
    old "St. George Company Veteran"
    new "圣乔治佣兵团老兵"
    old "Company Sergeant"
    new "佣兵团军士"
    old "Company Lieutenant"
    new "佣兵团副官"
    old "Company Captain"
    new "佣兵团队长"
    old "Marco di Santoro"
    new "马尔科·迪·桑托罗"
    old "Matteo Bellini"
    new "马泰奥·贝利尼"
    old "Bodyguard"
    new "护卫"
    old "{color=#A9A9A9}Обеспечить безопасность Франчески Кавалли."
    new "{color=#A9A9A9}确保弗朗切斯卡·卡瓦利的安全。"
    old "{i}{size=-7}(Джузеппе Кавалли)"
    new "{i}{size=-7}（朱塞佩·卡瓦利）"
    old "Father's Honor"
    new "父亲的荣耀"
    old "{color=#A9A9A9}Подготовиться к налёту на принадлежащий семье Контарини трактир.{vspace=5}Раздобыть лёгкое снаряжение, дубинку и маску."
    new "{color=#A9A9A9}准备突袭孔塔里尼家族名下的酒馆。{vspace=5}弄到轻便装备、一根棍棒和一个面具。"
    old "{i}{size=-7}(Данте Кавалли)"
    new "{i}{size=-7}（但丁·卡瓦利）"
    old "Could Нave Been Better"
    new "本可以更好"
    old "{color=#A9A9A9}Подготовиться к поездке в Мурано.{vspace=5}Франческа Кавалли готова смириться с тем, что вы будете её телохранителем,{vspace=1}при условии того, что вы не будете носить металлические доспехи, двуручное{vspace=1}оружие и щиты, а также прилично одеваться.{vspace=5}Требуемый престиж: от [francesca_desired_prestige!i]"
    new "{color=#A9A9A9}准备前往穆拉诺。{vspace=5}弗朗切斯卡·卡瓦利愿意接受由你担任她的护卫，{vspace=1}条件是你不穿金属铠甲、不携带双手武器{vspace=1}和盾牌，并穿着得体。{vspace=5}所需威望：[francesca_desired_prestige!i] 起"
    old "{i}{size=-7}(Франческа Кавалли)"
    new "{i}{size=-7}（弗朗切斯卡·卡瓦利）"
    old "The Dress"
    new "那条裙子"
    old "{color=#A9A9A9}Посетить ателье в Мурано и забрать платье Франчески."
    new "{color=#A9A9A9}前往穆拉诺的裁缝铺，取回弗朗切斯卡的裙子。"
    old "An Englishman and a Scot"
    new "英格兰人与苏格兰人"
    old "{color=#A9A9A9}Победить шотландского фехтовальщика на дуэли."
    new "{color=#A9A9A9}在决斗中击败苏格兰剑士。"
    old "Affairs of Love"
    new "风流韵事"
    old "{color=#A9A9A9}Передать письмо Франчески Леонардо Империали, который укрывается на вилле{vspace=5}Сан-Джиованни, в окрестностях Кьоджи."
    new "{color=#A9A9A9}将弗朗切斯卡的信交给莱昂纳多·因佩里亚利，他藏身在基奥贾附近的{vspace=5}圣乔瓦尼别墅。"
    old "Dante's Revenge"
    new "但丁的复仇"
    old "{color=#A9A9A9}Помочь Данте отыскать и допросить Николу Наполитано."
    new "{color=#A9A9A9}帮助但丁找到并审问尼科拉·纳波利塔诺。"
    old "Affairs of Love, pt. II"
    new "风流韵事·其二"
    old "{color=#A9A9A9}Посетить виллу Сан-Джиованни и передать Леонардо очередное письмо от Франчески."
    new "{color=#A9A9A9}前往圣乔瓦尼别墅，给莱昂纳多送去弗朗切斯卡的又一封信。"
    old "{color=#A9A9A9}Отправиться вместе с Данте на встречу с похитителями и передать им выкуп за Франческу.{vspace=5}Как только Франческа будет в безопасности — убить Наполитано и остальных похитителей."
    new "{color=#A9A9A9}与但丁一同去见绑匪，向他们交出弗朗切斯卡的赎金。{vspace=5}待弗朗切斯卡安全后，杀死纳波利塔诺及其余绑匪。"
    old "Chioggia"
    new "基奥贾"
    old "{color=#A9A9A9}Подготовиться к штурму Кьоджи вместе с людьми дожа.{vspace=5}Добраться до виллы Сан-Джиованни и спасти Франческу."
    new "{color=#A9A9A9}与总督的人马一同准备强攻基奥贾。{vspace=5}抵达圣乔瓦尼别墅，救出弗朗切斯卡。"
    old "Bronze for Gold"
    new "以铜换金"
    old "{color=#A9A9A9}Раздобыть [bronze_for_gold.timed_out!i] мер бронзы для кузнеца из Мурано.{vspace=15}{color=#A9A9A9}Передано: [bronze_for_gold.completed!i] из [bronze_for_gold.timed_out!i]"
    new "{color=#A9A9A9}为穆拉诺的铁匠弄到 [bronze_for_gold.timed_out!i] 份青铜。{vspace=15}{color=#A9A9A9}已交付：[bronze_for_gold.completed!i] / [bronze_for_gold.timed_out!i]"
    old "{i}{size=-7}(Кузнец из Мурано)"
    new "{i}{size=-7}（穆拉诺的铁匠）"
    old "Middle Man"
    new "中间人"
    old "{color=#A9A9A9}Отыскать Антонио Дандоло на Сант-Эразмо и заставить его вернуть обещанную{vspace=5}партию тканей.{vspace=5}Или же самостоятельно раздобыть [middle_man.timed_out!i] кусков ткани для ткацкой мастерской из Бурано.{vspace=15}{color=#A9A9A9}Передано: [middle_man.completed!i] из [middle_man.timed_out!i]"
    new "{color=#A9A9A9}在圣埃拉斯莫找到安东尼奥·丹多洛，迫使他归还承诺的那批{vspace=5}布料。{vspace=5}或者亲自为布拉诺的纺织工坊弄来 [middle_man.timed_out!i] 块布料。{vspace=15}{color=#A9A9A9}已交付：[middle_man.completed!i] / [middle_man.timed_out!i]"
    old "{i}{size=-7}(Ткацкая мастерская из Бурано)"
    new "{i}{size=-7}（布拉诺的纺织工坊）"
    old "Behind Closed Doors"
    new "门扉之后"
    old "{color=#A9A9A9}Помочь потерявшему ключи от дома венецианцу вскрыть входную дверь при{vspace=5}помощи отмычек или как-то иначе."
    new "{color=#A9A9A9}帮助一位丢了家门钥匙的威尼斯人，用撬锁工具{vspace=5}或其他手段打开大门。"
    old "{i}{size=-7}(Житель Венеции)"
    new "{i}{size=-7}（威尼斯居民）"
    old "True Venetian"
    new "真正的威尼斯人"
    old "{color=#A9A9A9}Раздобыть кузнечный молот, инструменты флетчера и помочь посетителю{vspace=5}таверны в ремонте его лодки.{vspace=5}Для успеха потребуются высокие показатели ремесла и силы."
    new "{color=#A9A9A9}弄到一把锻造锤、一套制箭工具，并帮助酒馆里的{vspace=5}一位客人修理他的船。{vspace=5}要成功需要较高的手艺与力量属性。"
    old "Smooth Talker"
    new "巧舌如簧"
    old "{color=#A9A9A9}Одеться с иголочки, прихватить алкоголь и попытаться уговорить{vspace=5}кредитора дать отсрочку должнику."
    new "{color=#A9A9A9}衣着光鲜地出门，带上酒，然后设法说服{vspace=5}债主给债务人宽限时日。"
    old "Universal Remedy"
    new "万能药"
    old "{color=#A9A9A9}Раздобыть лекарство, способное вылечить членов цирковой труппы."
    new "{color=#A9A9A9}弄到能治好马戏团团员们的药物。"
    old "Apprentice"
    new "学徒"
    old "{color=#A9A9A9}Предподать урок фехтования ученику."
    new "{color=#A9A9A9}给学徒上一堂剑术课。"
    old "La Fortuna"
    new "福尔图娜号"
    old "{color=#A9A9A9}Помочь старому рыбаку поднять ценности с борта затонувшего корабля."
    new "{color=#A9A9A9}帮助老渔夫从沉船里打捞财宝。"
    old "Regimentation"
    new "整编"
    old "{color=#A9A9A9}Повысить уровень подготовки бойцов отряда Роландо де Росси.{vspace=1}Требуемый уровень подготовки: [regimentation.timed_out!i]"
    new "{color=#A9A9A9}提升罗兰多·德·罗西小队战士的训练水平。{vspace=1}所需训练水平：[regimentation.timed_out!i]"
    old "{i}{size=-7}(Роландо де Росси)"
    new "{i}{size=-7}（罗兰多·德·罗西）"
    old "Shot Caller"
    new "发号施令者"
    old "{color=#A9A9A9}Повысить уровень своей репутации среди солдат до [shot_caller.timed_out!i]."
    new "{color=#A9A9A9}将你在士兵中的声望提升至 [shot_caller.timed_out!i]。"
    old "The Wedding"
    new "婚礼"
    old "{color=#A9A9A9}Раздобыть приличную одежду для посещения свадьбы дочери мэра Тревизо.{vspace=1}Требуемый престиж: [wedding.timed_out!i]"
    new "{color=#A9A9A9}弄一套体面的衣服，参加特雷维索市长女儿的婚礼。{vspace=1}所需威望：[wedding.timed_out!i]"
    old "The Invitation"
    new "邀请"
    old "{color=#A9A9A9}Посетить постоялый двор 'Белый бык' и узнать, кто и для чего ищет с вами{vspace=5}встречи."
    new "{color=#A9A9A9}前往“白牛”客栈，查明是谁因何事想与你{vspace=5}会面。"
    old "{i}{size=-7}(?)"
    new "{i}{size=-7}（？）"
    old "Нunter x Нunter"
    new "猎人×猎人"
    old "{color=#A9A9A9}Подстеречь Энрико Сельво в окружающих Тревизо лесах и убить его."
    new "{color=#A9A9A9}在特雷维索周边的树林中伏击恩里科·塞尔沃，将其杀死。"
    old "Strictly Business"
    new "公事公办"
    old "{color=#A9A9A9}Подбросить в лавки конкурентов Анны оккультные предметы, компромитирующие{vspace=5}их владельцев. Опционально: посетить фамильный склеп семьи Бенанданти."
    new "{color=#A9A9A9}向安娜竞争对手的店铺偷偷放入会让店主{vspace=5}难堪的秘法物品。可选：拜访贝南丹蒂家族墓穴。"
    old "Not A Step Back"
    new "寸步不退"
    old "{color=#A9A9A9}Остановить наступление генуэзских войск на Венецию, вернув Тревизо под свой контроль."
    new "{color=#A9A9A9}夺回特雷维索的控制权，阻止热那亚军队对威尼斯的进攻。"
    old "{i}{size=-7}(Doge Contarini)"
    new "{i}{size=-7}（孔塔里尼总督）"
    old "Controlling the Narrative"
    new "掌控舆论"
    old "{color=#A9A9A9}Организовать убийства Марко Ди Санторо и Маттео Беллини — политических{vspace=1}противников дожа, угрожающих внутренней стабильности Венецианской Республики.{vspace=5}Для сохранения своей анонимности, раскрытие которой может повредить{vspace=1}репутации дожа, лучше будет спрятать своё лицо под маской или капюшоном{vspace=1}плаща."
    new "{color=#A9A9A9}组织刺杀马尔科·迪·桑托罗与马泰奥·贝利尼——这两位总督的政敌，{vspace=1}正威胁着威尼斯共和国的内部稳定。{vspace=5}为保全匿名身份——一旦暴露便会损害{vspace=1}总督的声望——最好用面具或斗篷兜帽{vspace=1}遮住面孔。"
    old "Recruiting"
    new "招募"
    old "{color=#A9A9A9}Помочь венецианскому Арсеналу в привлечении добровольцев в войска,{vspace=1}передав двух опытных бардов (ур. 6 или выше)."
    new "{color=#A9A9A9}帮助威尼斯兵工厂为军队招募志愿者，{vspace=1}移交两名经验丰富的吟游诗人（6 级及以上）。"
    old "{i}{size=-7}(Venetian Arsenal)"
    new "{i}{size=-7}（威尼斯兵工厂）"
    old "Fragile Alliance: Нungary"
    new "脆弱的联盟：匈牙利"
    old "{color=#A9A9A9}Любой ценой вывести Королевство Венгрия из войны против Венеции."
    new "{color=#A9A9A9}不惜一切代价，让匈牙利王国退出与威尼斯的战争。"
    old "Fragile Alliance: Austria"
    new "脆弱的联盟：奥地利"
    old "{color=#A9A9A9}Любой ценой вывести герцогство Австрия из войны против Венеции."
    new "{color=#A9A9A9}不惜一切代价，让奥地利公国退出与威尼斯的战争。"
    old "Fragile Alliance: Padua"
    new "脆弱的联盟：帕多瓦"
    old "{color=#A9A9A9}Любой ценой вывести Падуанскую коммуну из войны против Венеции."
    new "{color=#A9A9A9}不惜一切代价，让帕多瓦公社退出与威尼斯的战争。"
    old "Fragile Alliance: Нoly Roman Empire"
    new "脆弱的联盟：神圣罗马帝国"
    old "{color=#A9A9A9}Любой ценой вывести Священную Римскую Империю из войны против Венеции."
    new "{color=#A9A9A9}不惜一切代价，让神圣罗马帝国退出与威尼斯的战争。"
    old "Fragile Alliance: Milan"
    new "脆弱的联盟：米兰"
    old "{color=#A9A9A9}Любой ценой вывести Милан из войны против Венеции."
    new "{color=#A9A9A9}不惜一切代价，让米兰退出与威尼斯的战争。"
    old "Fragile Alliance: Genoa"
    new "脆弱的联盟：热那亚"
    old "{color=#A9A9A9}Любой ценой вывести Геную из войны против Венеции."
    new "{color=#A9A9A9}不惜一切代价，让热那亚退出与威尼斯的战争。"
    old "The Carrot and the Stick"
    new "胡萝卜与大棒"
    old "{color=#A9A9A9}Оказать от имени дожа помощь госпиталю в Каннареджио и лазарету в Мурано."
    new "{color=#A9A9A9}以总督的名义，向坎纳雷焦的医院和穆拉诺的病院提供援助。"
    old "Little Black Book"
    new "小黑账本"
    old "{color=#A9A9A9}Помочь другу Джиованны Альвизу Бадоеру избавиться от долга перед{vspace=1}Эцио Моретти, устранив кредитора или же выкрав у него долговую расписку."
    new "{color=#A9A9A9}帮助乔万娜的朋友阿尔维泽·巴多埃尔摆脱对{vspace=1}埃齐奥·莫雷蒂的债务——除掉这位债主，或偷走他的借据。"
    old "{i}{size=-7}(Джованна Контарини)"
    new "{i}{size=-7}（乔万娜·孔塔里尼）"
    old "Lost But Not Forgotten"
    new "迷失但未被遗忘"
    old "{color=#A9A9A9}Разузнать о судьбе брата одной из горничных Джованны, проходящего службу{vspace=1}в гарнизоне венецианской крепости на острове Тенедос."
    new "{color=#A9A9A9}打听乔万娜一名女仆的兄长下落，他在特内多斯岛{vspace=1}威尼斯要塞的驻军中服役。"
    old "The Painting"
    new "那幅画"
    old "{color=#A9A9A9}Помочь Джованне Контарини вернуть украденную картину."
    new "{color=#A9A9A9}帮助乔万娜·孔塔里尼找回被盗的画作。"
    old "Covenant"
    new "誓约"
    old "{color=#A9A9A9}Сдержать данное Бернабо Висконти слово о том, что вы придёте ему на помощь,{vspace=1}если имперские войска вторгнутся в миланские земли."
    new "{color=#A9A9A9}履行你向贝尔纳博·维斯孔蒂许下的诺言：{vspace=1}若帝国军队入侵米兰领地，你将前来助他。"
    old "{i}{size=-7}(Бернабо Висконти)"
    new "{i}{size=-7}（贝尔纳博·维斯孔蒂）"
    old "Family Feud"
    new "家族世仇"
    old "{color=#A9A9A9}Захватить замок семьи Делла Торре неподалёку от Милана и наказать их за{vspace=1}участие в заговоре против Бернабо Висконти."
    new "{color=#A9A9A9}夺取米兰附近德拉·托雷家族的城堡，惩罚他们{vspace=1}参与针对贝尔纳博·维斯孔蒂的阴谋。"
    old "Make Stone Bleed"
    new "让顽石流血"
    old "{color=#A9A9A9}Проникнуть в замок Аквитанского рыцаря Жана Булана и убить его."
    new "{color=#A9A9A9}潜入阿基坦骑士让·布兰的城堡，将其杀死。"
    old "{i}{size=-7}(Карл Наваррский)"
    new "{i}{size=-7}（纳瓦拉的卡洛斯）"
    old "Criminals to Soldiers"
    new "罪犯变士兵"
    old "{color=#A9A9A9}Нанять на венецианскую службу французских рутьеров, укрывающихся в{vspace=1}булонском лесу."
    new "{color=#A9A9A9}雇佣躲藏在{vspace=1}布洛涅森林中的法国佣兵，为威尼斯效力。"
    old "{i}{size=-7}(Король Иоанн)"
    new "{i}{size=-7}（约翰王）"
    old "Death of the Order"
    new "骑士团的陨落"
    old "{color=#A9A9A9}Захватить крепость Эзберт в окрестностях Дамиетты и уничтожить остатки{vspace=1}ордена Тамплиеров.{vspace=10}Организовать экспедицию в Утремер можно в венецианском Арсенале."
    new "{color=#A9A9A9}攻占达米埃塔附近的埃兹伯特要塞，歼灭圣殿骑士团{vspace=1}的残余势力。{vspace=10}可在威尼斯兵工厂组织前往海外之地的远征。"
    old "Fall of a Tyrant"
    new "暴君陨落"
    old "{color=#A9A9A9}Оказать Джангалеаццо Висконти помощь в свержении его дяди Бернабо{vspace=1}Висконти, передав ему [death_of_tyrant.timed_out!i] солдат."
    new "{color=#A9A9A9}向詹加莱亚佐·维斯孔蒂提供 [death_of_tyrant.timed_out!i] 名士兵，协助他推翻其叔父贝尔纳博{vspace=1}·维斯孔蒂。"
    old "{i}{size=-7}(Джангалеаццо Висконти)"
    new "{i}{size=-7}（詹加莱亚佐·维斯孔蒂）"
    old "Enter the Schwarzburg"
    new "潜入施瓦茨堡"
    old "{color=#A9A9A9}Организовать убийство императора Карла."
    new "{color=#A9A9A9}策划刺杀皇帝卡尔。"
    old "{i}{size=-7}(Günther von Schwarzburg)"
    new "{i}{size=-7}（贡特尔·冯·施瓦茨堡）"
    old "Surcoat"
    new "罩袍"
    old "A loose robe worn over armor.{vspace=5}*Decreases fatigue gain from heat by 33%{vspace=5}*Vitality: +6{vspace=5}*Endurance: +3"
    new "穿在铠甲外面的宽松长袍。{vspace=5}*炎热产生的疲劳提升降低 33%{vspace=5}*体力：+6{vspace=5}*耐力：+3"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}urcoat"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}罩{/size}{/color}{/font}袍"
    old "Lion Нead Medallion"
    new "狮头勋章"
    old "A pendant with a lion's head made in the ancient Byzantine style.{vspace=5}*Strength and Agility: +1{vspace=5}*Prestige: +5{vspace=5}*Improves your hit chance with melee weapons{vspace=5}*The more aggressive you are in combat — the bigger the increase."
    new "一枚古拜占庭风格的狮头吊坠。{vspace=5}*力量与敏捷：+1{vspace=5}*威望：+5{vspace=5}*提升近战武器的命中率{vspace=5}*战斗中越凶悍，提升越大。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}L{/size}{/color}{/font}ion Нead Medallion"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}狮{/size}{/color}{/font}头勋章"
    old "Sharp Thorned Rose"
    new "尖刺玫瑰"
    old "A beautiful rose with razor-sharp thorns.{vspace=5}*Every 1 point of НP lost due to bleeding recovers 3 points of Stamina{vspace=5}*Every 1 point of НP lost due to bleeding recovers 3 points of Fatigue{vspace=5}*Can be used to manually self inflict a 6-turn bleeding"
    new "一朵美丽的玫瑰，尖刺锋利如剃刀。{vspace=5}*每因流血损失 1 点生命值，恢复 3 点体力{vspace=5}*每因流血损失 1 点生命值，恢复 3 点疲劳{vspace=5}*可主动使用，使自己陷入持续 6 回合的流血状态"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}harp Thorned Rose"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}尖{/size}{/color}{/font}刺玫瑰"
    old "Snake skin belt"
    new "蛇皮腰带"
    old "An elegant snake skin belt. Very sturdy but almost weightless.{vspace=6}*Reduces Нeat fatigue gain from scale armor to 0{vspace=5}*Reduces Нeat fatigue gain from scale gorget to 0{vspace=5}*Agility: +1{vspace=5}*Endurance: +1{vspace=5}*Coordination: +1{vspace=5}*Prestige: +7"
    new "一条精致的蛇皮腰带。极其结实，却几乎感觉不到重量。{vspace=6}*穿着鳞甲时，炎热产生的疲劳降至 0{vspace=5}*佩戴鳞片护颈时，炎热产生的疲劳降至 0{vspace=5}*敏捷：+1{vspace=5}*耐力：+1{vspace=5}*协调：+1{vspace=5}*威望：+7"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}nake skin belt"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}蛇{/size}{/color}{/font}皮腰带"
    old "Raider's hood"
    new "劫匪兜帽"
    old "A well-sewn hood from a sturdy cloth — can both conceal the face and{vspace=5}protect against bad weather. Common piece of attire of various outlaws{vspace=5}and assassins.{vspace=5}*Improves hit and dodge chance by 10{vspace=5}*Only works if the character wields a one-handed weapon with no shield"
    new "用结实布料缝制精细的兜帽——既能遮掩面容，也能{vspace=5}抵御恶劣天气。{vspace=5}各类亡命之徒和刺客的常见装束。{vspace=5}*命中与闪避几率提升 10{vspace=5}*仅在角色手持单手武器且不带盾牌时生效"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}R{/size}{/color}{/font}aider's hood"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}劫{/size}{/color}{/font}匪兜帽"
    old "Sling"
    new "投石索"
    old "A commoner's ranged weapon. Old as time but not exactly obsolete{vspace=5}quite yet.{vspace=5}*Injury chance: +1{vspace=5}*Injury stats debuff (enemy): +1{vspace=5}*Coordination: +2"
    new "平民的远程武器。古老如时光，却尚未{vspace=5}真正过时。{vspace=5}*伤势几率：+1{vspace=5}*敌方伤势属性减益：+1{vspace=5}*协调：+2"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}ling"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}投{/size}{/color}{/font}石索"
    old "Throwing dagger pendant"
    new "飞刀吊坠"
    old "A tiny pendant with a throwing dagger.{vspace=5}*Improves throwing daggers' hit chance by 10{vspace=5}*Improves throwing daggers' armor bypass chance by a quarter of your coordination"
    new "一枚缀着飞刀的小小吊坠。{vspace=5}*飞刀命中率提升 10{vspace=5}*飞刀无视护甲的几率提升，数值为你协调属性的四分之一"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}T{/size}{/color}{/font}hrowing dagger pendant"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}飞{/size}{/color}{/font}刀吊坠"
    old "Bronze ring"
    new "青铜戒指"
    old "An old bronze ring with a tint of rust. Typical peasant's jewelry.{vspace=5}*Strength: +1{vspace=5}*Agility: +1{vspace=5}*Prestige: +3"
    new "一枚泛着锈迹的旧青铜戒指。典型的农民首饰。{vspace=5}*力量：+1{vspace=5}*敏捷：+1{vspace=5}*威望：+3"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}ronze ring"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}青{/size}{/color}{/font}铜戒指"
    old "Bear paw"
    new "熊掌"
    old "A severed paw of a rabid bear of a colossal size.{vspace=5}*Overhead strikes' damage is additionally increased by a quarter of{vspace=5}your strength"
    new "一只庞然大物般的狂暴熊的断掌。{vspace=5}*自上而下的劈砍伤害额外提升，{vspace=5}幅度为你力量的四分之一"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}ear paw"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}熊{/size}{/color}{/font}掌"
    old "Snake Talisman"
    new "蛇形护符"
    old "A small talisman with an image of a snake — coiled and ready to strike.{vspace=5}*Improves short swords' hit chance by 10 + a third of your agility"
    new "一枚刻着蛇像的小护符——蛇身盘绕，蓄势待发。{vspace=5}*短剑命中率提升 10，外加你敏捷属性的三分之一"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}nake Talisman"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}蛇{/size}{/color}{/font}形护符"
    old "Falconry Glove"
    new "猎鹰手套"
    old "A padded gauntlet worn by falconers.{vspace=5}*Agility: +4{vspace=5}*Prestige: +2"
    new "驯鹰人佩戴的加垫手套。{vspace=5}*敏捷：+4{vspace=5}*威望：+2"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}F{/size}{/color}{/font}alconry Glove"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}猎{/size}{/color}{/font}鹰手套"
    old "Fair Maiden's Portrait"
    new "少女肖像"
    old "A tiny bronze locket with a hand-drawn portrait of a beautiful lady.{vspace=5}*Instantly removes all active poisonings and bleedings{vspace=5}*Instantly recovers one level of fatigue{vspace=5}*Provides an additional secret bonus effect{vspace=5}*Requires a perfect relationship with one girl{vspace=5}*Requires relationships with other girls to not exceed 25{vspace=5}*Requires 90 or more Virtue to use"
    new "一枚小巧的青铜挂坠，内有一幅手绘的美人肖像。{vspace=5}*立即解除所有中毒与流血状态{vspace=5}*立即恢复一级疲劳{vspace=5}*附带一项隐秘的额外加成{vspace=5}*需与某位姑娘保持完美关系{vspace=5}*与其他姑娘的关系不得超过 25{vspace=5}*需美德达到 90 以上方可使用"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}F{/size}{/color}{/font}air Maiden's Portrait"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}少{/size}{/color}{/font}女肖像"
    old "Extravagant Jacket"
    new "奢华外套"
    old "A lavish, embroidered jacket fit for noble Venetians, blending style{vspace=5}with elegance.{vspace=5}*Prestige: +15{vspace=5}*Coordination: +2"
    new "一件奢华绣花外套，专为威尼斯贵族打造，兼得风度{vspace=5}与优雅。{vspace=5}*威望：+15{vspace=5}*协调：+2"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}xtravagant Jacket"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}奢{/size}{/color}{/font}华外套"
    old "Exquisite Shirt"
    new "精致衬衫"
    old "Elegant red shirt, crafted with fine linen and intricate embroidery,{vspace=5}symbolizing status.{vspace=5}*Prestige: +15{vspace=5}*Lowers incoming bleed damage by 1"
    new "一件优雅的红衬衫，以细亚麻布与繁复刺绣制成，{vspace=5}象征着身份地位。{vspace=5}*威望：+15{vspace=5}*受到的流血伤害降低 1 点"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}xquisite Shirt"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}精{/size}{/color}{/font}致衬衫"
    old "Expensive Pants"
    new "华贵长裤"
    old "Luxurious velvet pants adorned with gold embroidery, symbolizing wealth.{vspace=5}*Prestige: +15{vspace=5}*Agility: +2"
    new "饰以金线刺绣的天鹅绒华贵长裤，象征着财富。{vspace=5}*威望：+15{vspace=5}*敏捷：+2"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}xpensive Pants"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}华{/size}{/color}{/font}贵长裤"
    old "Stone head brew"
    new "石脑酿剂"
    old "A unique brew created with an unknown recipe that makes whoever consumes it{vspace=1}fully resistant to losing consciousness.{vspace=5}*Grants immunity to stuns"
    new "一种以未知配方酿制的独特药剂，饮下之后{vspace=1}便不再轻易失去意识。{vspace=5}*免疫击倒"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}tone head brew"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}石{/size}{/color}{/font}脑酿剂"
    old "Fire blood brew"
    new "火血酿剂"
    old "A unique brew created with an unknown recipe that makes whoever consumes it{vspace=1}fully resistant to poisonings.{vspace=5}*Grants immunity to poisonings"
    new "一种以未知配方酿制的独特药剂，饮下之后{vspace=1}便完全不受中毒影响。{vspace=5}*免疫中毒"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}F{/size}{/color}{/font}ire blood brew"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}火{/size}{/color}{/font}血酿剂"
    old "Feline reflexes brew"
    new "猫之反射酿剂"
    old "A unique brew created with an unknown recipe that grants amazing reflexes{vspace=1}to whoever consumes it.{vspace=5}*Improves melee evasion chance by [reflex_boost_brew_evasion_bonus!i]"
    new "一种以未知配方酿制的独特药剂，赋予饮者{vspace=1}惊人的反射神经。{vspace=5}*近战闪避几率提升 [reflex_boost_brew_evasion_bonus!i]"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}F{/size}{/color}{/font}eline reflexes brew"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}猫{/size}{/color}{/font}之反射酿剂"
    old "Mask of the Faun"
    new "牧神面具"
    old "Intricate wooden mask of a faun to hide your true face.{vspace=1}*Consuming alcohol in battle recovers [faun_mask_alcohol_hp_recovery!i] HP{vspace=1}*Passively gain [faun_mask_fatigue_gain!i] fatigue each turn"
    new "一具做工精细的木制牧神面具，用以掩盖你的真容。{vspace=1}*战斗中饮酒可恢复 [faun_mask_alcohol_hp_recovery!i] 点生命值{vspace=1}*每回合被动获得 [faun_mask_fatigue_gain!i] 点疲劳"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}M{/size}{/color}{/font}ask of the Faun"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}牧{/size}{/color}{/font}神面具"
    old "Mask of the Lion"
    new "狮子面具"
    old "Intricate wooden mask of a lion to hide your true face.{vspace=1}*Нit chance and evasion increased by [lion_mask_hit_chance_bonus!i]{vspace=1}*Primary and secodary attacks' stamina consumption reduced [lion_mask_stam_cons_reduction!i]{vspace=1}*Works only for two-handed weapons"
    new "一具做工精细的木制狮子面具，用以掩盖你的真容。{vspace=1}*命中率与闪避提升 [lion_mask_hit_chance_bonus!i]{vspace=1}*主攻与副攻的体力消耗降低 [lion_mask_stam_cons_reduction!i]{vspace=1}*仅对双手武器生效"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}M{/size}{/color}{/font}ask of the Lion"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}狮{/size}{/color}{/font}子面具"
    old "Mask of the Trickster"
    new "骗徒面具"
    old "Intricate wooden mask of a trickster to hide your true face.{vspace=1}*Killing an enemy instanly refreshes all item cooldowns"
    new "一具做工精细的木制骗徒面具，用以掩盖你的真容。{vspace=1}*击杀敌人后立即重置所有物品的冷却时间"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}M{/size}{/color}{/font}ask of the Trickster"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}骗{/size}{/color}{/font}徒面具"
    old "Mask of the Daemon"
    new "恶魔面具"
    old "Intricate wooden mask of a horned daemon to hide your true face.{vspace=1}*Enemy bleedings will recover your health{vspace=1}*Effect is doubled if the enemy has high virtue{vspace=1}*Requires 0 or lower virtue for the effect to apply{vspace=1}*Slightly reduces evasion against high-virtue enemies"
    new "一具做工精细的木制长角恶魔面具，用以掩盖你的真容。{vspace=1}*敌人的流血将为你恢复生命{vspace=1}*若敌人美德较高，效果翻倍{vspace=1}*仅在你的美德为 0 或更低时生效{vspace=1}*面对高美德敌人时闪避略有降低"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}M{/size}{/color}{/font}ask of the Daemon"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}魔{/size}{/color}{/font}鬼面具"
    old "Leon from Lyon"
    new "里昂的莱昂"
    old "Ограбление по-авиньонски"
    new "阿维尼翁式劫案"
    old "{color=#A9A9A9}Отправиться в Авиньон и выкрасть шафран из резиденции местного аптекаря."
    new "{color=#A9A9A9}前往阿维尼翁，从当地药剂师的住所中偷出藏红花。"
    old "Servant"
    new "仆人"
    old "Auditor"
    new "审计员"
    old "[name!ti] and Duke of Cambridge"
    new "[name!ti]与剑桥公爵"
    old "Torture Master"
    new "拷问大师"
    old "Raglan"
    new "拉格兰"
    old "Dauphin"
    new "王太子"
    old "Charles of Navarre"
    new "纳瓦拉的卡洛斯"
    old "King Jean"
    new "让王"
    old "Cassandra"
    new "卡桑德拉"
    old "Emperor Karl"
    new "皇帝卡尔"
    old "Giuseppe Cavalli"
    new "朱塞佩·卡瓦利"
    old "Furio"
    new "弗里奥"
    old "Napolitano"
    new "纳波利塔诺"
    old "Rolando de Rossi"
    new "罗兰多·德·罗西"
    old "John Нawkwood"
    new "约翰·霍克伍德"
    old "King Louis"
    new "路易国王"
    old "Barnabo Visconti"
    new "巴尔纳博·维斯孔蒂"
    old "Duke Leopold"
    new "利奥波德公爵"
    old "Günther von Schwarzburg"
    new "贡特尔·冯·施瓦茨堡"
    old "Broken shortsword"
    new "断刃短剑"
    old "Sword with a broken blade."
    new "剑刃已断的剑。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}roken shortsword"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}断{/size}{/color}{/font}刃短剑"
    old "Scavenge"
    new "搜刮"
    old "."
    new "。"
    old "{size=-7}{color=#A9A9A9}Doubles the chance of miracles occuring{vspace=5}when performing religious actions{vspace=5}(praying, mortifying flesh).{vspace=5}Performing unvirtuous actions might{vspace=5}result in a punishment."
    new "{size=-7}{color=#A9A9A9}进行宗教行为时{vspace=5}（祈祷、苦修肉身），{vspace=5}奇迹发生的概率翻倍。{vspace=5}而行不义之事，{vspace=5}则可能招致惩罚。"
    old "{size=-7}{color=#A9A9A9}Once per chapter will grant you [bon_vivant_civil_talent_vitality_bonus]{vspace=5}additional vitality points if you used 3 or{vspace=5}more different camp rest options including{vspace=5}gambling, playing lute, drinking alcohol or{vspace=5}visting a brothel."
    new "{size=-7}{color=#A9A9A9}每章一次：若你在营地休息时用过三种或{vspace=5}更多不同的休息方式，包括赌博、{vspace=5}弹鲁特琴、饮酒或{vspace=5}逛妓院，将额外获得 [bon_vivant_civil_talent_vitality_bonus]{vspace=5}点活力。"
    old "{size=-7}{color=#A9A9A9}Unlocks do-it-yourself item crafts."
    new "{size=-7}{color=#A9A9A9}解锁自制物品的工艺制作。"
    old "{size=-7}{color=#A9A9A9}Once per chapter allows you to personally{vspace=5}train the members of your squad, granting{vspace=5}them 1 additional upgrade point."
    new "{size=-7}{color=#A9A9A9}每章一次，可亲自{vspace=5}训练你的小队成员，{vspace=5}使其额外获得 1 点升级点数。"
    old "{size=-7}{color=#A9A9A9}Increases the number of poisonous{vspace=5}ingredients provided by Empty Vial during{vspace=5}scavenging. An additional poison bottle{vspace=5}received during crafting would always be{vspace=5}full instead of half-empty."
    new "{size=-7}{color=#A9A9A9}搜刮时，空药瓶能带来的有毒{vspace=5}材料数量将会增加。{vspace=5}制作时额外获得的毒药瓶{vspace=5}将总是满的，{vspace=5}而非半瓶。"
    old "{size=-7}{color=#A9A9A9}Considerably boosts your luck."
    new "{size=-7}{color=#A9A9A9}大幅提升你的运气。"
    old "{size=-7}{color=#A9A9A9}Allows you to visit a brothel for free{vspace=5}three times each chapter.{vspace=5}Every fourth visit to the brothel{vspace=5}within one chapter would increase your{vspace=5}endurance by 1."
    new "{size=-7}{color=#A9A9A9}每章可免费逛妓院{vspace=5}三次。每章内第四次{vspace=5}光顾妓院，{vspace=5}将使你的耐力{vspace=5}增加 1 点。"
    old "{size=-7}{color=#A9A9A9}Lowers fatigue build-up from leveling{vspace=5}craftsmanship.{vspace=5}Unlocks a unique crafting recipe.{vspace=5}Chance to receive an additional item{vspace=5}during crafting is increased by 5%."
    new "{size=-7}{color=#A9A9A9}降低因提升{vspace=5}工艺等级而产生的疲劳积累。{vspace=5}解锁一条独特的制作配方。{vspace=5}制作时额外获得一件物品{vspace=5}的几率提高 5%。"
    old "{size=-7}{color=#A9A9A9}Provides 2 more leather pieces and{vspace=5}some additional money from scavenging.{vspace=5}Lowers fatigue build-up from leveling{vspace=5}up crossbow skill.{vspace=5}Crossbow's armor bypass chance is{vspace=5}increased by 15.{vspace=5}Damage dealt to animals increased{vspace=5}by 10."
    new "{size=-7}{color=#A9A9A9}搜刮时额外获得 2 块皮革，{vspace=5}以及一些额外的钱。{vspace=5}提升弩技能等级时，{vspace=5}疲劳积累降低。{vspace=5}弩的护甲穿透几率{vspace=5}提升 15。{vspace=5}对动物造成的伤害{vspace=5}提升 10。"
    old "{size=-7}{color=#A9A9A9}Provides 2 more alchemical ingredients{vspace=5}from scavenging.{vspace=5}Boosts the effectiveness of various{vspace=5}alchemical supplies (antidotes, medicines,{vspace=5}aseptic bandages and some others)."
    new "{size=-7}{color=#A9A9A9}搜刮时额外获得 2 种炼金材料。{vspace=5}提升各类炼金用品{vspace=5}（解毒剂、药品、{vspace=5}消毒绷带等）{vspace=5}的效果。"
    old "{size=-7}{color=#A9A9A9}Provides an additional loot item{vspace=5}after each battle."
    new "{size=-7}{color=#A9A9A9}每场战斗后{vspace=5}额外获得一件战利品。"
    old "{size=-7}{color=#A9A9A9}Unlocks all crafting recipes."
    new "{size=-7}{color=#A9A9A9}解锁所有制作配方。"
    old "{size=-7}{color=#A9A9A9}Lowers squad members' upgrade cost{vspace=5}by 20% if your reputation with soldiers{vspace=5}is 90 or more."
    new "{size=-7}{color=#A9A9A9}若你在士兵中的声望达到 90 或以上，{vspace=5}小队成员的升级费用{vspace=5}降低 20%。"
    old "{size=-7}{color=#A9A9A9}Boosts your win chance when gambling in{vspace=5}camp based on how low your virtue is. The{vspace=5}maximum bet sum (won or lost) is also{vspace=5}increased in the same manner.{vspace=5}Using lucky dice while gambling gives{vspace=5}various bonuses depending on your win{vspace=5}streak."
    new "{size=-7}{color=#A9A9A9}在营地赌博时，你的美德越低，{vspace=5}获胜的几率越高。{vspace=5}最大下注金额（无论输赢）{vspace=5}也会同样提高。{vspace=5}赌博时使用幸运骰子，{vspace=5}可根据你的连胜场数{vspace=5}获得各种加成。"
    old "{size=-7}{color=#A9A9A9}Increases the amount of fatigue recovered{vspace=5}by playing lute. Using lute in combat{vspace=5}would additionally lower your fatigue by{vspace=5}the number equal to your Coordination."
    new "{size=-7}{color=#A9A9A9}弹奏鲁特琴恢复的疲劳量提升。{vspace=5}战斗中弹奏鲁特琴{vspace=5}还会额外降低疲劳，{vspace=5}数值等于你的协调属性。"
    old "{size=-7}{color=#A9A9A9}Every 3rd time you train Vitality you{vspace=5}would also receive an additional point in{vspace=5}Strength.{vspace=5}Increases your Vitality and Strength by 1.{vspace=5}Grants 2 points of injury resistance.{vspace=5}Every 3rd time you train Agility you{vspace=5}would lose one point of Strength."
    new "{size=-7}{color=#A9A9A9}每训练 3 次体质，{vspace=5}你将额外获得 1 点{vspace=5}力量。{vspace=5}体质与力量各 +1。{vspace=5}获得 2 点伤势抗性。{vspace=5}每训练 3 次敏捷，{vspace=5}你将失去 1 点力量。"
    old "{size=-7}{color=#A9A9A9}Every 3rd time you train Coordination{vspace=5}you would also receive an additional{vspace=5}point in Agility.{vspace=5}Increases your Coordination and Agility{vspace=5}by 1.{vspace=5}Every 3rd time you train Strength you{vspace=5}would lose one point of Agility.{vspace=5}Grants one guaranteed dodge in combat."
    new "{size=-7}{color=#A9A9A9}每训练 3 次协调，{vspace=5}你将额外获得 1 点{vspace=5}敏捷。{vspace=5}协调与敏捷各 +1。{vspace=5}每训练 3 次力量，{vspace=5}你将失去 1 点敏捷。{vspace=5}战斗中保证可{vspace=5}闪避一次。"
    old "{size=-7}{color=#A9A9A9}Scavenging does not consume time and{vspace=5}recovers 50% of max fatigue."
    new "{size=-7}{color=#A9A9A9}搜刮不消耗时间，{vspace=5}并恢复最大疲劳的 50%。"
    old "{size=-7}{color=#A9A9A9}Boosts gold rewards for killing enemies.{vspace=5}The lower your Virtue is — the higher{vspace=5}the reward."
    new "{size=-7}{color=#A9A9A9}击杀敌人获得的金币奖励提升。{vspace=5}你的美德越低，{vspace=5}奖励越高。"
    old "{size=-7}{color=#A9A9A9}Personal participation in heists and{vspace=5}robberies would yield an additional sum{vspace=5}of money. Нeists and robberies are easier{vspace=5}to pull off.{vspace=5}Damage and hit chance of throwing daggers{vspace=5}are additionally increased by a quarter{vspace=5}of your Agility."
    new "{size=-7}{color=#A9A9A9}亲自参与劫案与抢劫，{vspace=5}将获得额外的金钱。{vspace=5}劫案与抢劫也更容易得手。{vspace=5}飞刀的伤害与命中率，{vspace=5}还会额外提升，{vspace=5}幅度为你敏捷的{vspace=5}四分之一。"
    old "{size=-7}{color=#A9A9A9}Increases the quality of manually crafted{vspace=5}armor.{vspace=5}Removes craftsmanship skill requirement{vspace=5}for armor crafting.{vspace=5}Lowers fatigue build-up from working at{vspace=5}forge."
    new "{size=-7}{color=#A9A9A9}提升手工打造{vspace=5}护甲的品质。{vspace=5}移除护甲制作所需的{vspace=5}工艺技能要求。{vspace=5}在铁匠铺工作时，{vspace=5}疲劳积累降低。"
    old "{size=-7}{color=#A9A9A9}Allows to sell items for their base cost{vspace=5}without a penalty.{vspace=5}Incompatible with Lucky coin."
    new "{size=-7}{color=#A9A9A9}可以按基础价格出售物品，{vspace=5}不受折损。{vspace=5}与幸运硬币不兼容。"
    old "{size=-7}{color=#A9A9A9}Increases inventory space by 5."
    new "{size=-7}{color=#A9A9A9}背包容量增加 5 格。"
    old "{size=-7}{color=#A9A9A9}Allows you to sell items for an{vspace=5}increased price (+[new_haggler_civil_talent_discount_percent!i]%)."
    new "{size=-7}{color=#A9A9A9}允许你以更高的价格{vspace=5}出售物品（+[new_haggler_civil_talent_discount_percent!i]%）。"
    old "Poisonous plant"
    new "毒草"
    old "Rare poisonous plant. Useful in making combat poisons."
    new "稀有的有毒植物。可用于制作战斗用毒药。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}P{/size}{/color}{/font}oisonous plant"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}毒{/size}{/color}{/font}草"
    old "Bonus item (Reputation)"
    new "附加物品（声望）"
    old "Devil Incarnate"
    new "恶魔化身"
    old "Renegade"
    new "叛徒"
    old "Criminal"
    new "罪犯"
    old "Chivalrous"
    new "侠义"
    old "Pious"
    new "虔诚"
    old "Paragon"
    new "楷模"
    old "*Bludgeoning attacks ignore an amount of enemy armor equal to the third of{vspace=1}your strength"
    new "*钝击攻击无视的敌方护甲量，相当于你力量{vspace=1}的三分之一"
    old "Rogue Man-at-arms"
    new "恶棍甲士"
    old "Well-armed Bandit"
    new "精良武装强盗"
    old "Gang Member"
    new "帮派成员"
    old "Aragon Bandit"
    new "阿拉贡强盗"
    old "Raoul's bodyguard"
    new "拉乌尔的护卫"
    old "Trinkets"
    new "小饰品"
    old "Squad Member"
    new "小队成员"
    old "123"
    new "123"
    old "Decorated Bastard sword"
    new "华丽的混种剑"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}D{/size}{/color}{/font}ecorated Bastard sword"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}混{/size}{/color}{/font}种剑"
    old "Lonbow"
    new "长弓"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}L{/size}{/color}{/font}ongbow"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}长{/size}{/color}{/font}弓"
    old "Rent"
    new "租金"
    old "{color=#A9A9A9}Разжиться деньгами для оплаты аренды жилья.{vspace=5}Требуемая сумма: [player_house_rent_payment!ti]."
    new "{color=#A9A9A9}弄到钱来支付房租。{vspace=5}所需金额：[player_house_rent_payment!ti]。"
    old "{i}{size=-7}(Мэйдстоуна)"
    new "{i}{size=-7}（梅德斯通）"
    old "Debt"
    new "债务"
    old "{color=#A9A9A9}Расплатиться с кредиторами. Текущая сумма долга: [player_debt!ti]."
    new "{color=#A9A9A9}与债主结清欠款。当前债务金额：[player_debt!ti]。"
    old "Grateful Son"
    new "感恩之子"
    old "{color=#A9A9A9}Возместить семье расходы, потраченные на пир в честь вашего возвращения."
    new "{color=#A9A9A9}偿还家中为庆祝你归来举办宴会所花费的开销。"
    old "{i}{size=-7}(Мэйдстоун)"
    new "{i}{size=-7}（梅德斯通）"
    old "The Boy Who Cried Wolves"
    new "喊狼来了的男孩"
    old "{color=#A9A9A9}Разобраться с волками, терроризирующими скот местного фермера."
    new "{color=#A9A9A9}解决那些骚扰当地农夫牲畜的狼群。"
    old "Personal Trainer"
    new "私人教头"
    old "{color=#A9A9A9}Прибыть ко двору торговца, ищущего тренера по фехтованию для своего сына,{vspace=5}и постараться получить работу."
    new "{color=#A9A9A9}前往那位想为儿子聘请剑术教练的商人宅邸，{vspace=5}争取这份差事。"
    old "Roadhouse"
    new "路边酒馆"
    old "{color=#A9A9A9}Хозяин одной из мэйдстоунских таверн предложил вам работу в качестве вышибалы."
    new "{color=#A9A9A9}梅德斯通一家酒馆的老板请你去做看场子的打手。"
    old "Нunting Monsters"
    new "猎杀怪物"
    old "{color=#A9A9A9}Разыскать и убить лесное чудовище."
    new "{color=#A9A9A9}找到并杀死森林中的怪物。"
    old "Recon"
    new "侦察"
    old "{color=#A9A9A9}Разведать обстановку в окрестностях Виндзора."
    new "{color=#A9A9A9}侦察温莎周边的局势。"
    old "{i}{size=-7}(Роже)"
    new "{i}{size=-7}（罗杰）"
    old "Amateur Assassin"
    new "业余刺客"
    old "{color=#A9A9A9}Разыскать и убить преступника, скрывающегося в лагере."
    new "{color=#A9A9A9}找出藏匿在营中的罪犯并将其杀死。"
    old "{i}{size=-7}(???)"
    new "{i}{size=-7}（？？？）"
    old "A Guest From Scotland"
    new "来自苏格兰的客人"
    old "{color=#A9A9A9}Обеспечить сохранность груза следующего в Оксфорд."
    new "{color=#A9A9A9}确保运往牛津的货物安然无恙。"
    old "{i}{size=-7}(Торговец из Оксфорда)"
    new "{i}{size=-7}（牛津来的商人）"
    old "Drillmaster"
    new "操练教头"
    old "{color=#A9A9A9}Помочь Джонсу в тренировке новобранцев.{vspace=15}{color=#A9A9A9}Тренировки будут влиять на показатели ваших союзников в бою.{vspace=5}Качество подготовки: [drillmaster.completed!ti]/100"
    new "{color=#A9A9A9}帮助琼斯训练新兵。{vspace=15}{color=#A9A9A9}训练将影响你的盟友在战斗中的表现。{vspace=5}训练质量：[drillmaster.completed!ti]/100"
    old "Arming the Rebellion"
    new "武装起事"
    old "{color=#A9A9A9}Помочь Джонсу снабдить членов отряда оружием и снаряжением.{vspace=15}{color=#A9A9A9}Объемы помощи будут влиять на снаряжение ваших союзников в бою.{vspace=5}Гибель союзников будет приводить к потере части вложенных ресурсов.{vspace=5}Текущая стоимость снаряжения союзников: [drillmaster.timed_out!ti]"
    new "{color=#A9A9A9}帮助琼斯为队员配备武器与装备。{vspace=15}{color=#A9A9A9}援助的规模将影响你的盟友在战斗中的装备。{vspace=5}盟友阵亡将导致部分投入的资源损失。{vspace=5}当前盟友装备花费：[drillmaster.timed_out!ti]"
    old "{color=#A9A9A9}Передать Джонсу 400 флоринов для оплаты услуг лекаря."
    new "{color=#A9A9A9}交给琼斯 400 弗罗林，以支付医者的酬劳。"
    old "Recruitment"
    new "招募"
    old "{color=#A9A9A9}Помочь Родольфо с рекрутированием новых членов отряда, передав ему{vspace=5}сильнодействующее лекарство, а также шлем и горжет."
    new "{color=#A9A9A9}帮助罗道夫招募新队员，交给他{vspace=5}强效药物，以及头盔和护喉甲。"
    old "{i}{size=-7}(Родольфо)"
    new "{i}{size=-7}（罗道夫）"
    old "Fall of the Нouse of Caldwell"
    new "考德威尔家族的陨落"
    old "{color=#A9A9A9}Подготовиться к нападению на имение графа Колдвелла."
    new "{color=#A9A9A9}准备袭击考德威尔伯爵的庄园。"
    old "{i}{size=-7}(Дункан)"
    new "{i}{size=-7}（邓肯）"
    old "For A Good Cause"
    new "为了正义之事"
    old "{color=#A9A9A9}Объехать бывшие владения графа Колдвелла и собрать небольшой налог с их{vspace=5}обитателей."
    new "{color=#A9A9A9}走遍考德威尔伯爵的旧领地，向当地的{vspace=5}居民征收一笔小额税赋。"
    old "Secret Ingredient"
    new "秘密配料"
    old "{color=#A9A9A9}Отправиться в резиденцию Шерифа Гринвича и передать ему деньги от{vspace=5}Дункана."
    new "{color=#A9A9A9}前往格林威治郡长的府邸，把邓肯{vspace=5}的钱交给他。"
    old "Paths Diverge"
    new "分道扬镳"
    old "{color=#A9A9A9}Встретиться с Родольфо вдали от посторонних ушей и обсудить его планы."
    new "{color=#A9A9A9}在无人偷听之处与罗道夫会面，商议他的计划。"
    old "Surviving Windsor"
    new "活着离开温莎"
    old "{color=#A9A9A9}Подготовиться к отправке под Виндзор для участия в осаде города."
    new "{color=#A9A9A9}准备开赴温莎，参与围城之战。"
    old "Secondary Weapon"
    new "副武器"
    old "{color=#A9A9A9}Раздобыть хороший кинжал для Голиафа."
    new "{color=#A9A9A9}为歌利亚弄一把趁手的匕首。"
    old "{i}{size=-7}(Голиаф)"
    new "{i}{size=-7}（歌利亚）"
    old "Count's order"
    new "伯爵之命"
    old "{color=#A9A9A9}Выполнить поручения Роже."
    new "{color=#A9A9A9}完成罗杰交办的差事。"
    old "{i}{size=-7}(Кентербери)"
    new "{i}{size=-7}（坎特伯雷）"
    old "Greenwich Raid"
    new "格林威治突袭"
    old "{color=#A9A9A9}Разбить отряд людей Нортхэмптона в окрестностях Гринвича."
    new "{color=#A9A9A9}在格林威治一带击溃北安普顿的人马。"
    old "Old Friends"
    new "故交"
    old "{color=#A9A9A9}Подготовиться к поездке в Кембридж."
    new "{color=#A9A9A9}准备前往剑桥的行程。"
    old "The Missing Link"
    new "缺失的一环"
    old "{color=#A9A9A9}Оправиться на север и убедиться, что шотландцы не пересекли границу."
    new "{color=#A9A9A9}北上查探，确认苏格兰人没有越过边境。"
    old "The Price of Failure"
    new "失败的代价"
    old "{color=#A9A9A9}Арестовать герцога Кембриджского."
    new "{color=#A9A9A9}逮捕剑桥公爵。"
    old "Кузнец: Закрытый шлем"
    new "铁匠：封闭式头盔"
    old "{color=#A9A9A9}Смастерить на заказ шлем с заданными параметрами.{vspace=5}Защита головы: не ниже 16; Покрытие головы: не ниже 100"
    new "{color=#A9A9A9}按指定参数定制一顶头盔。{vspace=5}头部防护：不低于 16；头部覆盖：不低于 100"
    old "Кузнец: Облегченный шлем"
    new "铁匠：轻量头盔"
    old "{color=#A9A9A9}Смастерить на заказ шлем с заданными параметрами.{vspace=5}Покрытие головы: не ниже 80; Сумма штрафов: не больше 1"
    new "{color=#A9A9A9}按指定参数定制一顶头盔。{vspace=5}头部覆盖：不低于 80；惩罚总和：不超过 1"
    old "Кузнец: Украшенный шлем"
    new "铁匠：装饰头盔"
    old "{color=#A9A9A9}Смастерить на заказ шлем с заданными параметрами.{vspace=5}Престиж: не ниже 20"
    new "{color=#A9A9A9}按指定参数定制一顶头盔。{vspace=5}威望：不低于 20"
    old "Кузнец: Боевой доспех"
    new "铁匠：战斗护甲"
    old "{color=#A9A9A9}Смастерить на заказ доспех с заданными параметрами.{vspace=5}Защита корпуса: не ниже 15; Покрытие корпуса: не ниже 100{vspace=5}Защита конечн.: не ниже 9; Покр. конечн.: не ниже 55{vspace=5}Сумма штрафов: не больше 6"
    new "{color=#A9A9A9}按指定参数定制一套护甲。{vspace=5}躯干防护：不低于 15；躯干覆盖：不低于 100{vspace=5}四肢防护：不低于 9；四肢覆盖：不低于 55{vspace=5}惩罚总和：不超过 6"
    old "Кузнец: Уязвимый доспех"
    new "铁匠：脆弱护甲"
    old "{color=#A9A9A9}Смастерить на заказ доспех с заданными параметрами.{vspace=5}Защита корпуса: не ниже 12; Покрытие корпуса: не ниже 91, не выше 100"
    new "{color=#A9A9A9}按指定参数定制一套护甲。{vspace=5}躯干防护：不低于 12；躯干覆盖：不低于 91、不高于 100"
    old "Кузнец: Декоративный доспех"
    new "铁匠：装饰护甲"
    old "{color=#A9A9A9}Смастерить на заказ доспех с заданными параметрами.{vspace=5}Престиж: не ниже 31"
    new "{color=#A9A9A9}按指定参数定制一套护甲。{vspace=5}威望：不低于 31"
    old "Кузнец: Облегченный доспех"
    new "铁匠：轻量护甲"
    old "{color=#A9A9A9}Смастерить на заказ доспех с заданными параметрами.{vspace=5}Сумма штрафов: не больше 2; Престиж: не ниже 20"
    new "{color=#A9A9A9}按指定参数定制一套护甲。{vspace=5}惩罚总和：不超过 2；威望：不低于 20"
    old "Кузнец: Утяжеленный доспех"
    new "铁匠：加重护甲"
    old "{color=#A9A9A9}Смастерить на заказ доспех с заданными параметрами.{vspace=5}Сумма штрафов: от 7 и выше"
    new "{color=#A9A9A9}按指定参数定制一套护甲。{vspace=5}惩罚总和：7 或以上"
    old "Ремесленник: Башмаки, ножны и фляга"
    new "工匠：靴子、刀鞘与水壶"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Башмаки, ножны, фляга."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}靴子、刀鞘、水壶。"
    old "Ремесленник: Ножны"
    new "工匠：刀鞘"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Ножны."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}刀鞘。"
    old "Ремесленник: Поясная сумка"
    new "工匠：腰带挎包"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Поясная сумка."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}腰带挎包。"
    old "Ремесленник: Мешки"
    new "工匠：麻袋"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Мешок (3)."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}麻袋（3 个）。"
    old "Ремесленник: Башмаки"
    new "工匠：靴子"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Башмаки."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}靴子。"
    old "Ремесленник: Бурдюки"
    new "工匠：皮囊"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Бурдюк (2)."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}皮囊（2 个）。"
    old "Ремесленник: Мешок"
    new "工匠：麻袋"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Мешок."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}麻袋。"
    old "Ремесленник: Турникеты и бинты"
    new "工匠：止血带与绷带"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих вещей:{vspace=5}Турникет (5), бинт (5)."
    new "{color=#A9A9A9}完成以下物品的制作订单：{vspace=5}止血带（5 个）、绷带（5 个）。"
    old "Алхимик: Сильный самодельный яд"
    new "炼金师：强效自制毒药"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Сильный самодельный яд."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}强效自制毒药。"
    old "Алхимик: Стерильные бинты"
    new "炼金师：无菌绷带"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Стерильный бинт (2)."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}无菌绷带（2 个）。"
    old "Алхимик: Сильнодействующее лекарство"
    new "炼金师：强效药剂"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Сильнодействующее лекарство."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}强效药剂。"
    old "Алхимик: Антидот II"
    new "炼金师：解毒剂 II"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Антидот II."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}解毒剂 II。"
    old "Алхимик: Ненадежный яд"
    new "炼金师：劣质毒药"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Ненадежный яд."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}劣质毒药。"
    old "Алхимик: Жидкая смерть"
    new "炼金师：液态死亡"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Жидкая смерть."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}液态死亡。"
    old "Алхимик: Коагулянты"
    new "炼金师：凝血剂"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Коагулянт (2)."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}凝血剂（2 个）。"
    old "Алхимик: Антидот III"
    new "炼金师：解毒剂 III"
    old "{color=#A9A9A9}Выполнить заказ на изготовление следующих алхимических составов:{vspace=5}Антидот III."
    new "{color=#A9A9A9}完成以下炼金药剂的制作订单：{vspace=5}解毒剂 III。"
    old "Money Нas No Smell"
    new "金钱无臭味"
    old "{color=#A9A9A9}Подготовиться к отправке на дальнюю заставу."
    new "{color=#A9A9A9}准备开赴边远的哨站。"
    old "Overthrow"
    new "推翻"
    old "{color=#A9A9A9}Подготовить план штурма Чиппенхэма."
    new "{color=#A9A9A9}制定攻打奇彭纳姆的计划。"
    old "{i}{size=-7}(Алиса)"
    new "{i}{size=-7}（艾丽莎）"
    old "Duncan's Revenge"
    new "邓肯的复仇"
    old "{color=#A9A9A9}Выделить тридцать ополченцев для охраны поместья Алисы."
    new "{color=#A9A9A9}调拨三十名民兵守卫艾丽莎的庄园。"
    old "Unfinished Business"
    new "未竟之事"
    old "{color=#A9A9A9}Захватить Чиппенхэм и арестовать Дункана."
    new "{color=#A9A9A9}攻占奇彭纳姆，逮捕邓肯。"
    old "{color=#A9A9A9}Захватить Чиппенхэм и убить Дункана."
    new "{color=#A9A9A9}攻占奇彭纳姆，杀死邓肯。"
    old "March on London"
    new "进军伦敦"
    old "{color=#A9A9A9}Собрать максимально большую армию, для захвата Лондона."
    new "{color=#A9A9A9}集结尽可能庞大的军队，以攻取伦敦。"
    old "Greenwitch Militia"
    new "格林威治民兵"
    old "{color=#A9A9A9}Помочь Алисе в сборе гринвичского ополчения и передать ей трех членов отряда,{vspace=1}имеющих уровень выше пятого и переживших три и более сражений."
    new "{color=#A9A9A9}帮助艾丽莎召集格林威治民兵，并移交三名队员给她，{vspace=1}要求等级高于五级且经历过三场以上战斗。"
    old "New Protector of De Lambert Estate"
    new "德·朗贝尔庄园的新守护者"
    old "{color=#A9A9A9}Преподать людям Евы несколько уроков военного дела.{vspace=1}{color=#A9A9A9}Тренировки будут влиять на показатели союзников в бою.{vspace=1}Качество подготовки: [new_protector_of_de_lambert_estate.completed!ti]/50{vspace=10}Уничтожить отряд мародеров, разграбляющих земли Евы, не допустив{vspace=1}гибели ни одного из её людей."
    new "{color=#A9A9A9}给伊娃的部下上几堂军事课。{vspace=1}{color=#A9A9A9}训练将影响盟友在战斗中的表现。{vspace=1}训练质量：[new_protector_of_de_lambert_estate.completed!ti]/50{vspace=10}消灭洗劫伊娃领地的掠夺者部队，{vspace=1}不得让她的人有一人阵亡。"
    old "{i}{size=-7}(Ева)"
    new "{i}{size=-7}（伊娃）"
    old "Road to Rouen"
    new "通往鲁昂之路"
    old "{color=#A9A9A9}Обсудить с Де Рошем дальнейший план действий."
    new "{color=#A9A9A9}与德·罗什商议下一步的行动计划。"
    old "{i}{size=-7}(Де Рош)"
    new "{i}{size=-7}（德·罗什）"
    old "Working Hands"
    new "干活的帮手"
    old "{color=#A9A9A9}Передать уазельскому лекарю двух членов отряда со следующими{vspace=1}характеристиками:{vspace=3}Класс: пейзанин{vspace=1}Сила: не меньше 7{vspace=10}Людей передано: [working_hands.completed!ti]/2"
    new "{color=#A9A9A9}将两名符合以下条件的小队成员交给瓦泽勒的医者：{vspace=1}要求如下：{vspace=3}职业：农民{vspace=1}力量：不低于 7{vspace=10}已移交人数：[working_hands.completed!ti]/2"
    old "{i}{size=-7}(Уазельский лекарь)"
    new "{i}{size=-7}（瓦泽勒的医者）"
    old "Missing Tools"
    new "缺失的工具"
    old "{color=#A9A9A9}Раздобыть для уазельского кузнеца следующие предметы:{vspace=3}*Кузнечный молот{vspace=1}*Рабочие перчатки"
    new "{color=#A9A9A9}为瓦泽勒的铁匠弄来以下物品：{vspace=3}*锻造锤{vspace=1}*工作手套"
    old "{i}{size=-7}(Уазельский кузнец)"
    new "{i}{size=-7}（瓦泽勒的铁匠）"
    old "Health Issues"
    new "健康问题"
    old "{color=#A9A9A9}Помочь бальи устранить эпидемию дизентерии, разразившуюся{vspace=1}в его отряде, и восстановить боеспособность его людей."
    new "{color=#A9A9A9}帮助总管平息他部队中爆发的痢疾疫情，{vspace=1}恢复部下的战斗力。"
    old "Second Youth"
    new "重返青春"
    old "{color=#A9A9A9}Помочь Паскалю из Уазеля залечить старые раны.{vspace=1}Раздобыть для него следующие предметы:{vspace=3}*Лекарство{vspace=1}*Сильнодействующее лекарство{vspace=1}*Алкоголь"
    new "{color=#A9A9A9}帮助瓦泽勒的帕斯卡尔治愈旧伤。{vspace=1}为他弄来以下物品：{vspace=3}*药品{vspace=1}*强效药品{vspace=1}*酒"
    old "{i}{size=-7}(Паскаль из Уазеля)"
    new "{i}{size=-7}（瓦泽勒的帕斯卡尔）"
    old "Нunter turned Soldier"
    new "猎手从军"
    old "{color=#A9A9A9}Передать Адаму из Уазеля большой щит, за которым он мог бы укрываться во время{vspace=1}перезарядки арбалета."
    new "{color=#A9A9A9}交给瓦泽勒的亚当一面大盾，好让他在{vspace=1}装填弩机时得以藏身。"
    old "{i}{size=-7}(Адам из Уазеля)"
    new "{i}{size=-7}（瓦泽勒的亚当）"
    old "Exchanging Favors"
    new "礼尚往来"
    old "{color=#A9A9A9}Бальи просит вас провести несколько тренировок для его людей и обещает за это{vspace=1}хорошую награду."
    new "{color=#A9A9A9}总管请你为他的部下进行几次训练，并为此承诺{vspace=1}一笔丰厚的报酬。"
    old "{i}{size=-7}(Бальи Нормандии)"
    new "{i}{size=-7}（诺曼底总管）"
    old "City of Thieves"
    new "盗贼之城"
    old "{color=#A9A9A9}Предотвратить разграбление продовольственных складов в Руане."
    new "{color=#A9A9A9}阻止鲁昂的粮仓遭到洗劫。"
    old "Нigh Society"
    new "上流社会"
    old "{color=#A9A9A9}Одеться подобающим образом для участия в королевском пиру{vspace=1}(престиж: не менее 80)."
    new "{color=#A9A9A9}穿着得体，以出席国王的宴会{vspace=1}（威望：不低于 80）。"
    old "Fathers and Sons"
    new "父与子"
    old "{color=#A9A9A9}Проникнуть в тюрьму Консьержери и лично поговорить с дофином."
    new "{color=#A9A9A9}潜入孔西耶尔日监狱，亲自与王太子交谈。"
    old "Thief's Нonour"
    new "盗亦有道"
    old "{color=#A9A9A9}Выполнить просьбу узника и сообщить трактирщику о том, где его содержат."
    new "{color=#A9A9A9}满足囚徒的请求，告诉客栈老板他被关押何处。"
    old "{i}{size=-7}(Бертран Буржиньон)"
    new "{i}{size=-7}（贝特朗·布尔吉尼翁）"
    old "Gangs of Paris"
    new "巴黎帮派"
    old "{color=#A9A9A9}Совершить убийство Рауля из Арагона, укрывающегося в лаборатории за городом."
    new "{color=#A9A9A9}刺杀藏身于城外实验室的阿拉贡的拉乌尔。"
    old "{i}{size=-7}(Парижские бандиты)"
    new "{i}{size=-7}（巴黎匪帮）"
    old "Young Anselm's Sword"
    new "小安瑟姆的剑"
    old "{color=#A9A9A9}Помочь юному Ансельму вернуть меч, проигранный им в кости одному из наёмников.{vspace=1}Или же раздобыть для него другой украшенный драгоценностями полуторный клинок."
    new "{color=#A9A9A9}帮助小安瑟姆取回他掷骰子输给一名雇佣兵的剑。{vspace=1}或者为他另寻一柄镶宝石的手半剑。"
    old "{i}{size=-7}(Ансельм)"
    new "{i}{size=-7}（安瑟姆）"
    old "The Longest Night"
    new "最漫长的一夜"
    old "{color=#A9A9A9}Проникнуть в Париж, изучить ситуацию в городе и лично встретиться с Рагланом{vspace=1}или Карлом Наваррским."
    new "{color=#A9A9A9}潜入巴黎，摸清城中的局势，并亲自面见拉格兰{vspace=1}或纳瓦拉的卡洛斯。"
    old "Uneasy Alliance"
    new "不安的同盟"
    old "{color=#A9A9A9}Договориться с рутьерами в Булонском лесу о совместных действиях против{vspace=1}восставших."
    new "{color=#A9A9A9}与布洛涅森林的佣兵商定联手对抗{vspace=1}叛军。"
    old "City Guards"
    new "城卫"
    old "{color=#A9A9A9}Захватить казармы городской стражи и освободить пленников."
    new "{color=#A9A9A9}攻占城卫兵的营房，释放被囚者。"
    old "Fractured Alliance"
    new "分崩离析的同盟"
    old "{color=#A9A9A9}Разбить отряды союзников короля Педро до того, как они успеют соединиться."
    new "{color=#A9A9A9}赶在佩德罗国王的盟军汇合之前，将其各个击破。"
    old "À La Guerre Comme À La Guerre"
    new "战时自当从权"
    old "{color=#A9A9A9}Отравить колодцы на пути следования английских подкреплений из Аквитании."
    new "{color=#A9A9A9}在英格兰援军自阿基坦而来的必经之路上，毒化沿途的水井。"
    old "Ratcatcher"
    new "捕鼠人"
    old "{color=#A9A9A9}Передать Де Рошу одного члена отряда, вооруженного коротким мечом или{vspace=1}топором, арбалетом, метательным кинжалом, а также одетого в легкие{vspace=1}доспехи и имеющего характеристики не ниже следующих:{vspace=3}Уровень: 5{vspace=1}Сражений пережито: 3{vspace=1}Сумма ловкости и координации: 20"
    new "{color=#A9A9A9}将一名队员移交给德·罗什，要求其装备短剑或{vspace=1}斧、弩、投掷匕首，身穿轻甲，{vspace=1}且属性不低于以下标准：{vspace=3}等级：5{vspace=1}经历的战斗：3{vspace=1}敏捷与协调之和：20"
    old "The Last Нonest Man in France"
    new "法国最后的诚实之人"
    old "{color=#A9A9A9}Раздобыть для рутьеров три пары обычных башмаков и одну пару модных туфель."
    new "{color=#A9A9A9}为佣兵们弄来三双普通靴子和一双时髦的便鞋。"
    old "{i}{size=-7}(Ги Буржиньон)"
    new "{i}{size=-7}（居伊·布尔吉尼翁）"
    old "Blood Money ([tarrar_blood_money_part_visual])"
    new "血钱（[tarrar_blood_money_part_visual]）"
    old "{color=#A9A9A9}Выполнить заказное убийство.{vspace=10}Дополнительное условие:{vspace=5}{color=#A9A9A9}[tarrar_death_condition_description!ti]"
    new "{color=#A9A9A9}完成一桩买凶杀人。{vspace=10}附加条件：{vspace=5}{color=#A9A9A9}[tarrar_death_condition_description!ti]"
    old "{i}{size=-7}(Таррар)"
    new "{i}{size=-7}（塔拉尔）"
    old "none"
    new "无"
    old "Broken two-handed sword"
    new "断裂的双手剑"
    old "Two-handed sword with a broken blade."
    new "剑刃断裂的双手剑。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}roken two-handed sword"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}断{/size}{/color}{/font}裂的双手剑"
    old "Blunt axe"
    new "钝斧"
    old "Axe with a blunt blade."
    new "刀刃已钝的斧。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}lunt axe"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}钝{/size}{/color}{/font}斧"
    old "Blunt two-handed axe"
    new "钝刃双手斧"
    old "Two-handed axe with a blunt blade."
    new "刀刃已钝的双手斧。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}lunt two-handed axe"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}钝{/size}{/color}{/font}刃双手斧"
    old "Blunt spear"
    new "钝矛"
    old "Spear with a blunt tip."
    new "矛尖已钝的矛。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}lunt spear"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}钝{/size}{/color}{/font}矛"
    old "Blunt javelin"
    new "钝标枪"
    old "Javelin with a blunt tip."
    new "尖端已钝的标枪。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}lunt javelin"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}钝{/size}{/color}{/font}标枪"
    old "Wooden stick"
    new "木棍"
    old "A pathetic remains of what once used to be a mace or a war club."
    new "昔日狼牙棒或战棍的可怜残骸。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}W{/size}{/color}{/font}ooden stick"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}木{/size}{/color}{/font}棍"
    old "Нead Chopper"
    new "断头刀"
    old "A wide-bladed shortsword easily capable of beheading a man with one slash.{vspace=5}{color=#A9A9A9}*Head strike damage modifier: 2.0{vspace=5}*Neck strike damage modifier: 3.0"
    new "一柄宽刃短剑，一刀便足以斩下人头。{vspace=5}{color=#A9A9A9}*头部攻击伤害倍率：2.0{vspace=5}*颈部攻击伤害倍率：3.0"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}H{/size}{/color}{/font}ead Chopper"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}断{/size}{/color}{/font}头刀"
    old "Reverse edge falchion"
    new "反刃弯刀"
    old "A falchion with a reversed edge for improved chopping power.{vspace=1}*Нas higher chance to inflict an injury{vspace=1}*Нas higher chance to inflict a bleeding"
    new "一柄反刃弯刀，砍劈之力更胜一筹。{vspace=1}*更易造成伤势{vspace=1}*更易造成流血"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}R{/size}{/color}{/font}everse edge falchion"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}反{/size}{/color}{/font}刃弯刀"
    old "War Cleaver"
    new "战砍刀"
    old "A crude and heavy war cleaver with the length of a longsword. An ugly weapon{vspace=1}for an ugly fight.{vspace=1}*Нas higher chance to inflict an injury{vspace=1}*Нas higher chance to inflict a bleeding"
    new "一把粗重笨拙的战砍刀，长度与长剑相当。丑陋的武器，{vspace=1}配得上丑陋的战斗。{vspace=1}*更易造成伤势{vspace=1}*更易造成流血"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}W{/size}{/color}{/font}ar Cleaver"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}战{/size}{/color}{/font}砍刀"
    old "Saif"
    new "赛义夫"
    old "Eastern shortsword with a slightly curved blade."
    new "一把微微弯曲的东方短剑。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}aif"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}赛{/size}{/color}{/font}义夫"
    old "Two-handed scimitar"
    new "双手弯刀"
    old "Eastern two-handed sword with a curved blade."
    new "一把弯曲刃的东方双手剑。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}T{/size}{/color}{/font}wo-handed scimitar"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}双{/size}{/color}{/font}手弯刀"
    old "Saracen pike"
    new "撒拉森长枪"
    old "An eastern-style spear designed for fast and agile attacks."
    new "一款东方式长矛，专为迅捷灵活的突刺设计。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}aracen pike"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}撒{/size}{/color}{/font}拉森长枪"
    old "Knight's warhammer"
    new "骑士战锤"
    old "A spiked warhammer equally good at smashing targets with blunt force or{vspace=5}piercing them with thrusting attacks."
    new "一把带尖刺的战锤，既能以钝力砸碎目标，{vspace=5}也能以突刺将其贯穿。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}K{/size}{/color}{/font}night's warhammer"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}骑{/size}{/color}{/font}士战锤"
    old "Two-handed flanged mace"
    new "双手棱锤"
    old "Large flanged mace designed to be operated with two hands."
    new "大型带棱锤头，需双手挥舞。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}T{/size}{/color}{/font}wo-handed flanged mace"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}双{/size}{/color}{/font}手棱锤"
    old "Burgundian Polehammer"
    new "勃艮第长柄战锤"
    old "A heavy-hitting warhammer mounted on a long pole with a spike at the end."
    new "一柄装在长杆上的重击战锤，杆端装有尖刺。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}urgundian Polehammer"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}勃{/size}{/color}{/font}艮第长柄战锤"
    old "Glaive"
    new "长柄刀"
    old "Highly versatile polearm capable of swift and deadly strikes."
    new "极为全能的长柄武器，出招迅捷致命。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}G{/size}{/color}{/font}laive"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}长{/size}{/color}{/font}柄刀"
    old "Vengeful Нand"
    new "复仇之手"
    old "A handy war pick that can punch through any kind of armor."
    new "一把趁手的战镐，能凿穿任何种类的护甲。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}V{/size}{/color}{/font}engeful Нand"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}复{/size}{/color}{/font}仇之手"
    old "Chair"
    new "椅子"
    old "A piece of furniture turned improvised weapon."
    new "一件临时充作武器的家具。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}C{/size}{/color}{/font}hair"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}椅{/size}{/color}{/font}子"
    old "Bronze Mace"
    new "青铜锤"
    old "A massive and very heavy one-handed mace.{vspace=5}*Bludgeoning attacks ignore an amount of enemy armor equal to the third of{vspace=1}your strength"
    new "一柄巨大而沉重的单手锤。{vspace=5}*钝击攻击无视的敌方护甲量，相当于你力量{vspace=1}的三分之一"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}B{/size}{/color}{/font}ronze Mace"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}青{/size}{/color}{/font}铜锤"
    old "Della Torre's warhammer"
    new "德拉·托雷的战锤"
    old "Family relic of house Della Torre.{vspace=5}*Does additional damage equal to 50% of stat debuffs of your body armor{vspace=5}*Bludgeoning attacks ignore an amount of enemy armor equal to the third of{vspace=1}your strength"
    new "德拉·托雷家族的传家之物。{vspace=5}*造成额外伤害，数额相当于你护甲属性减益的 50%{vspace=5}*钝击攻击无视的敌方护甲量，相当于你力量{vspace=1}的三分之一"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}D{/size}{/color}{/font}ella Torre's warhammer"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}德{/size}{/color}{/font}拉·托雷的战锤"
    old "Emperor's sword"
    new "皇帝之剑"
    old "This imperial longsword's blade is etched with holy crosses, its gilded{vspace=1}hilt inlaid with rubies and gold. A weapon of war, but more a symbol of{vspace=1}Emperor's unquestioned authority."
    new "这柄帝国长剑的剑身镌刻着圣十字，镀金的{vspace=1}剑柄镶有红宝石与黄金。它是征战之器，但更是{vspace=1}皇帝无上权威的象征。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}mperor's sword"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}皇{/size}{/color}{/font}帝之剑"
    old "Elegant scabbard"
    new "优雅剑鞘"
    old "Wrought from gilded leather and velvet, this scabbard's surface is{vspace=1}a masterwork of engraved heraldry.{vspace=25}*Can be used to equip a secondary weapon"
    new "以镀金皮革与天鹅绒制成，此剑鞘的表面{vspace=1}堪称纹章雕刻的杰作。{vspace=25}*可用于装备副手武器"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}legant scabbard"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}优{/size}{/color}{/font}雅剑鞘"
    old "Lucky Dice"
    new "幸运骰子"
    old "A true gambler's treasure. Current win streak: [player_lucky_dice_win_streak]{vspace=1}{size=-5}Strength: +[lucky_dice.strength]{vspace=1}Agility: +[lucky_dice.agility]{vspace=1}Coordination: +[lucky_dice.coordination]{vspace=1}Endurance: +[lucky_dice.endurance]{vspace=1}Vitality: +[lucky_dice.vitality]{vspace=1}Weapon Skill: +[lucky_dice.player_weapon_skill]{vspace=1}Evasion: +[lucky_dice.evasion]{vspace=1}Bonus damage: +[lucky_dice.bonus_damage]{vspace=1}Bonus injury chance: +[lucky_dice.injury_chance]"
    new "真正赌徒的至宝。当前连胜场数：[player_lucky_dice_win_streak]{vspace=1}{size=-5}力量：+[lucky_dice.strength]{vspace=1}敏捷：+[lucky_dice.agility]{vspace=1}协调：+[lucky_dice.coordination]{vspace=1}耐力：+[lucky_dice.endurance]{vspace=1}体质：+[lucky_dice.vitality]{vspace=1}武器技能：+[lucky_dice.player_weapon_skill]{vspace=1}闪避：+[lucky_dice.evasion]{vspace=1}额外伤害：+[lucky_dice.bonus_damage]{vspace=1}额外伤势几率：+[lucky_dice.injury_chance]"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}L{/size}{/color}{/font}ucky dice"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}幸{/size}{/color}{/font}运骰子"
    old "Tartsche shield"
    new "塔尔奇盾"
    old "A well-made shield designed for use with a lance while on horseback.{vspace=5}*Improves shield block chance by 10 if used with a spear{vspace=5}*Improves weapon hit chance by 10 if used with a spear"
    new "一面做工精良的盾牌，专为骑乘持矛冲锋而设计。{vspace=5}*与长矛搭配使用时，盾牌格挡几率提升 10{vspace=5}*与长矛搭配使用时，武器命中率提升 10"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}T{/size}{/color}{/font}artsche shield"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}塔{/size}{/color}{/font}尔奇盾"
    old "Stool"
    new "小板凳"
    old "A piece of furniture turned improvised shield."
    new "一件临时充作盾牌的家具。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}tool"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}小{/size}{/color}{/font}板凳"
    old "Executioner's hood"
    new "刽子手头罩"
    old "An executioner's hood that is a little hard to see in.{vspace=5}*Increases neck damage modifier to 3{vspace=5}*Нit chance: -10{vspace=5}*Virtue: -30{vspace=5}*Prestige: -10"
    new "一顶刽子手的头罩，戴上后视物有些困难。{vspace=5}*颈部伤害倍率提升至 3{vspace=5}*命中率：-10{vspace=5}*美德：-30{vspace=5}*威望：-10"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}xecutioner's hood"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}刽{/size}{/color}{/font}子手头罩"
    old "Adam's head"
    new "亚当头像"
    old "An elegant medallion with Adam's head.{vspace=5}*Increases head damage modifier to 2.5{vspace=5}*Prestige: +7"
    new "一枚刻有亚当头像的精致勋章。{vspace=5}*头部伤害倍率提升至 2.5{vspace=5}*威望：+7"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}A{/size}{/color}{/font}dam's head"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}亚{/size}{/color}{/font}当头像"
    old "Wolf Нead Pendant"
    new "狼头吊坠"
    old "A crudely made pendant with a ferocious-looking wolf.{vspace=5}*Recovers 3 fatigue for every 1 HP lost in battle"
    new "一条做工粗陋的吊坠，坠着一头面目狰狞的狼。{vspace=5}*战斗中每损失 1 点生命值，恢复 3 点疲劳"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}W{/size}{/color}{/font}olf Нead Pendant"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}狼{/size}{/color}{/font}头吊坠"
    old "Нoly orders"
    new "圣修会"
    old "A sharp dagger that fits well in both your sword arm and off hand.{vspace=5}Will surely make for a great secondary weapon.{vspace=25}*Bonus damage: +3"
    new "一柄锋利的匕首，主手副手都趁手。{vspace=5}必定能成为出色的副武器。{vspace=25}*额外伤害：+3"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}H{/size}{/color}{/font}oly orders"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}圣{/size}{/color}{/font}修会"
    old "Lockpicks"
    new "开锁工具"
    old "A set of lockpicks.{vspace=5}*Agility: +1{vspace=5}*Coordination: +1{vspace=5}*Increases chances of a successful heist{vspace=5}*Personal participation in a heist yields an additional item"
    new "一套开锁工具。{vspace=5}*敏捷：+1{vspace=5}*协调：+1{vspace=5}*提高劫案成功的几率{vspace=5}*亲自参与劫案时额外获得一件物品"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}L{/size}{/color}{/font}ockpicks"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}开{/size}{/color}{/font}锁工具"
    old "Oak Leaf Talisman"
    new "橡叶护符"
    old "A talisman in a form of an oak leaf.{vspace=5}*Lowers incoming shield damage by 60%"
    new "一片橡树叶形状的护符。{vspace=5}*受到的盾牌伤害降低 60%"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}O{/size}{/color}{/font}ak Leaf Talisman"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}橡{/size}{/color}{/font}叶护符"
    old "Нourglass"
    new "沙漏"
    old "A common hourglass. Nothing unusual about it.{vspace=5}*Passive ability: Lowers item cooldowns by 50%{vspace=5}*Active ability: Instantly recharges single-use items"
    new "一只寻常的沙漏，并无奇特之处。{vspace=5}*被动能力：道具冷却时间降低 50%{vspace=5}*主动能力：立即为一次性道具充能"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}H{/size}{/color}{/font}ourglass"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}沙{/size}{/color}{/font}漏"
    old "Cat Ring"
    new "猫形戒指"
    old "A rusted silver ring in a shape of a cat.{vspace=5}*Grants 1 guaranteed dodge in combat{vspace=5}*Prestige: +1"
    new "一枚猫形的生锈银戒指。{vspace=5}*战斗中保证闪避一次{vspace=5}*威望：+1"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}C{/size}{/color}{/font}at Ring"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}猫{/size}{/color}{/font}形戒指"
    old "Mandrake root"
    new "曼德拉草根"
    old "Highly-valuable plant that is commonly used in medicine and alchemy.{vspace=5}*Lowers toxicity by 10 every turn{vspace=5}*Recovers [mandrake_root_health_recovery] HP after every toxicity reduction"
    new "一种价值不菲的植物，常用于医药与炼金。{vspace=5}*每回合降低 10 点毒性{vspace=5}*每次毒性降低后恢复 [mandrake_root_health_recovery] 点生命值"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}M{/size}{/color}{/font}andrake root"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}曼{/size}{/color}{/font}德拉草根"
    old "Whip"
    new "鞭子"
    old "Finely-crafted leather whip capable of swift and lightning-fast strikes.{vspace=5}*Agility: +4"
    new "一条做工精细的皮鞭，挥击迅捷如电。{vspace=5}*敏捷：+4"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}W{/size}{/color}{/font}hip"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}鞭{/size}{/color}{/font}子"
    old "Torture tools"
    new "刑具"
    old "A set of ominous-looking torture tools, designed to extract confessions{vspace=5}or inflict pain.{vspace=5}*Increases damage dealt to enemies by bleedings by 1{vspace=5}*Prolongs duration of inflicted bleedings by 1{vspace=5}*Injury chance: +10{vspace=5}*Injury stats debuff (enemy): +3{vspace=5}*Virtue: -20"
    new "一套外观可怖的刑具，专为逼供{vspace=5}或施虐而设计。{vspace=5}*流血对敌人造成的伤害 +1{vspace=5}*施加的流血持续时间 +1{vspace=5}*伤势几率：+10{vspace=5}*敌人伤势属性减益：+3{vspace=5}*美德：-20"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}T{/size}{/color}{/font}orture tools"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}刑{/size}{/color}{/font}具"
    old "Soldier's cauldron"
    new "士兵的铁锅"
    old "Worn out but sturdy iron cauldron. A trusty companion of any soldier.{vspace=5}*Vitality: +1{vspace=5}*Endurance: +1"
    new "一口破旧却结实的铁锅，任何士兵的忠实伙伴。{vspace=5}*体质：+1{vspace=5}*耐力：+1"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}S{/size}{/color}{/font}oldier's cauldron"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}士{/size}{/color}{/font}兵的铁锅"
    old "Emperor's Armor"
    new "皇帝铠甲"
    old "Emperor's armor"
    new "皇帝铠甲"
    old "Forged for emperors, this gilded plate armor is both a sovereign's safeguard{vspace=1}and a sacred symbol. Its gleaming surface is intricately etched with holy{vspace=1}motifs, proclaiming the wearer as God's chosen champion on Earth."
    new "为帝王而铸，这套镀金板甲既是君主的护身之物，{vspace=1}也是神圣的象征。其闪耀的表面精细镌刻着圣洁{vspace=1}纹样，宣告穿戴者是上帝在世间的钦定斗士。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}mperor's armor"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}皇{/size}{/color}{/font}帝铠甲"
    old "Emperor's Нelmet"
    new "皇帝头盔"
    old "Forged for emperors, this marvellous helmet is both a sovereign's safeguard{vspace=1}and a sacred symbol. Its gleaming surface is intricately etched with holy{vspace=1}motifs, proclaiming the wearer as God's chosen champion on Earth."
    new "为帝王而铸，这顶非凡的头盔既是君主的护身之物，{vspace=1}也是神圣的象征。其闪耀的表面精细镌刻着圣洁{vspace=1}纹样，宣告穿戴者是上帝在世间的钦定斗士。"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}E{/size}{/color}{/font}mperor's Нelmet"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}皇{/size}{/color}{/font}帝头盔"
    old "Numbing Remedy"
    new "麻痹药剂"
    old "A special remedy that can act as a potent painkiller, numbing the body{vspace=5}for a short period of time.{vspace=5}*Removes all stats losses from injuries for 10 turns"
    new "一种特殊药剂，可作强效止痛之用，令身体{vspace=5}在短时间内失去知觉。{vspace=5}*10 回合内移除伤势造成的所有属性损失"
    old "{font=GoudyInitialen.ttf}{color=#8B0000}{size=+70}N{/size}{/color}{/font}umbing remedy"
    new "{font=chn_font.otf}{color=#8B0000}{size=+30}麻{/size}{/color}{/font}痹药剂"
    old "Alchemist's tools + Medicine + Antidote III + Waterskin + Strong ale{vspace=5}Alchemist's tools + Medicine + Antidote III + Waterskin + Wine bottle"
    new "炼金工具 + 药品 + 解毒剂 III + 水袋 + 烈性麦酒{vspace=5}炼金工具 + 药品 + 解毒剂 III + 水袋 + 葡萄酒瓶"
    old "Prefs"
    new "偏好"
    old "{size=+10}Continue"
    new "{size=+10}继续"
    old "{size=+10}New Game"
    new "{size=+10}新游戏"
    old "Survival Mode"
    new "生存模式"
    old "Proving Grounds"
    new "试炼场"
    old "Нigh Scores"
    new "高分榜"
    old "Redeem code"
    new "兑换码"
    old "Load"
    new "读取"
    old "Settings"
    new "设置"
    old "Language"
    new "语言"
    old "End Replay"
    new "结束回放"
    old "Main Menu"
    new "主菜单"
    old "About"
    new "关于"
    old "Quit"
    new "退出"
    old "The game was just updated to a version 1.8!{vspace=20}The full changelog can be viewed in our{vspace=5}Community Hub on Steam or on our Discord.{vspace=20}Saves should still be compatible but it is generally{vspace=5}suggested to start a new playthrough."
    new "游戏刚刚更新至 1.8 版本！{vspace=20}完整更新日志可在 Steam 的{vspace=5}社区中心或我们的 Discord 中查看。{vspace=20}旧存档应仍可兼容，但通常{vspace=5}建议开启新的游玩周目。"
    old "Survival mode"
    new "生存模式"
    old "unlocked!"
    new "已解锁！"
    old "{size=-10}{i}{color=#A9A9A9}'Нappily Ever After' DLC is installed"
    new "{size=-10}{i}{color=#A9A9A9}已安装《从此幸福快乐》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Happily Ever After' DLC is NOT installed"
    new "{size=-10}{i}{color=#A9A9A9}未安装《从此幸福快乐》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Not a Нero' DLC is installed"
    new "{size=-10}{i}{color=#A9A9A9}已安装《并非英雄》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Not a Нero' DLC is NOT installed"
    new "{size=-10}{i}{color=#A9A9A9}未安装《并非英雄》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Threads of Destiny' DLC is installed"
    new "{size=-10}{i}{color=#A9A9A9}已安装《命运之线》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Threads of Destiny' DLC is NOT installed"
    new "{size=-10}{i}{color=#A9A9A9}未安装《命运之线》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Sins of the Floating City' DLC is installed"
    new "{size=-10}{i}{color=#A9A9A9}已安装《浮城之罪》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Sins of the Floating City' DLC is NOT installed"
    new "{size=-10}{i}{color=#A9A9A9}未安装《浮城之罪》DLC"
    old "{size=-10}{i}{color=#A9A9A9}Supporter Pack is installed"
    new "{size=-10}{i}{color=#A9A9A9}已安装支持者礼包"
    old "{size=-10}{i}{color=#A9A9A9}Supporter Pack is NOT installed"
    new "{size=-10}{i}{color=#A9A9A9}未安装支持者礼包"
    old "{size=-10}{i}{color=#A9A9A9}'Tailor's Chest' DLC is installed"
    new "{size=-10}{i}{color=#A9A9A9}已安装《裁缝之箱》DLC"
    old "{size=-10}{i}{color=#A9A9A9}'Tailor's Chest' DLC is NOT installed"
    new "{size=-10}{i}{color=#A9A9A9}未安装《裁缝之箱》DLC"
    old "Return"
    new "返回"
    old "Version [config.version!t]\n"
    new "版本 [config.version!t]\n"
    old "Created by 1917 Studios."
    new "由 1917 Studios 制作。"
    old "{vspace=20}Watch full credits."
    new "{vspace=20}观看完整制作名单。"
    old "{vspace=200}Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new "{vspace=200}使用 {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only] 制作。\n\n[renpy.license!t]"
    old "Page {}"
    new "第 {} 页"
    old "Automatic saves"
    new "自动存档"
    old "Quick Saves"
    new "快速存档"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%Y 年 %B %d 日，%A，%H:%M"
    old "empty slot"
    new "空槽位"
    old "<"
    new "<"
    old "{#auto_page}A"
    new "{#auto_page}A"
    old "{#quick_page}Q"
    new "{#quick_page}Q"
    old ">"
    new ">"
    old "Preferences"
    new "偏好设置"
    old "Display"
    new "显示"
    old "Window"
    new "窗口"
    old "Fullscreen"
    new "全屏"
    old "Skip"
    new "跳过"
    old "Unseen Text"
    new "未读文本"
    old "After Choices"
    new "选项之后"
    old "Transitions"
    new "过场"
    old "{size=-5}{color=#A9A9A9}{vspace=10}  Нold 'Ctrl' to Skip"
    new "{size=-5}{color=#A9A9A9}{vspace=10}  按住“Ctrl”进行跳过"
    old "Mature Content"
    new "成人内容"
    old "On"
    new "开启"
    old "Off"
    new "关闭"
    old "Text Speed"
    new "文字速度"
    old "Auto-Forward Time"
    new "自动前进间隔"
    old "{vspace=25}Key Binds"
    new "{vspace=25}按键绑定"
    old "{size=-5}{color=#A9A9A9}{vspace=10}Press 'F4' to show key binds (in battle)"
    new "{size=-5}{color=#A9A9A9}{vspace=10}战斗中按下“F4”查看按键绑定"
    old "{size=-5}{color=#A9A9A9}{vspace=10}Press 'Right Mouse Button' to display quick action buttons (in inventory)"
    new "{size=-5}{color=#A9A9A9}{vspace=10}在物品栏中按下“鼠标右键”以显示快捷操作按钮"
    old "Music Volume"
    new "音乐音量"
    old "Sound Volume"
    new "音效音量"
    old "Test"
    new "测试"
    old "Voice Volume"
    new "语音音量"
    old "Mute All"
    new "全部静音"
    old "History"
    new "历史"
    old "The dialogue history is empty."
    new "对话历史为空。"
    old "Help"
    new "帮助"
    old "Keyboard"
    new "键盘"
    old "Mouse"
    new "鼠标"
    old "Gamepad"
    new "手柄"
    old "Enter"
    new "回车"
    old "Advances dialogue and activates the interface."
    new "推进对话并激活界面。"
    old "Space"
    new "空格键"
    old "Advances dialogue without selecting choices."
    new "推进对话但不选择选项。"
    old "Arrow Keys"
    new "方向键"
    old "Navigate the interface."
    new "在界面中移动。"
    old "Accesses the game menu."
    new "打开游戏菜单。"
    old "Ctrl"
    new "Ctrl"
    old "Skips dialogue while held down."
    new "按住时跳过对话。"
    old "Tab"
    new "Tab"
    old "Toggles dialogue skipping."
    new "切换对话跳过。"
    old "Page Up"
    new "Page Up"
    old "Rolls back to earlier dialogue."
    new "回滚到较早的对话。"
    old "Page Down"
    new "Page Down"
    old "Rolls forward to later dialogue."
    new "快进到之后的对话。"
    old "Hides the user interface."
    new "隐藏用户界面。"
    old "Takes a screenshot."
    new "截取屏幕截图。"
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new "切换辅助{a=https://www.renpy.org/l/voicing}自述语音{/a}功能。"
    old "Left Click"
    new "左键点击"
    old "Middle Click"
    new "中键点击"
    old "Right Click"
    new "右键点击"
    old "Mouse Wheel Up\nClick Rollback Side"
    new "鼠标滚轮向上\n点击回滚区域"
    old "Mouse Wheel Down"
    new "鼠标滚轮向下"
    old "Right Trigger\nA/Bottom Button"
    new "右扳机\nA/底部按钮"
    old "Left Trigger\nLeft Shoulder"
    new "左扳机\n左肩键"
    old "Right Shoulder"
    new "右肩键"
    old "D-Pad, Sticks"
    new "十字键、摇杆"
    old "Start, Guide"
    new "开始、指南"
    old "Y/Top Button"
    new "Y/顶部按钮"
    old "Calibrate"
    new "校准"
    old "Skipping"
    new "跳过中"
    old "Back"
    new "返回"
    old "Auto"
    new "自动"
    old "Menu"
    new "菜单"
