# TODO: Translation updated at 2026-08-02 23:21

# game/script_2.rpy:1123
translate chinese tutorial_crossbow_combat_enemy_2a926a69:

    nvl clear
    "{cps=50}教学：对抗弩手{vspace=25}弩是一种威力极强的武器，经常出现在中世纪战场上。在你的冒险旅途中，也会多次遇到手持弩的敌人。"

# game/script_2.rpy:1126
translate chinese tutorial_crossbow_combat_enemy_077c1531:

    nvl clear
    "{cps=50}你可以打开敌人的装备菜单，查看他是否携带弩——菜单中会显示弩的图标。"

# game/script_2.rpy:1129
translate chinese tutorial_crossbow_combat_enemy_56e19aa4:

    nvl clear
    "{cps=50}将鼠标悬停在他身上，就能看到对手使用的是什么型号的弩、他的射击水平如何、弩矢还剩多少，以及弩中装填的是哪种矢。"

# game/script_2.rpy:1131
translate chinese tutorial_crossbow_combat_enemy_5f80203b:

    nvl clear
    "{cps=50}敌人的命中判定方式与玩家相同。也就是说，想要学会准确判断敌方弩手的威胁程度，最好的办法就是亲自上阵练习使用弩。"

# game/script_2.rpy:1133
translate chinese tutorial_crossbow_combat_enemy_7020dc7c:

    nvl clear
    "{cps=50}各类伤势都会对命中率产生显著影响。有些武器即使只剩一只手也能勉强使用，但失去双手的话，就无法用弩进行精确射击了。"

# game/script_2.rpy:1135
translate chinese tutorial_crossbow_combat_enemy_eb1b5223:

    nvl clear
    "{cps=50}因此，要让弩手丧失战斗力，最有效的办法就是打伤他的手臂。"

# game/script_2.rpy:1137
translate chinese tutorial_crossbow_combat_enemy_cef069c2:

    nvl clear
    "{cps=50}此外，佯攻和致盲（头部伤势）对付持弩的敌人同样有效。"

# game/script_2.rpy:1139
translate chinese tutorial_crossbow_combat_enemy_76b2fe88:

    nvl clear
    ""

# game/script_2.rpy:3866
translate chinese player_use_wine_battle_b9fbb99f:

    nvl clear
    "{cps=50}{color=#A9A9A9}你喝下的那瓶酒居然有毒！{vspace=5}生命值减少50！{vspace=5}活力减少5！{vspace=5}毒性增加90！"

# game/script_2.rpy:3868
translate chinese player_use_wine_battle_76b2fe88:

    nvl clear
    ""

# game/script_2.rpy:3941
translate chinese player_use_ale_battle_b9fbb99f:

    nvl clear
    "{cps=50}{color=#A9A9A9}你喝下的那瓶酒居然有毒！{vspace=5}生命值减少50！{vspace=5}活力减少5！{vspace=5}毒性增加90！"

# game/script_2.rpy:3943
translate chinese player_use_ale_battle_76b2fe88:

    nvl clear
    ""

# game/script_2.rpy:61772
translate chinese arthur_bonus_turn_end_e451d040:

    "错误：标签“end turn”未定义"

# game/script_2.rpy:64403
translate chinese victory_b14b8d56:

    "错误：标签“victory”未定义"

translate chinese strings:

    old "{color=#000000}Fatigue -[wolf_head_pendant_visual_value]"
    new "{color=#000000}疲劳 -[wolf_head_pendant_visual_value]"
    old "{color=#008000}Нealth +[lepers_mask_heal_modifier]!{/color}"
    new "{color=#008000}生命 +[lepers_mask_heal_modifier]！{/color}"
    old "{color=#000000}Poisonous fumes!{vspace=5}Toxicity increased{/color}"
    new "{color=#000000}毒气弥漫！{vspace=5}毒性上升{/color}"
    old "{color=#000000}Your turn!{/color}"
    new "{color=#000000}轮到你了！{/color}"
    old "{color=#8B0000}[trait!ti] bled to death!{/color}"
    new "{color=#8B0000}[trait!ti] 失血过多而亡！{/color}"
    old "{color=#000000}[trait!ti] {color=#008000}died from poison!{/color}"
    new "{color=#000000}[trait!ti] {color=#008000}中毒而死！{/color}"
    old "{color=#000000}Bleeding resisted!{/color}"
    new "{color=#000000}抵抗了流血！{/color}"
    old "{color=#8B0000}Bleeding!{/color}"
    new "{color=#8B0000}流血！{/color}"
    old "{color=#8B0000}Нeavy Bleeding!{/color}"
    new "{color=#8B0000}重度流血！{/color}"
    old "{color=#000000}Poison resisted!{/color}"
    new "{color=#000000}抵抗了中毒！{/color}"
    old "{color=#008000}Dying to poison!{/color}"
    new "{color=#008000}中毒濒死！{/color}"
    old "{color=#000000}Нeat!{vspace=5}Fatigue +[heat_debuff]{/color}"
    new "{color=#000000}酷热！{vspace=5}疲劳 +[heat_debuff]{/color}"
    old "{color=#000000}Sandstorm!{/color}"
    new "{color=#000000}沙尘暴！{/color}"
    old "{color=#000000}Stunned! Unable to move!{/color}"
    new "{color=#000000}被击晕！无法移动！{/color}"
    old "{size=-2}Rotation"
    new "{size=-2}轮换"
    old "{size=-10}{color=#A9A9A9}Orders the soldiers from your squad to swap places — the one that is{vspace=5}currently fighting will retreat and a fresh one will take his place.{vspace=5}Out of combat units regenerate their stamina and gradually recover{vspace=5}from fatigue. However they can still die from bleedings or poisonings{vspace=5}suffered in combat."
    new "{size=-10}{color=#A9A9A9}命令你小队中的士兵互换位置——当前正在战斗的士兵将撤退，由一位体力充沛的士兵接替他的位置。{vspace=5}未参与战斗的单位会恢复体力，并逐渐从疲劳中恢复。{vspace=5}不过，他们仍可能因战斗中遭受的流血或中毒而死。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}10"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}10"
    old "{size=-2}Order a retreat"
    new "{size=-2}下令撤退"
    old "{size=-10}{color=#A9A9A9}Retreats the current ally from battle."
    new "{size=-10}{color=#A9A9A9}让当前队友撤出战斗。"
    old "{size=-2}First aid"
    new "{size=-2}急救"
    old "{size=-10}{color=#A9A9A9}Uses one of your consumable items on ally."
    new "{size=-10}{color=#A9A9A9}对队友使用一件消耗品。"
    old "{size=-10}Offensive stance{color=#A9A9A9}— increases melee weapon hit chance (by a % of your{vspace=1}weapon skill) but lowers the chances to evade or shield block enemy{vspace=1}attack. Very susceptible to enemy feints."
    new "{size=-10}进攻姿态{color=#A9A9A9}——提高近战武器的命中率（按你的武器技能的一定百分比），{vspace=1}但降低闪避或持盾格挡敌方攻击的概率。{vspace=1}极易被敌方佯攻所惑。"
    old "{size=-10}Defensive stance{color=#A9A9A9}— increases the chances to evade or shield block enemy{vspace=1}attack (by a % of your agility) but lowers your own melee weapon hit{vspace=1}chance. Susceptible to enemy feints."
    new "{size=-10}防守姿态{color=#A9A9A9}——提高闪避或持盾格挡敌方攻击的概率（按你的敏捷的一定百分比），{vspace=1}但降低自身近战武器的命中率。{vspace=1}易被敌方佯攻所惑。"
    old "{size=-10}Balanced stance{color=#A9A9A9}— provides no offensive or defensive bonuses.{vspace=1}Least susceptible to enemy feints."
    new "{size=-10}平衡姿态{color=#A9A9A9}——不提供任何进攻或防御加成。{vspace=1}对敌方佯攻的抵抗力最强。"
    old "{size=-5}Attack"
    new "{size=-5}攻击"
    old "{size=-5}Feint"
    new "{size=-5}佯攻"
    old "{size=-5}Recover"
    new "{size=-5}恢复"
    old "{size=-5}OFF stance"
    new "{size=-5}攻姿"
    old "{size=-5}DEF stance"
    new "{size=-5}防姿"
    old "{size=-5}BAL stance"
    new "{size=-5}衡姿"
    old "{size=-5}Crossbow"
    new "{size=-5}弩"
    old "{size=-5}Shield"
    new "{size=-5}盾牌"
    old "{size=-5}Items"
    new "{size=-5}物品"
    old "{size=-5}Respite: [player_respite_ready]"
    new "{size=-5}喘息：[player_respite_ready]"
    old "{size=-5}Respite"
    new "{size=-5}喘息"
    old "{color=#000000}You are not fatigued!{/color}"
    new "{color=#000000}你并未疲劳！{/color}"
    old "{color=#000000}Can't do that yet!{/color}"
    new "{color=#000000}还无法这么做！{/color}"
    old "{size=-7}Pouch"
    new "{size=-7}袋囊"
    old "{size=-7}Scabbard"
    new "{size=-7}剑鞘"
    old "{size=-9}{color=#A9A9A9}Base DMG: [player_attack]{vspace=1}Bonus DMG: [special_effect_bonus_damage]"
    new "{size=-9}{color=#A9A9A9}基础伤害：[player_attack]{vspace=1}附加伤害：[special_effect_bonus_damage]"
    old "{size=-7}{color=#A9A9A9}Charges: [weapon_poison_stacks]"
    new "{size=-7}{color=#A9A9A9}充能：[weapon_poison_stacks]"
    old "{size=-7}{color=#A9A9A9}Shield: [player_shield]/[player_shield_full]"
    new "{size=-7}{color=#A9A9A9}盾牌：[player_shield]/[player_shield_full]"
    old "{color=#000000}Respite{/color}"
    new "{color=#000000}喘息{/color}"
    old "Double recovery!"
    new "双倍恢复！"
    old "{color=#000000}Fatigue -[player_fatigue_recovery]{vspace=5}[double_fatigue_recover_chance!ti]{/color}"
    new "{color=#000000}疲劳 -[player_fatigue_recovery]{vspace=5}[double_fatigue_recover_chance!ti]{/color}"
    old "{size=-5}{i}Pouch:"
    new "{size=-5}{i}袋囊："
    old "{size=-5}{i}Equipped:"
    new "{size=-5}{i}已装备："
    old "{size=-5}[hourglass.name!ti]"
    new "{size=-5}[hourglass.name!ti]"
    old "{size=-5}[well_tuned_lute.name!ti]"
    new "{size=-5}[well_tuned_lute.name!ti]"
    old "{size=-5}[olifant.name!ti]"
    new "{size=-5}[olifant.name!ti]"
    old "{size=-5}[bloodletting_tools.name!ti]"
    new "{size=-5}[bloodletting_tools.name!ti]"
    old "{size=-5}[fair_maidens_portrait.name!ti]"
    new "{size=-5}[fair_maidens_portrait.name!ti]"
    old "{size=-5}[ritual_dagger.name!ti]"
    new "{size=-5}[ritual_dagger.name!ti]"
    old "{size=-5}[fencing_dagger.name!ti]"
    new "{size=-5}[fencing_dagger.name!ti]"
    old "{size=-5}[rondel_dagger.name!ti]"
    new "{size=-5}[rondel_dagger.name!ti]"
    old "{size=-5}[miseriecorde.name!ti]"
    new "{size=-5}[miseriecorde.name!ti]"
    old "{size=-5}[brigands_blade.name!ti]"
    new "{size=-5}[brigands_blade.name!ti]"
    old "{size=-5}[jambiya.name!ti]"
    new "{size=-5}[jambiya.name!ti]"
    old "{size=-5}[dagger.name!ti]"
    new "{size=-5}[dagger.name!ti]"
    old "{size=-5}[mail_breaker.name!ti]"
    new "{size=-5}[mail_breaker.name!ti]"
    old "{size=-5}[elegant_stiletto.name!ti]"
    new "{size=-5}[elegant_stiletto.name!ti]"
    old "{size=-5}[hunting_knife.name!ti]"
    new "{size=-5}[hunting_knife.name!ti]"
    old "{size=-5}[butchers_blade.name!ti]"
    new "{size=-5}[butchers_blade.name!ti]"
    old "{size=-5}[militia_dagger.name!ti]"
    new "{size=-5}[militia_dagger.name!ti]"
    old "{size=-5}[poisoned_feast_knife.name!ti]"
    new "{size=-5}[poisoned_feast_knife.name!ti]"
    old "{size=-5}[blackjack.name!ti]"
    new "{size=-5}[blackjack.name!ti]"
    old "{size=-5}[fancy_shoes.name!ti]"
    new "{size=-5}[fancy_shoes.name!ti]"
    old "{size=-5}[caestus.name!ti]"
    new "{size=-5}[caestus.name!ti]"
    old "{size=-5}[knights_bracer.name!ti]"
    new "{size=-5}[knights_bracer.name!ti]"
    old "{size=-5}[jousting_bracer.name!ti]"
    new "{size=-5}[jousting_bracer.name!ti]"
    old "{size=-5}[sharp_thorned_rose.name!ti]"
    new "{size=-5}[sharp_thorned_rose.name!ti]"
    old "{color=#000000}Wine used!{/color}"
    new "{color=#000000}饮用了葡萄酒！{/color}"
    old "{color=#000000}Fatigue -[player_fatigue_recovery]{/color}"
    new "{color=#000000}疲劳 -[player_fatigue_recovery]{/color}"
    old "{color=#000000}Ale used!{/color}"
    new "{color=#000000}饮用了麦酒！{/color}"
    old "{color=#000000}{font=meiryo.ttc}♫{/font}Strum a chord!{font=meiryo.ttc}♫{/font}{/color}"
    new "{color=#000000}{font=meiryo.ttc}♫{/font}拨动琴弦！{font=meiryo.ttc}♫{/font}{/color}"
    old "{color=#000000}Olifant used!"
    new "{color=#000000}使用了象牙号角！"
    old "{color=#000000}Bloodletting tools used!"
    new "{color=#000000}使用了放血工具！"
    old "{color=#000000}Minor Vitality brew used!{/color}"
    new "{color=#000000}使用了小型活力药剂！{/color}"
    old "{color=#000000}Major Vitality brew used!{/color}"
    new "{color=#000000}使用了大型活力药剂！{/color}"
    old "{color=#000000}Stamina recovery brew used!{/color}"
    new "{color=#000000}使用了体力恢复药剂！{/color}"
    old "{color=#000000}Fatigue recovery brew used!{/color}"
    new "{color=#000000}使用了疲劳恢复药剂！{/color}"
    old "{color=#000000}Sharp-Thorned Rose used!"
    new "{color=#000000}使用了利刺玫瑰！"
    old "{color=#000000}Can't use!"
    new "{color=#000000}无法使用！{/color}"
    old "{color=#000000}Fair Maidens Portrait used!"
    new "{color=#000000}使用了少女画像！"
    old "{color=#000000}Injury healed!"
    new "{color=#000000}伤势已治愈！{/color}"
    old "{color=#000000}Нealth +15!"
    new "{color=#000000}生命 +15！{/color}"
    old "{color=#000000}Poison shield received!"
    new "{color=#000000}获得毒盾！{/color}"
    old "{color=#000000}Stamina recovered!"
    new "{color=#000000}体力恢复！{/color}"
    old "{color=#000000}Нydration +[player_stamina_max]!"
    new "{color=#000000}水分 +[player_stamina_max]！{/color}"
    old "{color=#000000}Fatigue -[player_fatigue_pool]!"
    new "{color=#000000}疲劳 -[player_fatigue_pool]！{/color}"
    old "{color=#000000}Bleedings and poisonings removed!"
    new "{color=#000000}流血与中毒状态已清除！{/color}"
    old "{color=#000000}Numbing Remedy used!"
    new "{color=#000000}使用了麻痹药剂！{/color}"
    old "{color=#000000}Poison applied!{/color}"
    new "{color=#000000}已涂毒！{/color}"
    old "{color=#000000}Virtue -5!{/color}"
    new "{color=#000000}美德 -5！{/color}"
    old "{color=#000000}Weapon already poisoned!{/color}"
    new "{color=#000000}武器已涂过毒！{/color}"
    old "{color=#000000}Antidote used!{/color}"
    new "{color=#000000}使用了解毒剂！{/color}"
    old "{color=#000000}Bandage used!{/color}"
    new "{color=#000000}使用了绷带！{/color}"
    old "{color=#000000}Aseptic bandage used!{/color}"
    new "{color=#000000}使用了无菌绷带！{/color}"
    old "{color=#000000}[coagulant.name] used!{/color}"
    new "{color=#000000}[coagulant.name] 已使用！{/color}"
    old "{color=#000000}Tourniquet used!{/color}"
    new "{color=#000000}使用了止血带！{/color}"
    old "{color=#000000}Canteen used!{/color}"
    new "{color=#000000}使用了水壶！{/color}"
    old "{color=#000000}Waterskin used!{/color}"
    new "{color=#000000}使用了水囊！{/color}"
    old "{color=#000000}[stun_resistance_brew.name!ti] used!{/color}"
    new "{color=#000000}[stun_resistance_brew.name!ti] 已使用！{/color}"
    old "{color=#000000}[poison_resistance_brew.name!ti] used!{/color}"
    new "{color=#000000}[poison_resistance_brew.name!ti] 已使用！{/color}"
    old "{color=#000000}[reflex_boost_brew.name!ti] used!{/color}"
    new "{color=#000000}[reflex_boost_brew.name!ti] 已使用！{/color}"
    old "{color=#000000}Scabbard empty!{/color}"
    new "{color=#000000}剑鞘已空！{/color}"
    old "{size=-7}Dagger Throw{/size}"
    new "{size=-7}投掷匕首{/size}"
    old "{size=-7}Dagger Stab"
    new "{size=-7}匕首刺击"
    old "{size=-2}Dagger Throw"
    new "{size=-2}投掷匕首"
    old "{size=-7}{color=#A9A9A9}Knife-throwing attack.{vspace=5}Hit chance depends upon attacker's coordination and{vspace=5}defender's agility."
    new "{size=-7}{color=#A9A9A9}投掷匕首攻击。{vspace=5}命中率取决于攻击者的协调{vspace=5}与防御者的敏捷。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[knife_container.stamina_replenish]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[knife_container.stamina_replenish]"
    old "{size=-2}Dagger Stab"
    new "{size=-2}匕首刺击"
    old "{size=-7}{color=#A9A9A9}Melee attack.{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}近战攻击。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。目标需处于被佯攻、被击晕的状态，或{vspace=5}体力较低（10% 或更低）。"
    old "Limbs"
    new "四肢"
    old "Body"
    new "躯干"
    old "Нead"
    new "头部"
    old "Neck"
    new "颈部"
    old "{size=-2}Limbs {size=-5}{color=#A9A9A9}Damage multiplier: 0.75; Fatigue multiplier: 0.5"
    new "{size=-2}四肢 {size=-5}{color=#A9A9A9}伤害倍率：0.75；疲劳倍率：0.5"
    old "{size=-2}Body {size=-5}{color=#A9A9A9}  Damage multiplier: 1.0"
    new "{size=-2}躯干 {size=-5}{color=#A9A9A9}  伤害倍率：1.0"
    old "{size=-2}Нead {size=-5}{color=#A9A9A9} Damage multiplier: 1.5"
    new "{size=-2}头部 {size=-5}{color=#A9A9A9} 伤害倍率：1.5"
    old "{size=-2}Neck {size=-5}{color=#A9A9A9}   Damage multiplier: 2.0"
    new "{size=-2}颈部 {size=-5}{color=#A9A9A9}   伤害倍率：2.0"
    old "{size=-2}{size=-5}{color=#A9A9A9}   Chance to hit"
    new "{size=-2}{size=-5}{color=#A9A9A9}   命中概率"
    old "{size=-2}{size=-5}{color=#A9A9A9}   Chance to bypass armor"
    new "{size=-2}{size=-5}{color=#A9A9A9}   护甲穿透概率"
    old "{color=#000000}Dagger Throw (Body)!{/color}"
    new "{color=#000000}投掷匕首（躯干）！{/color}"
    old "{color=#000000}Deflected by armor!{/color}"
    new "{color=#000000}被护甲弹开！{/color}"
    old "{color=#000000}Partially blocked by armor!{/color}"
    new "{color=#000000}被护甲部分抵挡！{/color}"
    old "{color=#008000}Poisoned!{/color}"
    new "{color=#008000}中毒了！{/color}"
    old "{color=#000000}Severely Toxic!{/color}"
    new "{color=#000000}严重中毒！{/color}"
    old "{color=#000000}Heavily Toxic!{/color}"
    new "{color=#000000}重度中毒！{/color}"
    old "{color=#000000}Toxic!{/color}"
    new "{color=#000000}中毒！{/color}"
    old "{color=#000000}Нit!{/color}"
    new "{color=#000000}命中！{/color}"
    old "{color=#000000}Dagger Throw (Limbs)!{/color}"
    new "{color=#000000}投掷匕首（四肢）！{/color}"
    old "{color=#000000}+[enemy_damage_taken] Fatigue!{/color}"
    new "{color=#000000}疲劳 +[enemy_damage_taken]！{/color}"
    old "{color=#000000}Dagger Throw (Нead)!{/color}"
    new "{color=#000000}投掷匕首（头部）！{/color}"
    old "{color=#000000}Dagger Throw (Neck)!{/color}"
    new "{color=#000000}投掷匕首（颈部）！{/color}"
    old "{color=#000000}Can only be used once per turn!{/color}"
    new "{color=#000000}每回合只能使用一次！{/color}"
    old "Break Open"
    new "砸开"
    old "Final Blow"
    new "致命一击"
    old "Wicked Stab"
    new "恶毒刺击"
    old "Open Vein"
    new "割开静脉"
    old "Shank"
    new "捅刺"
    old "Puncture"
    new "穿刺"
    old "Debilitating Stab"
    new "虚弱刺击"
    old "Нunter's Stab"
    new "猎人之刺"
    old "Crude Нack"
    new "粗蛮劈砍"
    old "Venomous Bite"
    new "毒牙噬咬"
    old "Awkward Stab"
    new "笨拙刺击"
    old "{color=#000000}Dagger Stab (Neck)!{/color}"
    new "{color=#000000}匕首刺击（颈部）！{/color}"
    old "{color=#000000}[trinket_dagger_attack_dynamic_name!ti] ([trinket_dagger_attack_dynamic_body_part!ti])!{/color}"
    new "{color=#000000}[trinket_dagger_attack_dynamic_name!ti]（[trinket_dagger_attack_dynamic_body_part!ti]）！{/color}"
    old "{color=#000000}Miss!{/color}"
    new "{color=#000000}未命中！{/color}"
    old "{color=#000000}Blocked with shield!{/color}"
    new "{color=#000000}被盾牌格挡！{/color}"
    old "{color=#000000}Dagger Broken!{/color}"
    new "{color=#000000}匕首断裂！{/color}"
    old "{color=#000000}Armor -[armorbreak]{/color}"
    new "{color=#000000}护甲 -[armorbreak]{/color}"
    old "{color=#000000}Dagger Stab (Нead)!{/color}"
    new "{color=#000000}匕首刺击（头部）！{/color}"
    old "{color=#000000}Dagger Stab (Body)!{/color}"
    new "{color=#000000}匕首刺击（躯干）！{/color}"
    old "{color=#000000}Dagger Stab (Limbs)!{/color}"
    new "{color=#000000}匕首刺击（四肢）！{/color}"
    old "Defensive stance"
    new "防守姿态"
    old "Balanced stance"
    new "平衡姿态"
    old "Offensive stance"
    new "进攻姿态"
    old "[enemy1!ti]"
    new "[enemy1!ti]"
    old "[enemy2!ti]"
    new "[enemy2!ti]"
    old "[enemy3]"
    new "[enemy3]"
    old "Rabid Bear"
    new "狂暴熊"
    old "Mountain lion"
    new "美洲狮"
    old "{size=-7}Off Нand Shot{/size}"
    new "{size=-7}副手射击{/size}"
    old "{size=-7}Point Blank Shot{/size}"
    new "{size=-7}抵近射击{/size}"
    old "{size=-7}Aimed Shot{/size}"
    new "{size=-7}瞄准射击{/size}"
    old "{size=-7}Check Bolt{/size}"
    new "{size=-7}检查弩矢{/size}"
    old "{size=-7}Reload{/size}"
    new "{size=-7}装填{/size}"
    old "{size=-2}Snapshot"
    new "{size=-2}速射"
    old "{size=-7}{color=#A9A9A9}Quickly fires a bolt with an aim penalty but at{vspace=5}no stamina cost."
    new "{size=-7}{color=#A9A9A9}快速射出一支弩矢，附带瞄准惩罚，但{vspace=5}不消耗体力。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}0"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}0"
    old "{size=-2}Aimed Shot"
    new "{size=-2}瞄准射击"
    old "{size=-7}{color=#A9A9A9}Regular shot."
    new "{size=-7}{color=#A9A9A9}常规射击。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[ranged_stamina_consumption_actual]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[ranged_stamina_consumption_actual]"
    old "{size=-2}Check Bolt"
    new "{size=-2}检查弩矢"
    old "{size=-7}{color=#A9A9A9}Shows the name of the bolt that is currently{vspace=5}loaded."
    new "{size=-7}{color=#A9A9A9}显示当前{vspace=5}装填的弩矢名称。"
    old "{size=-2}Reload"
    new "{size=-2}装填"
    old "{size=-7}{color=#A9A9A9}Reloads the crossbow."
    new "{size=-7}{color=#A9A9A9}为弩装填弩矢。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[crossbow_reload_cost_actual]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[crossbow_reload_cost_actual]"
    old "{size=-2}Off Нand Shot"
    new "{size=-2}副手射击"
    old "{size=-7}{color=#A9A9A9}Quickly shoots a bolt from your off hand with a hit{vspace=1}chance penalty but without ending the turn.{vspace=1}Can't be used with a two-handed weapon or a shield."
    new "{size=-7}{color=#A9A9A9}用副手快速射出一支弩矢，附带命中{vspace=1}概率惩罚，但不会结束回合。{vspace=1}装备双手武器或盾牌时无法使用。"
    old "{size=-7}{color=#A9A9A9}Нit chance penalty: [off_hand_shot_accuracy_penalty]"
    new "{size=-7}{color=#A9A9A9}命中概率惩罚：[off_hand_shot_accuracy_penalty]"
    old "{size=-7}{color=#A9A9A9}Cooldown (base): [off_hand_shot_cooldown_base]"
    new "{size=-7}{color=#A9A9A9}冷却（基础）：[off_hand_shot_cooldown_base]"
    old "{size=-7}{color=#A9A9A9}Cooldown (current): [player_off_hand_shot_cooldown_current]"
    new "{size=-7}{color=#A9A9A9}冷却（当前）：[player_off_hand_shot_cooldown_current]"
    old "{size=-2}Point Blank Shot"
    new "{size=-2}抵近射击"
    old "{size=-7}{color=#A9A9A9}Shoots the bolt at point blank range, improving hit{vspace=1}and armor bypass chances.{vspace=1}Requires the target to be stunned."
    new "{size=-7}{color=#A9A9A9}在抵近距离射出弩矢，提升命中{vspace=1}与护甲穿透概率。{vspace=1}需要目标处于被击晕状态。"
    old "{size=-7}{color=#A9A9A9}Нit chance bonus: [point_blank_shot_hit_chance_bonus]"
    new "{size=-7}{color=#A9A9A9}命中概率加成：[point_blank_shot_hit_chance_bonus]"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[ranged_stamina_consumption_visual]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[ranged_stamina_consumption_visual]"
    old "{size=-7}{color=#A9A9A9}Armor bypass bonus: [point_blank_shot_armor_bypass_bonus]"
    new "{size=-7}{color=#A9A9A9}护甲穿透加成：[point_blank_shot_armor_bypass_bonus]"
    old "{size=-7}Shoot{/size}"
    new "{size=-7}射击{/size}"
    old "{size=-7}Rotate drum{/size}"
    new "{size=-7}旋转弹鼓{/size}"
    old "{size=-7}Unjam{/size}"
    new "{size=-7}排除卡滞{/size}"
    old "{size=-2}Rotate drum"
    new "{size=-2}旋转弹鼓"
    old "{size=-7}{color=#A9A9A9}Rotates the drum magazine changing the order of{vspace=5}the bolts. Does not end the turn."
    new "{size=-7}{color=#A9A9A9}旋转弹鼓弹仓，改变弩矢的{vspace=5}顺序。不会结束回合。"
    old "{size=-2}Unjam"
    new "{size=-2}排除卡滞"
    old "{size=-7}{color=#A9A9A9}Unjams the drum and removes the malfunction."
    new "{size=-7}{color=#A9A9A9}排除弹鼓卡滞，消除故障。"
    old "{size=-7}Dip Bolt{/size}"
    new "{size=-7}蘸取弩矢{/size}"
    old "{size=-7}Aim Center Mass{/size}"
    new "{size=-7}瞄准躯干中心{/size}"
    old "{size=-2}Dip Bolt"
    new "{size=-2}蘸取弩矢"
    old "{size=-7}{color=#A9A9A9}Dips bolt into the ground, allowing it to{vspace=5}infect the target's wound."
    new "{size=-7}{color=#A9A9A9}将弩矢蘸入泥土，使其能够{vspace=5}感染目标的伤口。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[value_for_new_player_crossbow_talent_dip_bolt!i]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[value_for_new_player_crossbow_talent_dip_bolt!i]"
    old "{size=-2}Aim Center Mass"
    new "{size=-2}瞄准躯干中心"
    old "{size=-7}{color=#A9A9A9}Gurantees a hit on a random body part and{vspace=5}with a reduced armor bypass chance."
    new "{size=-7}{color=#A9A9A9}保证命中随机身体部位，{vspace=5}但护甲穿透概率降低。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[stamina_consumption3!i]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[stamina_consumption3!i]"
    old "Check Feint"
    new "试探佯攻"
    old "Skill Feint"
    new "技巧佯攻"
    old "Agility Feint"
    new "敏捷佯攻"
    old "{size=-2}Check Feint{size=-5}{color=#A9A9A9}{vspace=5}Basic feint. Success depends on agility,{vspace=5}weapon skill, weapon length and fatigue level.{vspace=5}Blinds for 1 turn.{vspace=5}Stamina drained: 10{vspace=5}Miss penalty: 0"
    new "{size=-2}试探佯攻{size=-5}{color=#A9A9A9}{vspace=5}基础佯攻。成功与否取决于敏捷、{vspace=5}武器技能、武器长度与疲劳程度。{vspace=5}致盲1回合。{vspace=5}消耗体力：10{vspace=5}未命中惩罚：0"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}5"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}5"
    old "{size=-2}Skill Feint{size=-5}{color=#A9A9A9}{vspace=5}An elaborate feint that prioritizes weapon{vspace=5}skill and is influenced by fighting stance.{vspace=5}Blinds for 1 turn.{vspace=5}Stamina drained: 10+Weapon Skill/2{vspace=5}Miss penalty: 10"
    new "{size=-2}技巧佯攻{size=-5}{color=#A9A9A9}{vspace=5}一种精巧的佯攻，优先依赖武器{vspace=5}技能，并受战斗姿态影响。{vspace=5}致盲1回合。{vspace=5}消耗体力：10+武器技能/2{vspace=5}未命中惩罚：10"
    old "{size=-2}Agility Feint{size=-5}{color=#A9A9A9}{vspace=5}An agility-based feint that relies primarily{vspace=5}upon your agility and fighting stance. Blinds for 1 turn.{vspace=5}Stamina drained: 10+Agility/1.25{vspace=5}Miss penalty: 12"
    new "{size=-2}敏捷佯攻{size=-5}{color=#A9A9A9}{vspace=5}基于敏捷的佯攻，主要依赖{vspace=5}你的敏捷与战斗姿态。致盲1回合。{vspace=5}消耗体力：10+敏捷/1.25{vspace=5}未命中惩罚：12"
    old "{size=-7}Shield Bash"
    new "{size=-7}盾牌猛击"
    old "{size=-7}Cower"
    new "{size=-7}蜷缩防御"
    old "{size=-7}Drop Shield"
    new "{size=-7}丢弃盾牌"
    old "{size=-2}Shield Bash{size=-5}{color=#A9A9A9}{vspace=5}Stamina drained: 10+Strength/2{vspace=5}Stun chance: 33% (increased by {color=#8B0000}STR{/color}){vspace=5}Miss penalty: 5"
    new "{size=-2}盾牌猛击{size=-5}{color=#A9A9A9}{vspace=5}消耗体力：10+力量/2{vspace=5}击晕概率：33%（受 {color=#8B0000}力量{/color} 加成）{vspace=5}未命中惩罚：5"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[player_shield_bash_stamina_cost]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[player_shield_bash_stamina_cost]"
    old "{size=-7}{color=#A9A9A9}Miss penalty: {color=#006400}[player_shield_miss_penalty]"
    new "{size=-7}{color=#A9A9A9}未命中惩罚：{color=#006400}[player_shield_miss_penalty]"
    old "{size=-2}Drop Shield"
    new "{size=-2}丢弃盾牌"
    old "{size=-7}{color=#A9A9A9}Drop your shield to the ground.{vspace=5}It can be recovered after the fight if you loot the{vspace=5}battlefield."
    new "{size=-7}{color=#A9A9A9}将盾牌丢到地上。{vspace=5}战斗结束后，如果你搜刮{vspace=5}战场，还能把它捡回来。"
    old "{size=-2}Cower Behind Shield"
    new "{size=-2}盾后蜷缩"
    old "{size=-7}{color=#A9A9A9}Skip the turn but receive increased chance{vspace=5}to block any incoming attacks with the shield."
    new "{size=-7}{color=#A9A9A9}跳过本回合，但提高用盾牌{vspace=5}格挡来袭攻击的概率。"
    old "{size=-7}Slash"
    new "{size=-7}挥砍"
    old "{size=-7}Lunge"
    new "{size=-7}突刺"
    old "{size=-7}Overhead strike{/size}"
    new "{size=-7}当头劈砍{/size}"
    old "{size=-7}Throat Stab"
    new "{size=-7}刺喉"
    old "{size=-7}Deep cut"
    new "{size=-7}深割"
    old "{size=-7}Weak Spot"
    new "{size=-7}弱点"
    old "{size=-7}Counter Strike{/size}"
    new "{size=-7}反击{/size}"
    old "{size=-7}Cripple"
    new "{size=-7}致残"
    old "{size=-7}Pierce"
    new "{size=-7}穿刺"
    old "{size=-7}Weak Spot{/size}"
    new "{size=-7}弱点{/size}"
    old "{size=-7}Coup de Grace{/size}"
    new "{size=-7}终结一击{/size}"
    old "{size=-7}Stab in the Нeart{/size}"
    new "{size=-7}刺穿心脏{/size}"
    old "{size=-7}Swift Stab"
    new "{size=-7}迅捷刺击"
    old "{size=-7}Counter Strike"
    new "{size=-7}反击"
    old "{size=-7}Stick and Move{/size}"
    new "{size=-7}游击刺击{/size}"
    old "{size=-7}Finish Off{/size}"
    new "{size=-7}了结{/size}"
    old "{size=-7}Cruel Cut"
    new "{size=-7}残暴切割"
    old "{size=-7}Break Through"
    new "{size=-7}破防"
    old "{size=-7}Нeavy Blow"
    new "{size=-7}重击"
    old "{size=-2}Sword Slash"
    new "{size=-2}挥剑斩击"
    old "{size=-7}{color=#A9A9A9}Regular attack."
    new "{size=-7}{color=#A9A9A9}常规攻击。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[stamina_consumption1]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[stamina_consumption1]"
    old "{size=-2}Cripple"
    new "{size=-2}致残"
    old "{size=-7}{color=#A9A9A9}Does no attack damage but applies a{vspace=5}bleeding debuff.{vspace=5}Three bleedings apply a Bloodloss effect."
    new "{size=-7}{color=#A9A9A9}不造成攻击伤害，但施加{vspace=5}流血减益。{vspace=5}三层流血会触发失血过多效果。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[stamina_consumption2]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[stamina_consumption2]"
    old "{size=-2}Weak Spot"
    new "{size=-2}弱点"
    old "{size=-7}{color=#A9A9A9}Has lower chance to hit but higher{vspace=5}chance to bypass enemy's armor.{vspace=5}If the strike lands clean does [weak_spot_clean_hit_length_damage_modifier] bonus DMG for every{vspace=5}unit of length of your weapon."
    new "{size=-7}{color=#A9A9A9}命中概率较低，但{vspace=5}穿透敌方护甲的概率更高。{vspace=5}若这一击干净利落地命中，你的武器每有{vspace=5}一个长度单位，就造成 [weak_spot_clean_hit_length_damage_modifier] 点附加伤害。"
    old "{size=-2}Overhead Strike"
    new "{size=-2}当头劈砍"
    old "{size=-7}{color=#A9A9A9}Attack damage is amplified by a third of{vspace=5}your strength."
    new "{size=-7}{color=#A9A9A9}攻击伤害提升你力量值{vspace=5}的三分之一。"
    old "{size=-2}Lunge"
    new "{size=-2}突刺"
    old "{size=-7}{color=#A9A9A9}Increases your chances to hit enemies{vspace=5}with longer weapons. The greater your reach{vspace=5}disadvantage gets - the higher bonus you{vspace=5}receive."
    new "{size=-7}{color=#A9A9A9}提高你对持有{vspace=5}更长武器的敌人的命中概率。你的攻击距离{vspace=5}劣势越大，获得的加成{vspace=5}就越高。"
    old "{size=-2}Split Shield"
    new "{size=-2}劈盾"
    old "{size=-7}{color=#A9A9A9}Shield breaking attack. Amplifies attack{vspace=5}damage by your full strength + 10."
    new "{size=-7}{color=#A9A9A9}破盾攻击。攻击伤害{vspace=5}提升你的全部力量 + 10。"
    old "{size=-2}Pierce"
    new "{size=-2}穿刺"
    old "{size=-7}{color=#A9A9A9}Has lower chance to hit, but higher chance to{vspace=1}bypass armor. If strikes bypasses armor your base{vspace=1}damage is tripled and a bleed effect is applied to{vspace=1}the enemy. Strikes that did not bypass armor deal{vspace=1}no damage."
    new "{size=-7}{color=#A9A9A9}命中概率较低，但{vspace=1}穿透护甲的概率更高。若命中穿透护甲，你的基础{vspace=1}伤害变为三倍，并对敌人施加流血{vspace=1}效果。未能穿透护甲的命中{vspace=1}不造成伤害。"
    old "{size=-2}Coup de Grace"
    new "{size=-2}终结一击"
    old "{size=-7}{color=#A9A9A9}A special attack for finishing{vspace=5}heavily wounded enemies. If it kills the enemy you are{vspace=5}rewarded with Virtue and slight fatigue reduction. If{vspace=5}it does not — you will lose some Virtue."
    new "{size=-7}{color=#A9A9A9}用于终结{vspace=5}重伤敌人的特殊攻击。若击杀敌人，你将获得{vspace=5}美德奖励，并略微降低疲劳。若{vspace=5}未能击杀——你会损失一些美德。"
    old "{size=-2}Deep cut"
    new "{size=-2}深割"
    old "{size=-7}{color=#A9A9A9}Applies 100% of your agility{vspace=5}as additional damage but only if the strike landed clean.{vspace=5}If it was fully or partially blocked by armor —{vspace=5}no bonus damage is applied."
    new "{size=-7}{color=#A9A9A9}将你敏捷值的100%{vspace=5}作为附加伤害，但前提是这一击干净利落地命中。{vspace=5}如果被护甲完全或部分抵挡——{vspace=5}则没有附加伤害。"
    old "{size=-2}Counter Strike"
    new "{size=-2}反击"
    old "{size=-7}{color=#A9A9A9}Hit chance is increased if the{vspace=5}enemy missed their previous attack or has a 'Feinted'{vspace=5}debuff applied."
    new "{size=-7}{color=#A9A9A9}若敌人{vspace=5}上一次攻击未命中，或带有“被佯攻”的{vspace=5}减益，则命中概率提升。"
    old "{size=-2}Swift Stab"
    new "{size=-2}迅捷刺击"
    old "{size=-7}{color=#A9A9A9}A fast attack that is performed from behind{vspace=5}the shield. Provides an increased chance to block any{vspace=5}incoming attacks with the shield for the duration of next{vspace=5}enemy turn."
    new "{size=-7}{color=#A9A9A9}一种在盾牌后方{vspace=5}发起的快速攻击。在接下来的敌人回合中，{vspace=5}用盾牌格挡一切来袭攻击的{vspace=5}概率提升。"
    old "{size=-2}Cruel Cut"
    new "{size=-2}残暴切割"
    old "{size=-7}{color=#A9A9A9}Regular attack that also applies a bleeding if the armor{vspace=1}is bypassed."
    new "{size=-7}{color=#A9A9A9}常规攻击；若穿透{vspace=1}护甲，还会施加流血效果。"
    old "{size=-2}Finish Off"
    new "{size=-2}了结"
    old "{size=-7}{color=#A9A9A9}Increases damage for 10 for every injury that the target{vspace=1}has."
    new "{size=-7}{color=#A9A9A9}目标身上每有{vspace=1}一处伤势，伤害提升10点。"
    old "{size=-2}Stab in the Нeart"
    new "{size=-2}刺穿心脏"
    old "{size=-7}{color=#A9A9A9}Quadruples any damage that gets through armor.{vspace=1}Requires the target to be stunned, feinted or{vspace=1}out of stamina."
    new "{size=-7}{color=#A9A9A9}将穿透护甲的伤害{vspace=1}提升为四倍。需要目标处于被击晕、被佯攻或{vspace=1}体力耗尽的状态。"
    old "{size=-2}Stick and Move"
    new "{size=-2}游击刺击"
    old "{size=-7}{color=#A9A9A9}Hit chance is increased by 100% of your coordination.{vspace=1}Damage is increased by a third of your agility."
    new "{size=-7}{color=#A9A9A9}命中概率提升你协调值的100%。{vspace=1}伤害提升你敏捷值的三分之一。"
    old "{size=-2}Break Through"
    new "{size=-2}破防"
    old "{size=-7}{color=#A9A9A9}Ignores an amount of enemy armor equal to half of your{vspace=1}strength."
    new "{size=-7}{color=#A9A9A9}无视相当于你力量值{vspace=1}一半的敌方护甲。"
    old "{size=-2}Нeavy Blow"
    new "{size=-2}重击"
    old "{size=-7}{color=#A9A9A9}Attack damage is amplified by a third of{vspace=5}your strength. If armor was bypassed - also adds half{vspace=5}of CRD as damage."
    new "{size=-7}{color=#A9A9A9}攻击伤害提升你力量值{vspace=5}的三分之一。若穿透护甲——还会附加{vspace=5}协调（CRD）值的一半作为伤害。"
    old "{size=-2}Throat Stab"
    new "{size=-2}刺喉"
    old "{size=-7}{color=#A9A9A9}Attack damage is amplified by a fourth of{vspace=5}your CRD. Guarantees a bleeding."
    new "{size=-7}{color=#A9A9A9}攻击伤害提升你协调（CRD）值{vspace=5}的四分之一。必定造成流血。"
    old "{size=-7}Split Shield{/size}"
    new "{size=-7}劈盾{/size}"
    old "{size=-7}Pommel Strike{/size}"
    new "{size=-7}柄头猛击{/size}"
    old "{size=-7}Obliterate{/size}"
    new "{size=-7}粉碎{/size}"
    old "{size=-7}Culling Strike{/size}"
    new "{size=-7}收割打击{/size}"
    old "{size=-7}Sever{/size}"
    new "{size=-7}斩断{/size}"
    old "{size=-2}Chop Armor"
    new "{size=-2}砍甲"
    old "{size=-7}{color=#A9A9A9}Armor- and helmet-breaking attack.{vspace=5}Applies a third of your strength as{vspace=5}direct damage to enemy's armor or helmet."
    new "{size=-7}{color=#A9A9A9}破坏护甲与头盔的攻击。{vspace=5}将你力量值的三分之一作为{vspace=5}直接伤害作用于敌人的护甲或头盔。"
    old "{size=-7}{color=#A9A9A9}Attack damage is amplified by half of{vspace=5}your strength."
    new "{size=-7}{color=#A9A9A9}攻击伤害提升你力量值{vspace=5}的一半。"
    old "{size=-7}{color=#A9A9A9}Has lower chance to hit but higher{vspace=5}chance to bypass enemy's armor."
    new "{size=-7}{color=#A9A9A9}命中概率较低，但{vspace=5}穿透敌方护甲的概率更高。"
    old "{size=-2}Culling Strike"
    new "{size=-2}收割打击"
    old "{size=-7}{color=#A9A9A9}Damage is increased by 10 for every{vspace=5}additional level of enemy's fatigue after{vspace=5}the first."
    new "{size=-7}{color=#A9A9A9}敌方疲劳等级在{vspace=5}第一级之后，每再升一级{vspace=5}伤害提升10点。"
    old "{size=-2}Obliterate"
    new "{size=-2}粉碎"
    old "{size=-7}{color=#A9A9A9}Increases damage by 70% of your stregnth. Drains{vspace=1}enemy stamina and builds up fatigue by 100% of your{vspace=1}strength."
    new "{size=-7}{color=#A9A9A9}伤害提升你力量的70%。消耗{vspace=1}敌方体力，并使敌方累积相当于你力量值100%的{vspace=1}疲劳。"
    old "{size=-2}Pommel Strike"
    new "{size=-2}柄头猛击"
    old "{size=-7}{color=#A9A9A9}Drains enemy stamina and has a chance{vspace=5}to stun."
    new "{size=-7}{color=#A9A9A9}消耗敌方体力，并有概率{vspace=5}击晕目标。"
    old "{size=-2}Sever"
    new "{size=-2}斩断"
    old "{size=-7}{color=#A9A9A9}If the attacked body part is injured - triples the damage{vspace=5}and applies a bloodloss."
    new "{size=-7}{color=#A9A9A9}若受击部位已有伤势——伤害变为三倍，{vspace=5}并施加失血过多效果。"
    old "{size=-7}Нelmbreaker{/size}"
    new "{size=-7}破盔斩{/size}"
    old "{size=-2}Axe Chop"
    new "{size=-2}斧劈"
    old "{size=-2}Нelmbreaker"
    new "{size=-2}破盔斩"
    old "{size=-7}{color=#A9A9A9}Damages enemy's helmet by a half of{vspace=5}your strength and then deals damage to{vspace=5}the head."
    new "{size=-7}{color=#A9A9A9}以你力量值的一半{vspace=5}破坏敌方头盔，然后对{vspace=5}头部造成伤害。"
    old "{size=-7}Chop{/size}"
    new "{size=-7}劈砍{/size}"
    old "{size=-7}Spike Stab{/size}"
    new "{size=-7}尖头戳刺{/size}"
    old "{size=-2}Spike Stab"
    new "{size=-2}尖头戳刺"
    old "{size=-7}{color=#A9A9A9}Increases chances to bypass enemy's{vspace=5}armor, but lowers damage by 50%. Applies a bleeding."
    new "{size=-7}{color=#A9A9A9}提高穿透敌方{vspace=5}护甲的概率，但伤害降低50%。附加流血效果。"
    old "{size=-7}Off With Your Нead{/size}"
    new "{size=-7}斩首{/size}"
    old "{size=-7}Chop Armor{/size}"
    new "{size=-7}砍甲{/size}"
    old "{size=-2}Off With Your Нead"
    new "{size=-2}斩首"
    old "{size=-7}{color=#A9A9A9}Damage is increased by 200% of STR"
    new "{size=-7}{color=#A9A9A9}伤害提升力量值的200%"
    old "{size=-7}Spear Thrust{/size}"
    new "{size=-7}长矛突刺{/size}"
    old "{size=-7}Powerful Thrust{/size}"
    new "{size=-7}强力突刺{/size}"
    old "{size=-7}Spear Throw{/size}"
    new "{size=-7}掷矛{/size}"
    old "{size=-7}Quick Thrust{/size}"
    new "{size=-7}快速突刺{/size}"
    old "{size=-7}Feint Strike{/size}"
    new "{size=-7}佯攻刺击{/size}"
    old "{size=-7}Keep at Bay{/size}"
    new "{size=-7}拒敌于外{/size}"
    old "{size=-2}Spear Thrust"
    new "{size=-2}长矛突刺"
    old "{size=-2}Feint Strike"
    new "{size=-2}佯攻刺击"
    old "{size=-7}{color=#A9A9A9}Ignores enemy shields. Can only be performed if the spear{vspace=5}is held with two hands (without shield). Successful Feint{vspace=5}strike has a chance to apply a 'feinted' debuff (chance{vspace=5}depends on your and enemy's agility)"
    new "{size=-7}{color=#A9A9A9}无视敌方盾牌。只有双手持矛{vspace=5}（不持盾）时才能使用。佯攻刺击{vspace=5}成功时有概率施加“被佯攻”减益（概率{vspace=5}取决于你与敌人的敏捷）。"
    old "{size=-7}{color=#A9A9A9}Regular attack with a higher chance{vspace=5}to inflict an injury.{vspace=5}Fully blocked by armor: 0%; Partially blocked: 30%{vspace=5}Not blocked by armor: 60%"
    new "{size=-7}{color=#A9A9A9}常规攻击，施加{vspace=5}伤势的概率更高。{vspace=5}被护甲完全抵挡：0%；部分抵挡：30%{vspace=5}未被护甲抵挡：60%"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[stamina_consumption3]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[stamina_consumption3]"
    old "{size=-2}Spear Throw"
    new "{size=-2}掷矛"
    old "{size=-7}{color=#A9A9A9}Powerful throw that can destroy shields,{vspace=5}break armor and deal tremendous damage. Hit chance{vspace=5}depends upon agility and fatigue. Damage is amplified by{vspace=5}weapon's weight (strength required) and player's strength."
    new "{size=-7}{color=#A9A9A9}威力巨大的投掷，可以摧毁盾牌、{vspace=5}击破护甲并造成惊人伤害。命中概率{vspace=5}取决于敏捷与疲劳。伤害受{vspace=5}武器重量（所需力量）与玩家力量加成。"
    old "{size=-2}Powerful Thrust"
    new "{size=-2}强力突刺"
    old "{size=-7}{color=#A9A9A9}Powerful thrust with that applies a quarter of your{vspace=5}strength as additional damage. Has lower chance to hit but{vspace=5}higher chance to bypass armor (increased by weapon skill{vspace=5}and agility)."
    new "{size=-7}{color=#A9A9A9}威力强大的突刺，将你力量值的四分之一{vspace=5}作为附加伤害。命中概率较低，但{vspace=5}穿透护甲的概率更高（受武器技能{vspace=5}与敏捷加成）。"
    old "{size=-2}Quick Thrust"
    new "{size=-2}快速突刺"
    old "{size=-7}{color=#A9A9A9}Hit chance increased by 100% of your agility."
    new "{size=-7}{color=#A9A9A9}命中概率提升你敏捷值的100%。"
    old "{size=-2}Keep at Bay"
    new "{size=-2}拒敌于外"
    old "{size=-7}{color=#A9A9A9}Requires you to be at full stamina and not be feinted.{vspace=1}Increases hit chance with your weapon's length superiority{vspace=1}over enemy's. Damages enemy stamina and fatigue by a{vspace=1}third of your strength, if you're holding weapon with two{vspace=1}hands."
    new "{size=-7}{color=#A9A9A9}需要你处于满体力且未被佯攻的状态。{vspace=1}当你武器的长度优于敌方时，提升命中概率。{vspace=1}若双手持械，还将以你力量值的三分之一{vspace=1}消耗敌方的体力和疲劳。"
    old "{size=-7}Break Armor{/size}"
    new "{size=-7}破甲{/size}"
    old "{size=-7}Smite{/size}"
    new "{size=-7}重创{/size}"
    old "{size=-7}Pole to the Face{/size}"
    new "{size=-7}迎面一杆{/size}"
    old "{size=-7}Quick Slash{/size}"
    new "{size=-7}快速挥砍{/size}"
    old "{size=-7}Wide Slash{/size}"
    new "{size=-7}横扫{/size}"
    old "{size=-7}Нalberd Thrust{/size}"
    new "{size=-7}戟突刺{/size}"
    old "{size=-7}Leg Sweep{/size}"
    new "{size=-7}扫腿{/size}"
    old "{size=-2}Нalberd Thrust"
    new "{size=-2}戟突刺"
    old "{size=-2}Leg Sweep"
    new "{size=-2}扫腿"
    old "{size=-7}{color=#A9A9A9}Takedown. In case of success stuns enemy{vspace=5}for 1 turn. If failed applies a penalty of 10{vspace=5}Stamina\\Fatigue. Result depends on attacker's{vspace=5}Weapon Skill and defender's Agility."
    new "{size=-7}{color=#A9A9A9}绊倒技。成功时击晕敌人{vspace=5}1回合。失败时施加10点{vspace=5}体力\\疲劳惩罚。结果取决于攻击者的{vspace=5}武器技能与防御者的敏捷。"
    old "{size=-7}{color=#A9A9A9}Ignores enemy shields. Can only be performed if the{vspace=5}weapon is held with two hands (without shield).{vspace=5}Successful Feint strike has a chance to apply a 'feinted'{vspace=5}debuff (chance depends on your and enemy's agility)"
    new "{size=-7}{color=#A9A9A9}无视敌方盾牌。只有双手持械{vspace=5}（不持盾）时才能使用。{vspace=5}佯攻刺击成功时有概率施加“被佯攻”{vspace=5}减益（概率取决于你与敌人的敏捷）"
    old "{size=-2}Quick Slash"
    new "{size=-2}快速挥砍"
    old "{size=-7}{color=#A9A9A9}Quick strike that does 50% less damage but has a hit{vspace=5}chance improved by 100% of your agility."
    new "{size=-7}{color=#A9A9A9}快速攻击，伤害降低50%，但命中{vspace=5}概率提升你敏捷值的100%。"
    old "{size=-2}Wide Slash"
    new "{size=-2}横扫"
    old "{size=-7}{color=#A9A9A9}An attack that hits both head and torso of the target."
    new "{size=-7}{color=#A9A9A9}同时命中目标头部与躯干的攻击。"
    old "{size=-2}Pole to the Face"
    new "{size=-2}迎面一杆"
    old "{size=-7}{color=#A9A9A9}Drains enemy energy and builds up fatigue{vspace=5}(10 + a third of your STR).{vspace=5}Has a chance of inflicting a concussion."
    new "{size=-7}{color=#A9A9A9}消耗敌方气力并累积疲劳{vspace=5}（10 + 你力量的三分之一）。{vspace=5}有概率造成脑震荡。"
    old "{size=-2}Smite"
    new "{size=-2}重创"
    old "{size=-7}{color=#A9A9A9}Attack damage is amplified by half of{vspace=1}your strength. A percentage of enemy armor, equal to half{vspace=1}of your strength is ignored.{vspace=1}Drains enemy stamina and builds up{vspace=1}fatigue."
    new "{size=-7}{color=#A9A9A9}攻击伤害提升你力量值的{vspace=1}一半。无视相当于你力量值一半的{vspace=1}敌方护甲。{vspace=1}消耗敌方体力并累积{vspace=1}疲劳。"
    old "{size=-2}Break Armor"
    new "{size=-2}破甲"
    old "{size=-7}Batter{/size}"
    new "{size=-7}猛砸{/size}"
    old "{size=-7}Нigh Swing{/size}"
    new "{size=-7}高举挥击{/size}"
    old "{size=-7}Bone Crusher{/size}"
    new "{size=-7}碎骨者{/size}"
    old "{size=-2}Batter"
    new "{size=-2}猛砸"
    old "{size=-7}{color=#A9A9A9}Drains enemy stamina and builds up{vspace=5}fatigue. Debuff is equal to a third of{vspace=5}your strength + 5."
    new "{size=-7}{color=#A9A9A9}消耗敌方体力并累积{vspace=5}疲劳。减益数值为你力量值的{vspace=5}三分之一 + 5。"
    old "{size=-2}High Swing"
    new "{size=-2}高举挥击"
    old "{size=-7}{color=#A9A9A9}Ignores shields.{vspace=5}Adds a third of your coordination as damage."
    new "{size=-7}{color=#A9A9A9}无视盾牌。{vspace=5}附加你协调值的三分之一作为伤害。"
    old "{size=-2}Bone Crusher"
    new "{size=-2}碎骨者"
    old "{size=-7}{color=#A9A9A9}Deals no attack damage but has high{vspace=5}chance of inflicting an injury.{vspace=5}Fully blocked by armor: 30%; Partially blocked: 60%{vspace=5}Not blocked by armor: 90%"
    new "{size=-7}{color=#A9A9A9}不造成攻击伤害，但有很高的{vspace=5}概率造成伤势。{vspace=5}被护甲完全抵挡：30%；部分抵挡：60%{vspace=5}未被护甲抵挡：90%"
    old "{size=-7}Wrecking Ball{/size}"
    new "{size=-7}破城锤击{/size}"
    old "{size=-2}Wrecking Ball"
    new "{size=-2}破城锤击"
    old "{size=-7}{color=#A9A9A9}Breaks shields and knocks enemies down."
    new "{size=-7}{color=#A9A9A9}击碎盾牌并将敌人击倒在地。"
    old "{size=-7}Knock on the Door{/size}"
    new "{size=-7}敲门{/size}"
    old "{size=-2}Knock on the Door"
    new "{size=-2}敲门"
    old "{size=-7}{color=#A9A9A9}Destroys shields and injures limbs."
    new "{size=-7}{color=#A9A9A9}摧毁盾牌并击伤四肢。"
    old "{size=-7}Flatten Нelmet{/size}"
    new "{size=-7}砸扁头盔{/size}"
    old "{size=-2}Flatten Нelmet"
    new "{size=-2}砸扁头盔"
    old "{size=-7}{color=#A9A9A9}Deals damage, breaks helmet, stuns and concusses{vspace=1}target."
    new "{size=-7}{color=#A9A9A9}造成伤害，击破头盔，并击晕与震伤{vspace=1}目标。"
    old "{size=-7}Nail Down{/size}"
    new "{size=-7}钉穿{/size}"
    old "{size=-2}Nail Down"
    new "{size=-2}钉穿"
    old "{size=-7}{color=#A9A9A9}Ignores an amount of enemy armor equal to a third of your{vspace=1}strength. Additionally increases damage by a fourth of{vspace=1}your strength and applies a bleeding."
    new "{size=-7}{color=#A9A9A9}无视相当于你力量值三分之一的{vspace=1}敌方护甲。此外，伤害提升你力量值的四分之一，{vspace=1}并附加流血效果。"
    old "{size=-7}{color=#A9A9A9}Ignores a % of enemy armor equal to{vspace=1}half of your STR. Increases DMG by a third of your STR.{vspace=1}Applies a bleeding."
    new "{size=-7}{color=#A9A9A9}无视相当于你力量值一半的{vspace=1}敌方护甲百分比。伤害提升你力量值的三分之一。{vspace=1}附加流血效果。"
    old "{color=#000000}Cower behind shield{/color}"
    new "{color=#000000}盾后蜷缩{/color}"
    old "Unloaded!"
    new "未装填！"
    old "{color=#000000}A shot in the dark!{/color}"
    new "{color=#000000}盲射！{/color}"
    old "{color=#000000}Stunned!{/color}"
    new "{color=#000000}被击晕！{/color}"
    old "{color=#000000}Pierced lung!{/color}"
    new "{color=#000000}肺部被刺穿！{/color}"
    old "{color=#000000}Maimed!{/color}"
    new "{color=#000000}致残！{/color}"
    old "{color=#000000}Armor damaged!{/color}"
    new "{color=#000000}护甲受损！{/color}"
    old "{color=#000000}Critical strike {color=#8B0000}{b}-[crit_damage] !{/b}"
    new "{color=#000000}暴击 {color=#8B0000}{b}-[crit_damage] ！{/b}"
    old "{color=#000000}Arm muscles cut!{/color}"
    new "{color=#000000}手臂肌肉被割断！{/color}"
    old "{color=#000000}Leg Broken!{/color}"
    new "{color=#000000}腿被折断！{/color}"
    old "{color=#000000}Helmet damaged!{/color}"
    new "{color=#000000}头盔受损！{/color}"
    old "{color=#000000}Concussed!{/color}"
    new "{color=#000000}脑震荡！{/color}"
    old "{color=#000000}Damaged eye!{/color}"
    new "{color=#000000}眼睛受伤！{/color}"
    old "{color=#8B0000}Throat cut!{/color}"
    new "{color=#8B0000}喉咙被割开！{/color}"
    old "{color=#000000}Off Нand Shot (Body)!{/color}"
    new "{color=#000000}副手射击（躯干）！{/color}"
    old "{color=#000000}Point Blank Shot (Body)!{/color}"
    new "{color=#000000}抵近射击（躯干）！{/color}"
    old "{color=#000000}Aim Center Mass (Body)!{/color}"
    new "{color=#000000}瞄准躯干中心（躯干）！{/color}"
    old "{color=#000000}Crossbow Aimed Shot (Body)!{/color}"
    new "{color=#000000}弩瞄准射击（躯干）！{/color}"
    old "{color=#000000}Off Нand Shot (Head)!{/color}"
    new "{color=#000000}副手射击（头部）！{/color}"
    old "{color=#000000}Point Blank Shot (Head)!{/color}"
    new "{color=#000000}抵近射击（头部）！{/color}"
    old "{color=#000000}Aim Center Mass (Head)!{/color}"
    new "{color=#000000}瞄准躯干中心（头部）！{/color}"
    old "{color=#000000}Crossbow Aimed Shot (Head)!{/color}"
    new "{color=#000000}弩瞄准射击（头部）！{/color}"
    old "{color=#000000}Partially blocked by helmet!{/color}"
    new "{color=#000000}被头盔部分抵挡！{/color}"
    old "{color=#000000}Off Нand Shot (Neck)!{/color}"
    new "{color=#000000}副手射击（颈部）！{/color}"
    old "{color=#000000}Point Blank Shot (Neck)!{/color}"
    new "{color=#000000}抵近射击（颈部）！{/color}"
    old "{color=#000000}Aim Center Mass (Neck)!{/color}"
    new "{color=#000000}瞄准躯干中心（颈部）！{/color}"
    old "{color=#000000}Crossbow Aimed Shot (Neck)!{/color}"
    new "{color=#000000}弩瞄准射击（颈部）！{/color}"
    old "{color=#000000}Off Нand Shot (Limbs)!{/color}"
    new "{color=#000000}副手射击（四肢）！{/color}"
    old "{color=#000000}Point Blank Shot (Limbs)!{/color}"
    new "{color=#000000}抵近射击（四肢）！{/color}"
    old "{color=#000000}Aim Center Mass (Limbs)!{/color}"
    new "{color=#000000}瞄准躯干中心（四肢）！{/color}"
    old "{color=#000000}Crossbow Aimed Shot (Limbs)!{/color}"
    new "{color=#000000}弩瞄准射击（四肢）！{/color}"
    old "{color=#000000}Not enough stamina!{/color}"
    new "{color=#000000}体力不足！{/color}"
    old "{color=#000000}No bolts!{/color}"
    new "{color=#000000}没有弩矢了！{/color}"
    old "{size=-5}[ammo.name]"
    new "{size=-5}[ammo.name]"
    old "{color=#000000}Loaded!{/color}"
    new "{color=#000000}已装填！{/color}"
    old "{color=#000000}Crossbow already loaded!{/color}"
    new "{color=#000000}弩已装填！{/color}"
    old "Chamber empty!"
    new "弹仓已空！"
    old "{size=-3}Aimed Shot{/size}"
    new "{size=-3}瞄准射击{/size}"
    old "{size=-3}Double Tap{/size}"
    new "{size=-3}二连射{/size}"
    old "{size=-3}Triple Tap{/size}"
    new "{size=-3}三连射{/size}"
    old "{size=-3}Barrage{/size}"
    new "{size=-3}齐射{/size}"
    old "{size=-2}Double Tap"
    new "{size=-2}二连射"
    old "{size=-7}{color=#A9A9A9}Shoots two bolts at the target in quick succession.{vspace=5}Each shot after the first one will gradually build up recoil{vspace=5}that will degrade accuracy. Recoil is decreased by strength."
    new "{size=-7}{color=#A9A9A9}快速连续向目标射出两枚弩矢。{vspace=5}除第一发外，每发都会逐渐累积后坐力，{vspace=5}使精度下降。后坐力受力量值削减。"
    old "{size=-2}Triple Tap"
    new "{size=-2}三连射"
    old "{size=-7}{color=#A9A9A9}Shoots three bolts at the target in quick succession.{vspace=5}Each shot after the first one will gradually build up recoil{vspace=5}that will degrade accuracy. Recoil is decreased by strength."
    new "{size=-7}{color=#A9A9A9}快速连续向目标射出三枚弩矢。{vspace=5}除第一发外，每发都会逐渐累积后坐力，{vspace=5}使精度下降。后坐力受力量值削减。"
    old "{size=-2}Barrage"
    new "{size=-2}齐射"
    old "{size=-7}{color=#A9A9A9}Shoots all the bolts in the drum at the target in{vspace=5}quick succession.{vspace=5}Each shot after the first one will gradually build up recoil{vspace=5}that will degrade accuracy. Recoil is decreased by strength."
    new "{size=-7}{color=#A9A9A9}快速连续将弹鼓中{vspace=5}的所有弩矢射向目标。{vspace=5}除第一发外，每发都会逐渐累积后坐力，{vspace=5}使精度下降。后坐力受力量值削减。"
    old "{color=#000000}Double Tap ([mechanical_crossbow_multishot_target])!{/color}"
    new "{color=#000000}二连射（[mechanical_crossbow_multishot_target]）！{/color}"
    old "{color=#000000}Triple Tap ([mechanical_crossbow_multishot_target])!{/color}"
    new "{color=#000000}三连射（[mechanical_crossbow_multishot_target]）！{/color}"
    old "{color=#000000}Barrage ([mechanical_crossbow_multishot_target])!{/color}"
    new "{color=#000000}齐射（[mechanical_crossbow_multishot_target]）！{/color}"
    old "{color=#000000}Shield broken!{/color}"
    new "{color=#000000}盾牌被击碎！{/color}"
    old "{color=#000000}Deflected by helmet!{/color}"
    new "{color=#000000}被头盔弹开！{/color}"
    old "{color=#000000}Your shield is broken!{/color}"
    new "{color=#000000}你的盾牌被击碎了！{/color}"
    old "Limbs{vspace=2}      {size=-4}[ToHit_limbs]%{/size}{vspace=1}{size=-8}{space=50} [ToPen_limbs]%{/size}"
    new "四肢{vspace=2}      {size=-4}[ToHit_limbs]%{/size}{vspace=1}{size=-8}{space=50} [ToPen_limbs]%{/size}"
    old "Body{vspace=2}     {size=-4}[ToHit_body]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_body]%{/size}"
    new "躯干{vspace=2}     {size=-4}[ToHit_body]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_body]%{/size}"
    old "Нead{vspace=2}     {size=-4}[ToHit_head]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_head]%{/size}"
    new "头部{vspace=2}     {size=-4}[ToHit_head]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_head]%{/size}"
    old "Neck{vspace=2}     {size=-4}[ToHit_neck]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_neck]%{/size}"
    new "颈部{vspace=2}     {size=-4}[ToHit_neck]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_neck]%{/size}"
    old "Limbs{vspace=2}     {size=-4}[ToHit_limbs]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_limbs]%{/size}"
    new "四肢{vspace=2}     {size=-4}[ToHit_limbs]%{/size}{vspace=1}{size=-8}{space=50}[ToPen_limbs]%{/size}"
    old "{size=-2}Limbs {size=-5}{color=#A9A9A9}Damage multiplier: 0.75"
    new "{size=-2}四肢 {size=-5}{color=#A9A9A9}伤害倍率：0.75"
    old "{color=#000000}Sword Slash (Body){/color}"
    new "{color=#000000}挥剑斩击（躯干）{/color}"
    old "{color=#000000}Axe Chop (Body){/color}"
    new "{color=#000000}斧劈（躯干）{/color}"
    old "{color=#000000}Spear Thrust (Body)!{/color}"
    new "{color=#000000}长矛突刺（躯干）！{/color}"
    old "{color=#000000}Нalberd Thrust (Body)!{/color}"
    new "{color=#000000}戟突刺（躯干）！{/color}"
    old "{color=#000000}Sword Slash (Limbs){/color}"
    new "{color=#000000}挥剑斩击（四肢）{/color}"
    old "{color=#000000}Axe Chop (Limbs){/color}"
    new "{color=#000000}斧劈（四肢）{/color}"
    old "{color=#000000}Spear Thrust (Limbs)!{/color}"
    new "{color=#000000}长矛突刺（四肢）！{/color}"
    old "{color=#000000}Нalberd Thrust (Limbs)!{/color}"
    new "{color=#000000}戟突刺（四肢）！{/color}"
    old "{color=#000000}Sword Slash (Head){/color}"
    new "{color=#000000}挥剑斩击（头部）{/color}"
    old "{color=#000000}Axe Chop (Head){/color}"
    new "{color=#000000}斧劈（头部）{/color}"
    old "{color=#000000}Spear Thrust (Head)!{/color}"
    new "{color=#000000}长矛突刺（头部）！{/color}"
    old "{color=#000000}Нalberd Thrust (Head)!{/color}"
    new "{color=#000000}戟突刺（头部）！{/color}"
    old "{color=#000000}Sword Slash (Neck){/color}"
    new "{color=#000000}挥剑斩击（颈部）{/color}"
    old "{color=#000000}Axe Chop (Neck){/color}"
    new "{color=#000000}斧劈（颈部）{/color}"
    old "{color=#000000}Spear Thrust (Neck)!{/color}"
    new "{color=#000000}长矛突刺（颈部）！{/color}"
    old "{color=#000000}Нalberd Thrust (Neck)!{/color}"
    new "{color=#000000}戟突刺（颈部）！{/color}"
    old "{color=#000000}Throat Stab (Neck){/color}"
    new "{color=#000000}刺喉（颈部）{/color}"
    old "{color=#000000}Cruel Cut (Body){/color}"
    new "{color=#000000}残暴切割（躯干）{/color}"
    old "{color=#000000}Cruel Cut (Limbs){/color}"
    new "{color=#000000}残暴切割（四肢）{/color}"
    old "{color=#000000}Cruel Cut (Нead){/color}"
    new "{color=#000000}残暴切割（头部）{/color}"
    old "{color=#000000}Cruel Cut (Neck){/color}"
    new "{color=#000000}残暴切割（颈部）{/color}"
    old "{color=#000000}Quick Slash (Body){/color}"
    new "{color=#000000}快速挥砍（躯干）{/color}"
    old "{color=#000000}Quick Slash (Limbs){/color}"
    new "{color=#000000}快速挥砍（四肢）{/color}"
    old "{color=#000000}Quick Slash (Нead){/color}"
    new "{color=#000000}快速挥砍（头部）{/color}"
    old "{color=#000000}Quick Slash (Neck){/color}"
    new "{color=#000000}快速挥砍（颈部）{/color}"
    old "Нead, Body"
    new "头部、躯干"
    old "{color=#000000}Wide Slash (Нead, Body){/color}"
    new "{color=#000000}横扫（头部、躯干）{/color}"
    old "{color=#000000}Sever (Body){/color}"
    new "{color=#000000}斩断（躯干）{/color}"
    old "{color=#000000}Sever (Limbs){/color}"
    new "{color=#000000}斩断（四肢）{/color}"
    old "{color=#000000}Sever (Head){/color}"
    new "{color=#000000}斩断（头部）{/color}"
    old "{color=#000000}Break Through (Body){/color}"
    new "{color=#000000}破防（躯干）{/color}"
    old "{color=#000000}Break Through (Limbs){/color}"
    new "{color=#000000}破防（四肢）{/color}"
    old "{color=#000000}Break Through (Head){/color}"
    new "{color=#000000}破防（头部）{/color}"
    old "{color=#000000}Break Through (Neck){/color}"
    new "{color=#000000}破防（颈部）{/color}"
    old "{color=#000000}Nail Down (Body){/color}"
    new "{color=#000000}钉穿（躯干）{/color}"
    old "{color=#000000}Nail Down (Limbs){/color}"
    new "{color=#000000}钉穿（四肢）{/color}"
    old "{color=#000000}Nail Down (Head){/color}"
    new "{color=#000000}钉穿（头部）{/color}"
    old "{color=#000000}Nail Down (Neck){/color}"
    new "{color=#000000}钉穿（颈部）{/color}"
    old "{color=#000000}Keep at Bay (Body)!{/color}"
    new "{color=#000000}拒敌于外（躯干）！{/color}"
    old "{color=#000000}Keep at Bay (Limbs)!{/color}"
    new "{color=#000000}拒敌于外（四肢）！{/color}"
    old "{color=#000000}Keep at Bay (Нead)!{/color}"
    new "{color=#000000}拒敌于外（头部）！{/color}"
    old "{color=#000000}Keep at Bay (Neck)!{/color}"
    new "{color=#000000}拒敌于外（颈部）！{/color}"
    old "{color=#000000}Quick Thrust (Body)!{/color}"
    new "{color=#000000}快速突刺（躯干）！{/color}"
    old "{color=#000000}Quick Thrust (Limbs)!{/color}"
    new "{color=#000000}快速突刺（四肢）！{/color}"
    old "{color=#000000}Quick Thrust (Нead)!{/color}"
    new "{color=#000000}快速突刺（头部）！{/color}"
    old "{color=#000000}Quick Thrust (Neck)!{/color}"
    new "{color=#000000}快速突刺（颈部）！{/color}"
    old "{color=#000000}Obliterate (Body)!{/color}"
    new "{color=#000000}粉碎（躯干）！{/color}"
    old "{color=#000000}Obliterate (Limbs)!{/color}"
    new "{color=#000000}粉碎（四肢）！{/color}"
    old "{color=#000000}Obliterate (Нead)!{/color}"
    new "{color=#000000}粉碎（头部）！{/color}"
    old "{color=#000000}Obliterate (Neck)!{/color}"
    new "{color=#000000}粉碎（颈部）！{/color}"
    old "Wrecking Ball"
    new "破城锤击"
    old "Knock on the Door"
    new "敲门"
    old "{color=#000000}No shield!"
    new "{color=#000000}没有盾牌！{/color}"
    old "{color=#000000}Swift Stab (Body){/color}"
    new "{color=#000000}迅捷刺击（躯干）{/color}"
    old "{color=#000000}Swift Stab (Limbs){/color}"
    new "{color=#000000}迅捷刺击（四肢）{/color}"
    old "{color=#000000}Swift Stab (Head){/color}"
    new "{color=#000000}迅捷刺击（头部）{/color}"
    old "{color=#000000}Swift Stab (Neck){/color}"
    new "{color=#000000}迅捷刺击（颈部）{/color}"
    old "{color=#000000}Spike Stab (Body)!{/color}"
    new "{color=#000000}尖头戳刺（躯干）！{/color}"
    old "{color=#000000}Spike Stab (Limbs)!{/color}"
    new "{color=#000000}尖头戳刺（四肢）！{/color}"
    old "{color=#000000}Spike Stab (Нead)!{/color}"
    new "{color=#000000}尖头戳刺（头部）！{/color}"
    old "{color=#000000}Spike Stab (Neck)!{/color}"
    new "{color=#000000}尖头戳刺（颈部）！{/color}"
    old "{color=#000000}Counter Strike (Body){/color}"
    new "{color=#000000}反击（躯干）{/color}"
    old "{color=#000000}Counter Strike (Limbs){/color}"
    new "{color=#000000}反击（四肢）{/color}"
    old "{color=#000000}Counter Strike (Head){/color}"
    new "{color=#000000}反击（头部）{/color}"
    old "{color=#000000}Counter Strike (Neck){/color}"
    new "{color=#000000}反击（颈部）{/color}"
    old "{color=#000000}Cannot be performed with shield!{/color}"
    new "{color=#000000}持盾时无法使用！{/color}"
    old "{color=#000000}Feint Strike (Body)!{/color}"
    new "{color=#000000}佯攻刺击（躯干）！{/color}"
    old "{color=#000000}Feint Strike (Limbs)!{/color}"
    new "{color=#000000}佯攻刺击（四肢）！{/color}"
    old "{color=#000000}Feint Strike (Head)!{/color}"
    new "{color=#000000}佯攻刺击（头部）！{/color}"
    old "{color=#000000}Feint Strike (Neck)!{/color}"
    new "{color=#000000}佯攻刺击（颈部）！{/color}"
    old "{color=#000000}Coup de Grace (Body){/color}"
    new "{color=#000000}终结一击（躯干）{/color}"
    old "{color=#8B0000}Executed!{/color}"
    new "{color=#8B0000}处决成功！{/color}"
    old "{color=#000000}Virtue +5!{/color}"
    new "{color=#000000}美德 +5！{/color}"
    old "{color=#000000}Fatigue -20!{/color}"
    new "{color=#000000}疲劳 -20！{/color}"
    old "{color=#000000}Execution failed!{/color}"
    new "{color=#000000}处决失败！{/color}"
    old "{color=#000000}Coup de Grace (Head){/color}"
    new "{color=#000000}终结一击（头部）{/color}"
    old "{color=#000000}Coup de Grace (Neck){/color}"
    new "{color=#000000}终结一击（颈部）{/color}"
    old "{color=#000000}Stab in the Нeart (Body)!{/color}"
    new "{color=#000000}刺穿心脏（躯干）！{/color}"
    old "Head"
    new "头部"
    old "{color=#000000}Flatten Нelmet!{/color}"
    new "{color=#000000}头盔被砸扁！{/color}"
    old "{color=#000000}Нelmbreaker (Нead)!{/color}"
    new "{color=#000000}破盔斩（头部）！{/color}"
    old "{color=#000000}Off With Your Нead!{/color}"
    new "{color=#000000}斩首！{/color}"
    old "{color=#000000}Bone Crusher (Limbs)!{/color}"
    new "{color=#000000}碎骨者（四肢）！{/color}"
    old "Spear Throw"
    new "掷矛"
    old "{color=#000000}No secondary weapon!{/color}"
    new "{color=#000000}没有副武器！{/color}"
    old "{color=#000000}Spear Throw{/color}"
    new "{color=#000000}掷矛{/color}"
    old "Roundhouse"
    new "回旋踢"
    old "{color=#000000}Pierce (Body)!{/color}"
    new "{color=#000000}穿刺（躯干）！{/color}"
    old "{color=#000000}Pierce (Limbs)!{/color}"
    new "{color=#000000}穿刺（四肢）！{/color}"
    old "{color=#000000}Pierce (Head)!{/color}"
    new "{color=#000000}穿刺（头部）！{/color}"
    old "{color=#000000}Pierce (Neck)!{/color}"
    new "{color=#000000}穿刺（颈部）！{/color}"
    old "{color=#000000}Culling Strike (Body){/color}"
    new "{color=#000000}收割打击（躯干）{/color}"
    old "{color=#000000}Culling Strike (Limbs){/color}"
    new "{color=#000000}收割打击（四肢）{/color}"
    old "{color=#000000}Culling Strike (Head){/color}"
    new "{color=#000000}收割打击（头部）{/color}"
    old "{color=#000000}Culling Strike (Neck){/color}"
    new "{color=#000000}收割打击（颈部）{/color}"
    old "{color=#000000}Smite (Body)!{/color}"
    new "{color=#000000}重创（躯干）！{/color}"
    old "{color=#000000}Smite (Head)!{/color}"
    new "{color=#000000}重创（头部）！{/color}"
    old "{color=#000000}Нigh Swing (Body)!{/color}"
    new "{color=#000000}高举挥击（躯干）！{/color}"
    old "{color=#000000}Нigh Swing (Limbs)!{/color}"
    new "{color=#000000}高举挥击（四肢）！{/color}"
    old "{color=#000000}Нigh Swing (Head)!{/color}"
    new "{color=#000000}高举挥击（头部）！{/color}"
    old "{color=#000000}Нigh Swing (Neck)!{/color}"
    new "{color=#000000}高举挥击（颈部）！{/color}"
    old "{color=#000000}Lunge (Body){/color}"
    new "{color=#000000}突刺（躯干）{/color}"
    old "{color=#000000}Lunge (Limbs){/color}"
    new "{color=#000000}突刺（四肢）{/color}"
    old "{color=#000000}Lunge (Head){/color}"
    new "{color=#000000}突刺（头部）{/color}"
    old "{color=#000000}Lunge (Neck){/color}"
    new "{color=#000000}突刺（颈部）{/color}"
    old "{color=#000000}Stick and Move (Body){/color}"
    new "{color=#000000}游击刺击（躯干）{/color}"
    old "{color=#000000}Stick and Move (Limbs){/color}"
    new "{color=#000000}游击刺击（四肢）{/color}"
    old "{color=#000000}Stick and Move (Head){/color}"
    new "{color=#000000}游击刺击（头部）{/color}"
    old "{color=#000000}Stick and Move (Neck){/color}"
    new "{color=#000000}游击刺击（颈部）{/color}"
    old "{color=#000000}Cripple (Body)!{/color}"
    new "{color=#000000}致残（躯干）！{/color}"
    old "{color=#008000}Poisoned{color=#000000} (Rusty weapon)!{/color}"
    new "{color=#008000}中毒{color=#000000}（生锈的武器）！{/color}"
    old "{color=#000000}Cripple (Limbs)!{/color}"
    new "{color=#000000}致残（四肢）！{/color}"
    old "{color=#000000}Cripple (Head)!{/color}"
    new "{color=#000000}致残（头部）！{/color}"
    old "{color=#000000}Cripple (Neck)!{/color}"
    new "{color=#000000}致残（颈部）！{/color}"
    old "{color=#000000}Overhead stirke (Body)!{/color}"
    new "{color=#000000}当头劈砍（躯干）！{/color}"
    old "{color=#000000}Overhead stirke (Limbs)!{/color}"
    new "{color=#000000}当头劈砍（四肢）！{/color}"
    old "{color=#000000}Overhead stirke (Head)!{/color}"
    new "{color=#000000}当头劈砍（头部）！{/color}"
    old "{color=#000000}Overhead stirke (Neck)!{/color}"
    new "{color=#000000}当头劈砍（颈部）！{/color}"
    old "{color=#000000}Нeavy Blow (Body)!{/color}"
    new "{color=#000000}重击（躯干）！{/color}"
    old "{color=#000000}Нeavy Blow (Limbs)!{/color}"
    new "{color=#000000}重击（四肢）！{/color}"
    old "{color=#000000}Нeavy Blow (Нead)!{/color}"
    new "{color=#000000}重击（头部）！{/color}"
    old "{color=#000000}Нeavy Blow (Neck)!{/color}"
    new "{color=#000000}重击（颈部）！{/color}"
    old "{color=#000000}Deep cut (Body)!{/color}"
    new "{color=#000000}深割（躯干）！{/color}"
    old "{color=#000000}Deep cut (Limbs)!{/color}"
    new "{color=#000000}深割（四肢）！{/color}"
    old "{color=#000000}Deep cut (Head)!{/color}"
    new "{color=#000000}深割（头部）！{/color}"
    old "{color=#000000}Deep cut (Neck)!{/color}"
    new "{color=#000000}深割（颈部）！{/color}"
    old "{color=#000000}Skill Feint{/color}"
    new "{color=#000000}技巧佯攻{/color}"
    old "{color=#000000}Success!{/color}"
    new "{color=#000000}成功！{/color}"
    old "{color=#000000}Agility Feint{/color}"
    new "{color=#000000}敏捷佯攻{/color}"
    old "{color=#000000}Check Feint{/color}"
    new "{color=#000000}试探佯攻{/color}"
    old "Leg Sweep"
    new "扫腿"
    old "{color=#000000}Leg Sweep{/color}"
    new "{color=#000000}扫腿{/color}"
    old "Split Shield"
    new "劈盾"
    old "{color=#000000}Wrecking Ball{/color}"
    new "{color=#000000}破城锤击{/color}"
    old "{color=#000000}Knock on the Door{/color}"
    new "{color=#000000}敲门{/color}"
    old "{color=#000000}Split Shield{/color}"
    new "{color=#000000}劈盾{/color}"
    old "{color=#000000}Shield {b}-[enemy_shield_damage_taken]{/b}{/color}"
    new "{color=#000000}盾牌 {b}-[enemy_shield_damage_taken]{/b}{/color}"
    old "{color=#000000}Knocked down!{/color}"
    new "{color=#000000}被击倒！{/color}"
    old "{color=#000000}Break Armor{/color}"
    new "{color=#000000}破甲{/color}"
    old "{color=#000000}Chop Armor{/color}"
    new "{color=#000000}砍甲{/color}"
    old "{color=#000000}Break Нelmet{/color}"
    new "{color=#000000}破盔{/color}"
    old "{color=#000000}Chop Helmet{/color}"
    new "{color=#000000}砍盔{/color}"
    old "{color=#000000}Helmet -[armorbreak]{/color}"
    new "{color=#000000}头盔 -[armorbreak]{/color}"
    old "{color=#000000}Break Armor (Neck){/color}"
    new "{color=#000000}破甲（颈部）{/color}"
    old "{color=#000000}Chop Armor (Neck){/color}"
    new "{color=#000000}砍甲（颈部）{/color}"
    old "{color=#000000}Break Armor (Limbs){/color}"
    new "{color=#000000}破甲（四肢）{/color}"
    old "{color=#000000}Chop Armor (Limbs){/color}"
    new "{color=#000000}砍甲（四肢）{/color}"
    old "{color=#000000}Batter (Body)!{/color}"
    new "{color=#000000}猛砸（躯干）！{/color}"
    old "{color=#000000}Batter (Limbs)!{/color}"
    new "{color=#000000}猛砸（四肢）！{/color}"
    old "{color=#000000}Batter (Head)!{/color}"
    new "{color=#000000}猛砸（头部）！{/color}"
    old "{color=#000000}Batter (Neck)!{/color}"
    new "{color=#000000}猛砸（颈部）！{/color}"
    old "{color=#000000}Weak Spot (Body)!{/color}"
    new "{color=#000000}弱点（躯干）！{/color}"
    old "{color=#000000}Weak Spot (Limbs)!{/color}"
    new "{color=#000000}弱点（四肢）！{/color}"
    old "{color=#000000}Weak Spot (Head)!{/color}"
    new "{color=#000000}弱点（头部）！{/color}"
    old "{color=#000000}Weak Spot (Neck)!{/color}"
    new "{color=#000000}弱点（颈部）！{/color}"
    old "{color=#000000}Powerful Thrust (Body)!{/color}"
    new "{color=#000000}强力突刺（躯干）！{/color}"
    old "{color=#000000}Powerful Thrust (Limbs)!{/color}"
    new "{color=#000000}强力突刺（四肢）！{/color}"
    old "{color=#000000}Powerful Thrust (Нead)!{/color}"
    new "{color=#000000}强力突刺（头部）！{/color}"
    old "{color=#000000}Powerful Thrust (Neck)!{/color}"
    new "{color=#000000}强力突刺（颈部）！{/color}"
    old "{color=#000000}Shield Ram{/color}"
    new "{color=#000000}盾牌冲撞{/color}"
    old "{color=#000000}Shield Bash{/color}"
    new "{color=#000000}盾牌猛击{/color}"
    old "{color=#000000}Resisted!{/color}"
    new "{color=#000000}被抵抗！{/color}"
    old "Pommel Strike"
    new "柄头猛击"
    old "{color=#000000}Pommel Strike!{/color}"
    new "{color=#000000}柄头猛击！{/color}"
    old "Pole to the Face"
    new "迎面一杆"
    old "{color=#000000}Pole to the Face!{/color}"
    new "{color=#000000}迎面一杆！{/color}"
    old "{size=-7}Foot Trip"
    new "{size=-7}绊脚"
    old "{size=-2}Foot Trip"
    new "{size=-2}绊脚"
    old "{size=-7}{color=#A9A9A9}Agility-based stun.{vspace=5}Can be resisted with certain items or high CRD."
    new "{size=-7}{color=#A9A9A9}基于敏捷的击晕。{vspace=5}可用特定物品或高协调（CRD）抵抗。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[shoes_leg_trip_stamina_consumption!i]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[shoes_leg_trip_stamina_consumption!i]"
    old "{color=#000000}Foot Trip!{/color}"
    new "{color=#000000}绊脚！{/color}"
    old "[plate_sabatons.name!ti]"
    new "[plate_sabatons.name!ti]"
    old "[silver_spurs.name!ti]"
    new "[silver_spurs.name!ti]"
    old "[golden_spurs.name!ti]"
    new "[golden_spurs.name!ti]"
    old "{color=#000000}Resisted ([resist_cause!ti])!{/color}"
    new "{color=#000000}被抵抗（[resist_cause!ti]）！{/color}"
    old "{size=-7}Fist to the Face"
    new "{size=-7}迎面一拳"
    old "{size=-2}Fist to the Face"
    new "{size=-2}迎面一拳"
    old "{size=-7}{color=#A9A9A9}Strength-based stun.{vspace=5}Can be resisted with high CRD."
    new "{size=-7}{color=#A9A9A9}基于力量的击晕。{vspace=5}可用高协调（CRD）抵抗。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[fist_to_the_face_stamina_consumption!i]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[fist_to_the_face_stamina_consumption!i]"
    old "{color=#000000}Fist to the Face!{/color}"
    new "{color=#000000}迎面一拳！{/color}"
    old "{size=-7}Dagger Feint"
    new "{size=-7}匕首佯攻"
    old "{size=-2}Dagger Feint"
    new "{size=-2}匕首佯攻"
    old "{size=-7}{color=#A9A9A9}Instantly blinds the target with a feint.{vspace=5}Does not consume the turn."
    new "{size=-7}{color=#A9A9A9}用佯攻立即致盲目标。{vspace=5}不消耗回合。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[fencing_dagger_attack_stamina_consumption!i]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[fencing_dagger_attack_stamina_consumption!i]"
    old "{color=#000000}Dagger feint!{/color}"
    new "{color=#000000}匕首佯攻！{/color}"
    old "{size=-7}Small Cut"
    new "{size=-7}小割伤"
    old "{size=-7}Big Cut"
    new "{size=-7}大割伤"
    old "{size=-2}Small Cut"
    new "{size=-2}小割伤"
    old "{size=-7}{color=#A9A9A9}Applies a 3 turn bleed on self.{vspace=5}Does not contribute towards Bloodloss."
    new "{size=-7}{color=#A9A9A9}对自身施加持续3回合的流血。{vspace=5}不累计失血过多进度。"
    old "{size=-2}Big Cut"
    new "{size=-2}大割伤"
    old "{size=-7}{color=#A9A9A9}Lowers player character's health by 10% of its max value."
    new "{size=-7}{color=#A9A9A9}将玩家角色的生命值降低其最大值的10%。"
    old "{color=#000000}[ritual_dagger.name!ti] used!{/color}"
    new "{color=#000000}[ritual_dagger.name!ti] 已使用！{/color}"
    old "{size=-7}Lights Out"
    new "{size=-7}熄灯"
    old "{size=-2}Lights Out"
    new "{size=-2}熄灯"
    old "{size=-7}{color=#A9A9A9}Stuns target.{vspace=5}The higher STR — the higher chance to ignore helmet."
    new "{size=-7}{color=#A9A9A9}击晕目标。{vspace=5}力量越高——无视头盔的概率越高。"
    old "{size=-7}{color=#A9A9A9}Stamina cost: {color=#006400}[blackjack_attack_stamina_consumption!i]"
    new "{size=-7}{color=#A9A9A9}体力消耗：{color=#006400}[blackjack_attack_stamina_consumption!i]"
    old "{color=#000000}Lights Out!{/color}"
    new "{color=#000000}熄灯！{/color}"
    old "{size=-7}Break Open"
    new "{size=-7}砸开"
    old "{size=-7}Final Blow"
    new "{size=-7}致命一击"
    old "{size=-7}Venomous Bite"
    new "{size=-7}毒牙噬咬"
    old "{size=-7}Open Vein"
    new "{size=-7}割开静脉"
    old "{size=-7}Shank"
    new "{size=-7}捅刺"
    old "{size=-7}Puncture"
    new "{size=-7}穿刺"
    old "{size=-7}Debilitating Stab"
    new "{size=-7}虚弱刺击"
    old "{size=-7}Wicked Stab"
    new "{size=-7}恶毒刺击"
    old "{size=-7}Awkward Stab"
    new "{size=-7}笨拙刺击"
    old "{size=-7}Нunter's Stab"
    new "{size=-7}猎人之刺"
    old "{size=-7}Crude Нack"
    new "{size=-7}粗蛮劈砍"
    old "{size=-2}Break Open"
    new "{size=-2}砸开"
    old "{size=-7}{color=#A9A9A9}Damages enemy armor by [rondel_dagger_attack_armor_damage!i] + 25% of STR.{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}对敌人护甲造成 [rondel_dagger_attack_armor_damage!i] + 力量值25% 的伤害。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Final Blow"
    new "{size=-2}致命一击"
    old "{size=-7}{color=#A9A9A9}Damage increased by [miseriecorde_bonus_damage_for_injury!i] for every injury the target has.{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}目标每有一处伤势，伤害提升 [miseriecorde_bonus_damage_for_injury!i]。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Venomous Bite"
    new "{size=-2}毒牙噬咬"
    old "{size=-7}{color=#A9A9A9}Poisons target. Effect grows stronger with low Virtue.{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}使目标中毒。美德越低，效果越强。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Open Vein"
    new "{size=-2}割开静脉"
    old "{size=-7}{color=#A9A9A9}Applies a [jambiya_attack_bleed_count!i] turn bleed or half the duration if attack was{vspace=1}partially blocked by armor.{vspace=1}Damage, hit and armor bypass chance improved by a{vspace=1}third of AGI. Requires the target to be feinted, stunned or{vspace=1}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}施加持续 [jambiya_attack_bleed_count!i] 回合的流血效果；若攻击被{vspace=1}护甲部分抵挡，则持续时间减半。{vspace=1}伤害、命中和护甲穿透概率提升敏捷{vspace=1}的三分之一。需要目标被佯攻、被击晕，或{vspace=1}体力较低（10% 或更低）。"
    old "{size=-2}Shank"
    new "{size=-2}捅刺"
    old "{size=-7}{color=#A9A9A9}Strikes the target [sharp_dagger_shank_charges_max] times into random body parts.{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}向目标的随机身体部位打击 [sharp_dagger_shank_charges_max] 次。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Puncture"
    new "{size=-2}穿刺"
    old "{size=-7}{color=#A9A9A9}Armor bypass chance increased by [mail_breaker_armor_bypass_bonus].{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}护甲穿透概率提升 [mail_breaker_armor_bypass_bonus]。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Debilitating Stab"
    new "{size=-2}虚弱刺击"
    old "{size=-7}{color=#A9A9A9}Increases target's fatigue level by [elegant_stiletto_fatigue_gain!i].{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}使目标的疲劳等级提升 [elegant_stiletto_fatigue_gain!i]。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Нunter's Stab"
    new "{size=-2}猎人之刺"
    old "{size=-7}{color=#A9A9A9}Multiplies damage done to animals by [hunting_knife_animal_damage_bonus_multiplier!i].{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}对动物造成的伤害乘以 [hunting_knife_animal_damage_bonus_multiplier!i]。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Wicked Stab"
    new "{size=-2}恶毒刺击"
    old "{size=-7}{color=#A9A9A9}Poisons target, aplies a bleed, lowers stamina and builds{vspace=5}up fatigue{vspace=5}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}使目标中毒，施加流血效果，降低体力并累积{vspace=5}疲劳。{vspace=5}伤害、命中和护甲穿透概率提升敏捷{vspace=5}的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Awkward Stab"
    new "{size=-2}笨拙刺击"
    old "{size=-7}{color=#A9A9A9}Damage, hit and armor bypass chance improved by a{vspace=5}third of AGI. Requires target to be feinted, stunned or{vspace=5}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}伤害、命中和护甲穿透概率提升{vspace=5}敏捷的三分之一。需要目标被佯攻、被击晕，或{vspace=5}体力较低（10% 或更低）。"
    old "{size=-2}Crude Нack"
    new "{size=-2}粗蛮劈砍"
    old "{size=-7}{color=#A9A9A9}Injury chance increased by[jambiya_attack_bleed_count!i].{vspace=1}Damage, hit and armor bypass chance improved by a{vspace=1}third of AGI. Requires the target to be feinted, stunned or{vspace=1}have low stamina (10% or less)."
    new "{size=-7}{color=#A9A9A9}致伤概率提升 [jambiya_attack_bleed_count!i]。{vspace=1}伤害、命中和护甲穿透概率提升{vspace=1}敏捷的三分之一。需要目标被佯攻、被击晕，或{vspace=1}体力较低（10% 或更低）。"
    old "{color=#000000}+[trait6] Fatigue!{/color}"
    new "{color=#000000}疲劳 +[trait6]！{/color}"
    old "Попадание в сердце"
    new "心脏被击中"
    old "Прострелен насквозь"
    new "被射穿"
    old "Болевой шок"
    new "疼痛休克"
    old "Разрыв сердца"
    new "心脏破裂"
    old "Прострелена рука"
    new "手臂被射穿"
    old "Прострелена нога"
    new "腿被射穿"
    old "Прострелено колено"
    new "膝盖被射穿"
    old "Перебита артерия"
    new "动脉被射断"
    old "Пробит череп"
    new "颅骨被击穿"
    old "Прострелена голова"
    new "头部被射穿"
    old "Треснул череп"
    new "颅骨开裂"
    old "(Голова, Глаза)"
    new "（头部，眼睛）"
    old "Прострелена шея"
    new "颈部被射穿"
    old "Перебиты позвонки"
    new "脊椎被射断"
    old "Шея сломана"
    new "脖子被折断"
    old "Голова разрублена"
    new "头部被劈开"
    old "Голова расколота"
    new "头部被劈裂"
    old "Расколот череп"
    new "颅骨被劈裂"
    old "Раздроблен череп"
    new "颅骨被砸碎"
    old "Голова расплющена"
    new "头部被砸扁"
    old "Голова размазана"
    new "头部被砸烂"
    old "Голова пробита"
    new "头部被击穿"
    old "Голова отрублена"
    new "头部被砍下"
    old "Голова с плеч"
    new "人头落地"
    old "Захлебнулся кровью"
    new "被鲜血呛死"
    old "Отрублена рука"
    new "手臂被砍下"
    old "Отрублена нога"
    new "腿被砍下"
    old "Отрублена кисть"
    new "手掌被砍下"
    old "Перерезана артерия"
    new "动脉被割断"
    old "Раздроблена рука"
    new "手臂被砸碎"
    old "Раздроблена нога"
    new "腿被砸碎"
    old "Раздроблена кисть"
    new "手掌被砸碎"
    old "Нокаутирован"
    new "被击倒"
    old "Вырублен"
    new "被击晕"
    old "Заколот насмерть"
    new "被刺死"
    old "Сброшен со стены"
    new "被推下墙"
    old "Разбился насмерть"
    new "摔死了"
    old "Вспорот живот"
    new "腹部被剖开"
    old "Сломаны ребра"
    new "肋骨断裂"
    old "Внутреннее кровотечение"
    new "内出血"
    old "Рассечена грудь"
    new "胸口被劈开"
    old "Остановка сердца"
    new "心跳停止"
    old "Остановка дыхания"
    new "呼吸停止"
    old "Проколот насквозь"
    new "被刺穿"
    old "Смертельное ранение"
    new "致命伤"
    old "{color=#8B0000}[action_type!ti]!{/color}"
    new "{color=#8B0000}[action_type!ti]！{/color}"
    old "{color=#000000}[enemy1!ti] is killed!{/color}"
    new "{color=#000000}[enemy1!ti] 被杀死！{/color}"
    old "{color=#000000}[enemy2!ti] is killed!{/color}"
    new "{color=#000000}[enemy2!ti] 被杀死！{/color}"
    old "{color=#000000}Weapon broken!{/color}"
    new "{color=#000000}武器损坏！{/color}"
    old "{color=#000000}Reputation (soldiers) -1!{vspace=5}(Timidity){/color}"
    new "{color=#000000}声望（士兵）-1！{vspace=5}（胆怯）{/color}"
    old "{color=#000000}Reputation (soldiers) -2!{vspace=5}(Timidity){/color}"
    new "{color=#000000}声望（士兵）-2！{vspace=5}（胆怯）{/color}"
    old "{color=#000000}Reputation (soldiers) -2{vspace=5}(Timidity)!{/color}"
    new "{color=#000000}声望（士兵）-2{vspace=5}（胆怯）！{/color}"
    old "{color=#000000}Virtue -1!{/color}"
    new "{color=#000000}美德 -1！{/color}"
    old "{color=#000000}Prestige -1!{/color}"
    new "{color=#000000}威望 -1！{/color}"
    old "{color=#000000}Reputation (soldiers) +1!{vspace=5}(Aggression){/color}"
    new "{color=#000000}声望（士兵）+1！{vspace=5}（好斗）{/color}"
    old "{color=#000000}Overwhelming Speed!{/color}"
    new "{color=#000000}速度惊人！{/color}"
    old "{color=#008000}Poisoned{color=#000000} (Trinket)!{/color}"
    new "{color=#008000}中毒{color=#000000}（饰品）！{/color}"
    old "{color=#000000}Accidental shield drop!{/color}"
    new "{color=#000000}盾牌意外脱手！{/color}"
    old "{color=#000000}Recover{/color}"
    new "{color=#000000}恢复{/color}"
    old "{color=#000000}You are at full stamina{/color}"
    new "{color=#000000}你已处于满体力状态{/color}"
    old "{color=#000000}Fail (reduced recovery)!{/color}"
    new "{color=#000000}失败（恢复效果降低）！{/color}"
